<script>
	$(document).ready(function () {
		$('#dataTables-emp').dataTable({
			"bPaginate": true,
			"bLengthChange": true,
			"bFilter": true,
			"bInfo": true,
			"bAutoWidth": true});
	});
	 
	function pilihEmp(kode_barang,nama_barang,merk_barang,stok_studio,ket,hj_whs,hj_whs2){
		  
		  var count_table_tbody_tr = document.getElementById("counterx").value;
		  
		  var table = document.getElementById("myTable");	  
		  var row = table.insertRow(-1);
		  var cell1 = row.insertCell(0);
		  var cell2 = row.insertCell(1);
		  var cell3 = row.insertCell(2);
		  var cell4 = row.insertCell(3);
		  var cell5 = row.insertCell(4);
		  var cell6 = row.insertCell(5);
		  var cell7 = row.insertCell(6);
		  var cell8 = row.insertCell(7);
		  var cell9 = row.insertCell(8);
		  
		  var rows = parseInt(count_table_tbody_tr) + 1;
		  
		  document.getElementById("counterx").value=rows;
		  
		  cell1.innerHTML = "<input type='text' class='form-control input-sm' name='kode_barang[]' value='"+kode_barang+"' readonly/> <input type='hidden' name='nama_tabel[]' value='device' readonly/>";
		  cell2.innerHTML = "<input type='text' class='form-control input-sm' name='nama_barang[]' value='"+merk_barang+""+nama_barang+"' readonly/> <input type='hidden' name='kode[]' value='kode_device' readonly/>";
		  cell3.innerHTML = "<input type='text' class='form-control input-sm' id='ket"+rows+"' name='ket[]' value='"+ket+"' readonly/>";
		  cell4.innerHTML = "<input type='text' class='form-control input-sm' id='stok_studio"+rows+"' name='stok_studio[]' value='"+stok_studio+"' readonly/>";
		  cell5.innerHTML = "<input type='text' class='form-control input-sm' id='hj_whs"+rows+"' name='hj_whs[]' value='"+hj_whs+"' onkeyup='coba("+rows+")' onchange='jual("+rows+")'/> <input type='hidden' id='hj_whs_lama"+rows+"' name='hj_whs_lama[]' value='"+hj_whs2+"' readonly/> <input type='hidden' id='hj_whs_baru"+rows+"' name='hj_whs_baru[]' value='"+hj_whs2+"' readonly/>";
		  cell6.innerHTML = "<input type='text' class='form-control input-sm' id='discount"+rows+"' name='discount[]' value='0' onkeyup='jual2("+rows+")'/>";
		  cell7.innerHTML = "<input type='text' class='form-control input-sm' id='qty"+rows+"' name='qty[]' value='1' onkeyup='jual2("+rows+")'/>";
		  cell8.innerHTML = "<input type='text' class='form-control input-sm' id='sub_total"+rows+"' name='sub_total[]' value='"+hj_whs+"' readonly/>";
		  cell9.innerHTML = "<input type='button' id='delete' class='btn btn-danger btn-sm mar-ed-button' name='delete' onclick='deleterow(this,"+rows+")' value='Hapus'/>";
		
		var total_biaya = document.getElementById("total_biaya").value;
		var total_biaya2 = total_biaya.replaceAll(".", "");
		
		var hj_whs2 = hj_whs.replaceAll(".", "");
		var hitung_total = parseInt(total_biaya2)+parseInt(hj_whs2);
		var hitung_total2 = hitung_total.toString().replaceAll(/(\d)(?=(\d\d\d)+(?!\d))/g, "$1.");
			document.getElementById("total_biaya").value=hitung_total2;
		
		var jml_pembayaran = document.getElementById("jml_pembayaran").value;
		var jml_pembayaran2 = jml_pembayaran.replaceAll(".", "");
		
		if (parseInt(jml_pembayaran2) < parseInt(hitung_total)){
			$("#button1").show();
			$("#button2").hide();
			document.getElementById("biaya_admin").value=0;
			document.getElementById("uang_kembali").value=0;
		} else {
			$("#button1").hide();
			$("#button2").show();
		}
		
		closeDetil();
	}   
</script>

<form action="" method="post" name="emplist" id="emplist">
	<div id="popupContact" style="width:75%; min-height:600px">
		<table width="100%">
			<tr>
				<td>
					<button class="btn btn-danger btn-circle right" type="button" onclick="closeDetil()"><i class="glyphicon glyphicon-remove"></i></button>
				</td>
			</tr>
		</table>
	<center>
	<div id="popupContactx">	
	<div class="panel panel-info" style="margin-right: 25px;margin-left: 25px;">
		<div class="panel-heading"><h3 class="title title-custom">List Data Perlengkapan (Device)</h3></div>	
		<div class="panel-body">
			<div class="col-lg-3 col-md-3 col-sm-12">	
				<select class = "form-control input-sm" width="15%" onclick="pilih_barang(this)">
					<option value="0">--Pilih Barang--</option>
					<option value="Liquid">Isi Ulang (Liquid)</option>
					<option value="Device">Perlengkapan (Device)</option>
					<option value="Aksesoris">Aksesoris</option>
					<option value="Atomizer">Atomizer</option>
				</select>
			</div>
		<div class="col-lg-12 col-md-12 col-sm-12">
			<br>
			<form action="" method="post" name="insdata" id="insdata">
				<div class="table-responsive">
					<div style="overflow:auto;height:440px;">
					<table style="font-size:12px;" class="table table-striped table-bordered table-hover" id="dataTables-emp" width="200%">
						<thead>
						<tr bgcolor="#4ECDC4">		
							<th width="15%">Kode Device</th>
							<th width="45%">Nama Device</th>
							<th width="10%">Stok Studio</th>
							<th width="20%">Keterangan</th>
							<th width="10%">Harga Jual Retail</th>
						</tr>
						</thead>
						<tbody>
						<?php
								 for($x=0; $x<count($this->data); $x++){
									 
										$kode_device 	= $this->data[$x]['kode_device'];
										$merk_device 	= $this->data[$x]['merk_device'];
										$nama_device 	= $this->data[$x]['nama_device'];
										$ket		 	= $this->data[$x]['ket'];
										$stok_studio 	= number_format($this->data[$x]['stok_studio'],0,",",".");
										$hj_whs	 	= number_format($this->data[$x]['hj_whs'],0,",",".");
										$hj_whs2		= $this->data[$x]['hj_whs'];
										$kode_supplier 	= $this->data[$x]['kode_supplier'];
									?>																		
											<td align="left"><a href="#" onclick="javascript:pilihEmp('<?php echo $kode_device; ?>','<?php echo $nama_device; ?>','<?php echo $merk_device; ?>','<?php echo $stok_studio; ?>','<?php echo $ket; ?>','<?php echo $hj_whs; ?>','<?php echo $hj_whs2; ?>')"><?php echo $kode_device;?></a></td>
											<td align="left"><?php echo $merk_device;?> - <?php echo $nama_device;?></td>
											<td align="left"><?php echo $stok_studio;?></td>
											<td align="left"><?php echo $ket;?></td>
											<td align="left"><?php echo $hj_whs;?></td>
										</tr>	
									<?php 
										}
									?>
						</tbody>
					</table>
					</div>
				</div>
			</form>
			</div>			
			<div id='popuptarget'></div>
		</div>
	</div>		
</div>
</center>
</div>
<div id='myDIVx'></div>
<div id="backgroundPopup"></div>
</form>
