<head>
	<link href="<?php echo $this->baseUrl(); ?>/css/select2.min.css" rel="stylesheet">
	<link href="<?php echo $this->baseUrl(); ?>/css/fileinput/fileinput.min.css" rel="stylesheet">
	<script src="<?php echo $this->baseUrl(); ?>/lib/select2.full.min.js"></script>
	<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
	<script src="<?php echo $this->baseUrl(); ?>/lib/jquery-ui-1.9.2.custom.min.js"></script>
</head>