<style>
#backgroundPopup{  

display:none;  
position:fixed;  
_position:absolute; /* hack for internet explorer 6*/  
height:100%;  
width:100%;  
top:0;  
left:0; 
/*background: rgba(0, 0, 0, 0) url("../img/popup-bg.png");*/
background:rgba(0,0,0,0.85);  
border:1px solid #cecece;  
z-index:1040;  


}  
 
 
.box-popup1{
	position:fixed;
	top:30px;
	left:30px;
	width:40px;
	height:30px;
}
 

#popupContact{  

display:none;  
position:fixed;  
_position:absolute; /* hack for internet explorer 6*/  
height:100%; 
width:90%;  
background:#acacac;  
z-index:999999;  
font-size:13px;  
overflow:auto;
top:2px;
bottom:10px;
padding:15px;
margin: 1%;
}  




#popupContact h1{  
text-align:left;  
color:#6FA5FD;  
font-size:22px;  
font-weight:bold;  
border-bottom:1px dotted #D3D3D3;  
padding-bottom:2px;  
margin-bottom:20px;  
}  
#popupContact textarea{width:90%;height:100px;}
#popupContactClose{  
font-size:14px;  
line-height:14px;  
right:6px;  
top:4px;  
position:absolute;  
color:#6fa5fd;  
font-weight:bold;  
width:16px;
cursor:pointer;
display:block;  
background:url(../images/cross.png)
} 


</style>
<form id="frm_postdata" name="frm_postdata" enctype="multipart/form-data" method="POST">
	<input type="hidden" name="currentPage" id="currentPage" size="6" maxlength="6" value="<?php echo $this->numPage;?>" class="inputbox2 narrowkey1"></input>
		<?php 
			$seq = $this->seq;
			//var_dump($seq);
			$seq += 1;
			$seq=str_pad($seq, 5, '0', STR_PAD_LEFT);
		?>
		<input type="hidden" id='seq' name='seq' value ='<?php echo $seq;?>'>
		<div id="popupview"></div>
		<div class="panel">
            <fieldset class="panel-dt">							
				<h4><i class="fa fa-angle-right"></i> Edit Pembelian Barang</h4>
						<br>
					<div class="col-sm-12">
						<table width="100%">
							<tr>
								<td width="10%"><font style="font-size:12px;font-weight:bold;">Nomor Order</font></td>
								<td width="1%">:</td>
								<td>
									<table>
										<td> <input name="no_order" id="no_order" type="text" maxlength="50" size="20" class="form-control input-sm" value="<?php echo $this->data[0]['no_order'];?>" readonly> </td>
										<td> &nbsp; <label id="no_order-error" for="no_order" class="error"></td>
									</table>
								</td>
							</tr> 
							<tr><td>&nbsp;</td></tr>
							<tr>
								<td width="10%"><font style="font-size:12px;font-weight:bold;">Tanggal Order</font></td>
								<td width="1%">:</td>
								<td>
									<table>
										<?php
											$tgl_order = date_create($this->data[0]['tgl_order']);
											$tgl_order = date_format($tgl_order,"d-m-Y");
										?>
										<td> <input name="tgl_order" id="tgl_order" type="text" maxlength="50" size="20" class="form-control input-sm" value="<?php echo $tgl_order;?>" readonly> </td>
										<td> &nbsp; <label id="tgl_order-error" for="tgl_order" class="error"></td>
									</table>
								</td>
							</tr> 
							<tr><td>&nbsp;</td></tr>
							<tr>
								<td width="10%"><font style="font-size:12px;font-weight:bold;">Nama Supplier</font></td>
								<td width="1%">:</td>
								<td>
									<table>
										<?php
											$kode_supplier = $this->data[0]['kode_supplier'];
											$supplier = $this->Pembayaransupplier_Service->getdatasupplierid($kode_supplier);
											$nama_supplier = $supplier[0]['nama_supplier'];
										?>
										<td> <input name="nama_supplier" id="nama_supplier" type="text" maxlength="50" size="20" class="form-control input-sm" value="<?php echo $nama_supplier;?>" readonly> </td>
										<td> &nbsp; <label id="nama_supplier-error" for="nama_supplier" class="error"></td>
									</table>
								</td>
							</tr>
							<tr><td>&nbsp;</td></tr>
							<tr>
								<td width="10%"><font style="font-size:12px;font-weight:bold;">Kode Supplier</font></td>
								<td width="1%">:</td>
								<td>
									<table>
										<td> <input name="kode_supplier2" id="kode_supplier2" type="text" maxlength="10" size="10" class="form-control input-sm" value="<?php echo $this->data[0]['kode_supplier']?>" readonly> </td>
										<td> </td>
									</table>
								</td>
							</tr> 
							<tr><td>&nbsp;</td></tr>
							<tr>
								<td width="10%"><font style="font-size:12px;font-weight:bold;">Alamat Supplier</font></td>
								<td width="1%">:</td>
								<td>
									<table>
										<td> <input name="alamat_supplier" id="alamat_supplier" type="text" maxlength="100" size="100" class="form-control input-sm" value="<?php echo $this->data2[0]['alamat_supplier']?>" readonly> </td>
										<td> </td>
									</table>
								</td>
							</tr> 
							<tr><td>&nbsp;</td></tr>
							<tr>
								<td width="10%"><font style="font-size:12px;font-weight:bold;">Status Barang Supplier</font></td>
								<td width="1%">:</td>
								<td>
									<table>
										<td> <input name="tipe" id="tipe" type="text" maxlength="20" size="15" class="form-control input-sm" value="<?php echo $this->data2[0]['tipe']?>" readonly> </td>
										<td> </td>
									</table>
								</td>
							</tr> 
							<tr><td>&nbsp;</td></tr>
							<tr>
								<td width="10%"><font style="font-size:12px;font-weight:bold;">Nomor Telepon</font></td>
								<td width="1%">:</td>
								<td>
									<table>
										<td> <input name="no_tlp" id="no_tlp" type="text" maxlength="20" size="15" class="form-control input-sm" value="<?php echo $this->data2[0]['no_tlp']?>" readonly> </td>
										<td> </td>
									</table>
								</td>
							</tr> 
							<tr><td>&nbsp;</td></tr>
							<tr>
								<td width="10%"><font style="font-size:12px;font-weight:bold;">Nomor Handphone / WA</font></td>
								<td width="1%">:</td>
								<td>
									<table>
										<td> <input name="no_hp" id="no_hp" type="text" maxlength="20" size="15" class="form-control input-sm" value="<?php echo $this->data2[0]['no_hp']?>" readonly> </td>
										<td> </td>
									</table>
								</td>
							</tr> 
							<tr><td>&nbsp;</td></tr>
							<tr>
								<td width="10%"><font style="font-size:12px;font-weight:bold;">Email</font></td>
								<td width="1%">:</td>
								<td>
									<table>
										<td> <input name="email" id="email" type="text" maxlength="25" size="25" class="form-control input-sm" value="<?php echo $this->data2[0]['email']?>" readonly> </td>
										<td> </td>
									</table>
								</td>
							</tr> 
							<tr><td>&nbsp;</td></tr>
						</table>
						<hr>
					<div class="col-lg-12 col-md-12 col-sm-12">
						<div align='left'>
							<b><u>DETAIL PEMBELIAN BARANG</u></b>
							<!--input type="button" class="right btn btn-success  btn-xs" style="font-weight:bold;" value="Tambah Barang" onclick="dataliquid()"-->
							<input type='hidden' name='counterx' id='counterx' value="<?php echo count($this->data3);?>">
						</div>
						<br>
						<table width="100%" id="myTable">
							<tr>
								<td> <font style="font-size:12px;font-weight:bold;">Kode Barang</font></td>
								<td> <font style="font-size:12px;font-weight:bold;">Nama Barang</font></td>
								<td> <font style="font-size:12px;font-weight:bold;">Keterangan</font></td>
								<td> <font style="font-size:12px;font-weight:bold;">Stok  Gudang</font></td>
								<td> <font style="font-size:12px;font-weight:bold;">Harga Beli</font></td>
								<td> <font style="font-size:12px;font-weight:bold;">QTY</font></td>
								<td> <font style="font-size:12px;font-weight:bold;">Sub Total</font></td>
								<td> <font style="font-size:12px;font-weight:bold;"></font></td>
							</tr>
								<?php
									$nama_barang  = '';
									$ket		  = '';
									$stok_gudang  = '';
								 for($d=0; $d<count($this->data3); $d++){
									
										$kode_barang 	= $this->data3[$d]['kode_barang'];
										$harga_beli 	= number_format($this->data3[$d]['harga_beli'],0,",",".");
										$harga_beli2 	= $this->data3[$d]['harga_beli'];
										$qty 			= $this->data3[$d]['qty'];
										$sub_total		= number_format($this->data3[$d]['sub_total'],0,",",".");
										$jenis_barang	= $this->data3[$d]['jenis_barang'];
										$kode_jenis_barang = $this->data3[$d]['kode_jenis_barang'];
										
										$barang = $this->Pembayaransupplier_Service->getdatabarangid($kode_barang);
										if(isset($barang[0]['nama_barang'])){ $nama_barang = $barang[0]['nama_barang'];}
										if(isset($barang[0]['ket'])){ $ket = $barang[0]['ket'];}
										if(isset($barang[0]['stok_gudang'])){ $stok_gudang = $barang[0]['stok_gudang'];}
										/* $nama_barang  = $barang[0]['nama_barang'];
										$ket		  = $barang[0]['ket'];
										$stok_gudang  = $barang[0]['stok_gudang']; */
									?>	
							<tr>
								<td><input type='text' class='form-control input-sm' name='kode_barang[]' value='<?php echo $kode_barang;?>' readonly></td>
								<td><input type='text' class='form-control input-sm' name='nama_barang[]' value='<?php echo $nama_barang;?>' readonly> <input type='hidden' name='kode[]' value='<?php echo $kode_jenis_barang;?>' readonly></td>
								<td><input type='text' class='form-control input-sm' name='ket[]' value='<?php echo $ket;?>' readonly> <input type='hidden' name='nama_tabel[]' value='<?php echo $jenis_barang;?>' readonly></td>
								<td><input type='text' class='form-control input-sm' id='stok_gudang<?php echo $d+1;?>' name='stok_gudang[]' value='<?php echo $stok_gudang;?>' readonly> <input type='hidden' id='stok_gudang_baru<?php echo $d+1;?>' name='stok_gudang_baru[]' value='<?php echo $stok_gudang;?>' readonly></td>
								<td><input type='text' class='form-control input-sm' id='harga_beli<?php echo $d+1;?>' name='harga_beli[]' value='<?php echo $harga_beli;?>' onkeyup='beli(<?php echo $d+1;?>)' readonly> <input type='hidden' id='harga_beli_lama<?php echo $d+1;?>' name='harga_beli_lama[]' value='<?php echo $harga_beli2;?>' readonly> <input type='hidden' id='harga_beli_baru<?php echo $d+1;?>' name='harga_beli_baru[]' value='<?php echo $harga_beli2;?>' readonly></td>
								<td><input type='text' class='form-control input-sm' id='qty<?php echo $d+1;?>' name='qty[]' value='<?php echo $qty;?>' onkeyup='beli(<?php echo $d+1;?>)' readonly></td>
								<td><input type='text' class='form-control input-sm' id='sub_total<?php echo $d+1;?>' name='sub_total[]' value='<?php echo $sub_total;?>' readonly></td>	
							</tr>
						 <?php } ?>
						</table>
				</div>
				<div class="col-lg-8 col-md-8 col-sm-12">	
					<div class="showback">
					<div align='left'><b><u>RIWAYAT PEMBAYARAN</u></b></div>
					<br>
					  <table style="font-size:12px;" class="table table-striped table-bordered table-hover" id="dataTables-emp">
							<thead>
							<tr bgcolor="#4ECDC4">
								<th width="15%" style="text-align:center;">Tanggal Bayar</th>
								<th width="15%" style="text-align:center;">Nominal Bayar</th>
								<th width="15%" style="text-align:center;">Sisa Pembayaran</th>
								<th width="25%" style="text-align:center;">Metode Bayar</th>
								<th width="30%" style="text-align:center;">Catatan</th>
							</tr>
							</thead>
							<tbody>
								<?php
								 for($e=0; $e<count($this->data4); $e++){
										$id_hutang 			= $this->data4[$e]['id_hutang'];
										$tgl_pembayaran 	= date_create($this->data4[$e]['tgl_pembayaran']);
										$tgl_pembayaran		= date_format($tgl_pembayaran,"d-m-Y");
										$jumlah_pembayaran  = number_format($this->data4[$e]['jumlah_pembayaran'],0,",",".");
										$sisa_pembayaran 	= number_format($this->data4[$e]['sisa_pembayaran'],0,",",".");
										$metode_pembayaran 	= $this->data4[$e]['metode_pembayaran'];
										$no_rekening 	= $this->data4[$e]['no_rekening'];
										$catatan 	= $this->data4[$e]['catatan'];
										if($metode_pembayaran == 'Transfer'){
											$rekening = $no_rekening;
										} else {
											$rekening = 'Cash / Tunai';
										}
										$row_terakhir = count($this->data4) - 1;
										
										$data_net_total  = $this->data[0]['net_total'];
										$data_sisa_bayar = $this->data[0]['sisa_bayar'];
										$terbayar = $data_net_total - $data_sisa_bayar;
									?>	
							<tr>
								<td align="center"><?php echo $tgl_pembayaran;?></td>
								<?php
								if($e == $row_terakhir){ ?>
									<td align="center">
										<p id="fix"><?php echo $jumlah_pembayaran;?> &nbsp; <a href="#" title="edit" onclick="edit()"><i class="fa fa-edit pad-ico-button"></i></a></p> 
										<p id="edited">
											<input type="text" class="form-control input-sm" id="jumlah_pembayaran<?php echo $e;?>" name="jumlah_pembayaran" value="<?php echo $jumlah_pembayaran;?>" onkeyup="ubah_bayar(this,<?php echo $e;?>)"> 
											<input type="hidden" id="pembayaran<?php echo $e;?>" name="pembayaran" value="<?php echo $jumlah_pembayaran;?>"> 
											<button type="button" class="btn btn-primary btn-xs" onCLick="PostData2()">Simpan</button>
										</p>
									</td>
								<?php } else { ?>
									<td align="center"><?php echo $jumlah_pembayaran;?></td>
								<?php } ?>
								<td align="center">
									<?php
									if($e == $row_terakhir){ ?>
										<p id="sisa<?php echo $e;?>"><?php echo $sisa_pembayaran;?></p>
										<input type="hidden" id="sisa_pembayaran<?php echo $e;?>" name="sisa_pembayaran" value="<?php echo $sisa_pembayaran;?>"> 
										<input type="hidden" id="terbayar<?php echo $e;?>" name="terbayar" value="<?php echo $terbayar;?>"> 
										<input type="hidden" id="id_hutang<?php echo $e;?>" name="id_hutang" value="<?php echo $id_hutang;?>"> 
									<?php } else { ?>
										<p id="sisa<?php echo $e;?>"><?php echo $sisa_pembayaran;?></p>
										<input type="hidden" id="sisa_pembayaran<?php echo $e;?>" value="<?php echo $sisa_pembayaran;?>"> 
										<input type="hidden" id="terbayar<?php echo $e;?>" value="<?php echo $terbayar;?>"> 
										<input type="hidden" id="id_hutang<?php echo $e;?>" value="<?php echo $id_hutang;?>"> 
								<?php } ?>
								</td>
								<td align="center"><?php echo $rekening;?></td>
								<?php
								if($e == $row_terakhir){ ?>
								<td align="center">
									<p id="fix_catatan"><?php echo $catatan;?></p> 
									<p id="edited_catatan"><input type="text" class="form-control input-sm" id="catat<?php echo $e;?>" name="catat" value="<?php echo $catatan;?>"></p> 
									<label id="catat-error" for="catat" class="error"></label>
								</td>
								<?php } else { ?>
									<td align="center"><?php echo $catatan;?></td>
								<?php } ?>
							</tr>
						 <?php } ?>
						 </tbody>
					</table>
				</div>
				</div>
				<div class="col-lg-4 col-md-4 col-sm-12">	
					<table width="100%" id="myTable2">
						<tr><td>&nbsp;</td></tr>
							<tr>
								<td width="5%">&nbsp; <label id="total-error" for="total" class="error"></td>
								<td width="25%"><font style="font-size:12px;font-weight:bold;">Total</font></td>
								<td width="35%"><input type='text' class="form-control input-sm" name='total' id='total' value='<?php echo number_format($this->data[0]['total'],0,",",".");?>' readonly> </td>
							</tr>
							<tr><td>&nbsp;</td></tr>
							<tr>
								<td ></td>
								<td><font style="font-size:12px;font-weight:bold;">Biaya Kirim</font></td>
								<td> <input type='text' class="form-control input-sm" name='biaya_kirim' id='biaya_kirim' value='<?php echo number_format($this->data[0]['biaya_kirim'],0,",",".");?>' onkeyup='biaya()' readonly> </td>
							</tr>
							<tr><td  align="right"><label id="biaya_kirim-error" for="biaya_kirim" class="error"></td></tr>
							<tr>
								<td ></td>
								<td><font style="font-size:12px;font-weight:bold;">Diskon</font></td>
								<td> <input type='text' class="form-control input-sm" name='diskon' id='diskon' value='<?php echo number_format($this->data[0]['diskon'],0,",",".");?>' onkeyup='datadiskon()' readonly> </td>
							</tr>
							<tr><td  align="right"><label id="diskon-error" for="diskon" class="error"></td></tr>
							<tr>
								<td ></td>
								<td><font style="font-size:12px;font-weight:bold;">Net Total</font></td>
								<td> <input type='text' class="form-control input-sm" name='net_total' id='net_total' value='<?php echo number_format($this->data[0]['net_total'],0,",",".");?>' readonly> </td>
							</tr>
							<tr><td>&nbsp;</td></tr>
							<tr>
								<td ></td>
								<td><font style="font-size:12px;font-weight:bold;">Sisa Pembayaran</font></td>
								<td> <input type='text' class="form-control input-sm" name='sisa_bayar' id='sisa_bayar' value='<?php echo number_format($this->data[0]['sisa_bayar'],0,",",".");?>' readonly> </td>
							</tr>
							<tr><td>&nbsp;</td></tr>
							<tr>
								<td ></td>
								<td><font style="font-size:12px;font-weight:bold;">Jumlah Bayar</font></td>
								<td> 
									<input type='hidden' name='telah_dibayar' id='telah_dibayar' value='<?php echo number_format($this->data[0]['jml_bayar_dp'],0,",",".");?>' readonly> 
									<input type='text' class="form-control input-sm" name='jml_bayar_dp' id='jml_bayar_dp' value='' onkeyup='jumlahdp()'> 
									<input type='hidden' name='total_bayar' id='total_bayar' value='' readonly> 
								</td>
							</tr>
							<tr><td colspan='3' align="right"><label id="jml_bayar_dp-error" for="jml_bayar_dp" class="error"></td></tr>
							<tr>
								<td colspan='2'></td>
								<td> 
									<input type="radio" id="metode_bayar_a" name="metode_bayar" value="Hutang" onclick='lunasin()' checked>
									<label for="vehicle1"> Cicil</label> &nbsp;&nbsp;&nbsp;
									<input type="radio" id="metode_bayar_b" name="metode_bayar" value="Lunas" onclick='lunasin2()'>
									<label for="vehicle2"> Lunas</label>
								</td>
							</tr>
							<tr><td>&nbsp;</td></tr>
							<tr>
								<td ></td>
								<td><font style="font-size:12px;font-weight:bold;">Sisa Hutang</font></td>
								<td> <input type='text' class="form-control input-sm" name='sisa_hutang' id='sisa_hutang' value='<?php echo number_format($this->data[0]['sisa_bayar'],0,",",".");?>' readonly> </td>
							</tr>
							<tr><td>&nbsp;</td></tr>
							<tr>
								<td ></td>
								<td><font style="font-size:12px;font-weight:bold;">Cara Pembayaran</font></td>
								<td> 
									<select id="metode_bayar2" name="metode_bayar2" class = "form-control input-sm" width="15%" onclick="metodebayar(this)">
										<option value="0">--Pilih Cara Pembayaran--</option>
										<option value="Transfer">Transfer</option>
										<option value="Cash">Cash</option>
									</select>
								</td>
							</tr>
							<tr><td  align="right"><label id="metode_bayar2-error" for="metode_bayar2" class="error"></td></tr>
							<tr id='transfer'>
								<td ></td>
								<td width="10%"><font style="font-size:12px;font-weight:bold;">Sumber Dana</font></td>
								<td>	

								 <!--   menampilkan semua bang transfer    -->               
			                  <select id="no_rek" name="no_rek" class = "form-control input-sm" width="15%">
			                    <option value="0">--Pilih Sumber Dana--</option>

			                    <?php  
			                      for($x=0; $x<count($this->rek); $x++){ 
			                      $cek_rek = $this->rek[$x]['nama_akun'].' - '.$this->rek[$x]['no_akun'] .' ('.$this->rek[$x]['nama_cabang_pembuka'].')';
			                      $id = $this->rek[$x]['id'];
			                    ?>
			                    <option value="<?php echo $id;?>"><?php echo $cek_rek;?></option>
			                    <?php } ?>
			                  </select>
			                  <!--   menampilkan semua bang transfer    -->   

			                  <select id="cash" name="cash" class = "form-control input-sm" width="15%">
			                  <option value="0">--Pilih Sumber Dana--</option>
			                    <?php  
			                      for($x=0; $x<count($this->cash); $x++){ 
			                      $cek_rek = $this->cash[$x]['nama_akun'];
			                      $id = $this->cash[$x]['id'];
			                    ?>
			                    <option value="<?php echo $id;?>"><?php echo $cek_rek;?></option>
			                    <?php } ?>
			                  </select>

								</td>
							</tr>
							<tr id='transfer2'><td  align="right"><label id="no_rek-error" for="no_rek" class="error"></td></tr>
							<tr>
								<td ></td>
								<td><font style="font-size:12px;font-weight:bold;">Catatan</font></td>
								<td> <input type='text' class="form-control input-sm" name='catatan' id='catatan' value='<?php if(isset($this->data[0]['catatan'])){ echo $this->data[0]['catatan'];}?>'> </td>
							</tr>
							<tr><td>&nbsp;</td></tr>
					</table>
				</div>	
			</fieldset>
		</div>
		
	</div>
</div>
<div class="col-lg-12">
<div class="form-group form-group-bottom" align="right">
						<input type="hidden" id="proses" name="proses" value="<?php echo $this->proses?>">	
						<br><br>
							
							<a href="pembayaransupplier">
							<button type="button" class="btn btn-theme02">
								<span class="fa fa-backward"></span> &nbsp;Kembali
							</button></a>
							<button type="button" class="btn btn-theme03" onCLick="PostData()">
								<span class="fa fa-save"></span> &nbsp;Simpan
							</button>
							
			</div>
</div>
</form>
  <script src="<?php echo $this->baseUrl();?>/lib/jquery.form.js"></script>
  <link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl();?>/css/sweetalert.css">
  <script src="<?php echo $this->baseUrl();?>/lib/sweetalert.min.js"></script>   
  <script src="<?php echo $this->baseUrl();?>/lib/jquery.scrollTo.min.js"></script>
  <script src="<?php echo $this->baseUrl();?>/lib/jquery.nicescroll.js" type="text/javascript"></script>
<script>
	$("#fix").show();
	$("#edited").hide();
	$("#fix_catatan").show();
	$("#edited_catatan").hide();
	$("#no_rek").hide();
	$("#cash").hide();
	$("#transfer").hide();
	$("#transfer2").hide();
	
	

	function edit() {
		$("#fix").hide();
		$("#edited").show();
		$("#fix_catatan").hide();
		$("#edited_catatan").show();
		$("#cash").hide();
	}
	
	function ubah_bayar(x,y) {
		var bayar = x.value;
		var bayar2 = bayar.replaceAll(".", "");
		var bayar3 = bayar2.toString().replaceAll(/(\d)(?=(\d\d\d)+(?!\d))/g, "$1.");
			document.getElementById("jumlah_pembayaran"+y).value=bayar3;
		
		var y1 = parseInt(y) - parseInt(1);
		var sisa_pembayaran = document.getElementById('sisa_pembayaran'+y1).value;
		var sisa_pembayaran2 = sisa_pembayaran.replaceAll(".", "");
		
		if( parseInt(bayar2) >  parseInt(sisa_pembayaran2)){
			document.getElementById('catat-error').innerHTML ="<span style='color: red;'Nominal bayar melebihi sisa pembayaran.</span>";
			document.getElementById("jumlah_pembayaran"+y).focus();
			document.getElementById("jumlah_pembayaran"+y).value='0';
			var bayar = document.getElementById("jumlah_pembayaran"+y).value;
			var bayar2 = bayar.replaceAll(".", "");
		} else {
			document.getElementById('catat-error').innerHTML ='';
		}
		
		var hitung =  parseInt(sisa_pembayaran2) - parseInt(bayar2);
		var hitung2 = hitung.toString().replaceAll(/(\d)(?=(\d\d\d)+(?!\d))/g, "$1.");
			document.getElementById("sisa_pembayaran"+y).value=hitung2;
			document.getElementById("sisa"+y).innerHTML=hitung2;
		
		var terbayar = document.getElementById('terbayar'+y1).value;
		var terbayar2 = terbayar.replaceAll(".", "");
		var pembayaran = document.getElementById('pembayaran'+y).value;
		var pembayaran2 = pembayaran.replaceAll(".", "");
		
		var hitung_bayar = parseInt(terbayar2) - parseInt(pembayaran2);
		
		var hitung_terbayar_baru = parseInt(hitung_bayar) + parseInt(bayar2);
		var hitung_terbayar_baru2 = hitung_terbayar_baru.toString().replaceAll(/(\d)(?=(\d\d\d)+(?!\d))/g, "$1.");
			document.getElementById("terbayar"+y).value=hitung_terbayar_baru2;
	}
	
	function loadPopup() {
		var popupStatus = 0;
		if (popupStatus == 0) {
			jQuery("#backgroundPopup").css({"opacity": "1"});
			jQuery("#backgroundPopup").fadeIn("fast");
			jQuery("#popupContact").fadeIn("fast");
			popupStatus = 1
		}
	}

	function centerPopup() {
		var windowWidth = document.documentElement.clientWidth;
		var windowHeight = "1000%";
		var popupHeight = jQuery("#popupContact").height();
		var popupWidth = jQuery("#popupContact").width();
	}

	function closePopup() {
		document.getElementById('popupContact').style.display = "none";
		document.getElementById('backgroundPopup').style.display = "none";
	}

	function disablePopup() {
		document.getElementById('popupContact').style.display = "none";
		document.getElementById('backgroundPopup').style.display = "none";
	}
		
	function dataliquid(){
		var seq = document.getElementById('seq').value;
		
		//alert('maintain'); 
		
		var url = '<?php echo $this->basePath; ?>/pembayaransupplier/dataliquid';
		var opt = {seq:seq};
		
		jQuery.get(url,opt, function(data) {			
			jQuery("#popupview").html(data);
			centerPopup(); 
			loadPopup();		
		})
	}
	
	function datadevice(){
		var seq = document.getElementById('seq').value;
		
		//alert('maintain'); 
		
		var url = '<?php echo $this->basePath; ?>/pembayaransupplier/datadevice';
		var opt = {seq:seq};
		
		jQuery.get(url,opt, function(data) {			
			jQuery("#popupview").html(data);
			centerPopup(); 
			loadPopup();		
		})
	}
	
	function dataaksesoris(){
		var seq = document.getElementById('seq').value;
		
		//alert('maintain'); 
		
		var url = '<?php echo $this->basePath; ?>/pembayaransupplier/dataaksesoris';
		var opt = {seq:seq};
		
		jQuery.get(url,opt, function(data) {			
			jQuery("#popupview").html(data);
			centerPopup(); 
			loadPopup();		
		})
	}
	
	function dataatomizer(){
		var seq = document.getElementById('seq').value;
		
		//alert('maintain'); 
		
		var url = '<?php echo $this->basePath; ?>/pembayaransupplier/dataatomizer';
		var opt = {seq:seq};
		
		jQuery.get(url,opt, function(data) {			
			jQuery("#popupview").html(data);
			centerPopup(); 
			loadPopup();		
		})
	}
	
	function getSelectValue(){
		var selectedValue = document.getElementById("kode_supplier").value;
		var res = selectedValue.split(",");
		var kode_supplier = res[0];
		var alamat = res[1];
		var tipe = res[2];
		var no_tlp = res[3];
		var no_hp = res[4];
		var email = res[5];
		
		document.getElementById("kode_supplier2").value = kode_supplier;
		document.getElementById("alamat_supplier").value = alamat;
		document.getElementById("tipe").value = tipe;
		document.getElementById("no_tlp").value = no_tlp;
		document.getElementById("no_hp").value = no_hp;
		document.getElementById("email").value = email;
	}
                                                                                                                                     
	
	function PostData(){
		//alert('Testing2');
        $("#frm_postdata").ajaxSubmit(post_data);
    }
	
	var post_data = {
		target:'',
		beforeSubmit: function() {	
			var jml_bayar_dp	  = document.getElementById('jml_bayar_dp').value;
			var metode_bayar2	  = document.getElementById('metode_bayar2').value;
			var no_rek	  		  = document.getElementById('no_rek').value;
				
				if (!jml_bayar_dp) {
					document.getElementById('jml_bayar_dp-error').innerHTML ="<span style='color: red;'>Jumlah Bayar Harus Diisi.</span>";
					document.getElementById('jml_bayar_dp').focus();
					exit;
				}else document.getElementById('jml_bayar_dp-error').innerHTML ='';
				
				if (metode_bayar2=='0') {
					document.getElementById('metode_bayar2-error').innerHTML ="<span style='color: red;'>Metode Bayar Harus Dipilih.</span>";
					document.getElementById('metode_bayar2').focus();
					exit;
				}else document.getElementById('metode_bayar2-error').innerHTML ='';
				
				if(metode_bayar2 == 'Transfer'){
					if (no_rek=='0') {
						document.getElementById('no_rek-error').innerHTML ="<span style='color: red;'>Bank Transfer Harus Dipilih.</span>";
						document.getElementById('no_rek').focus();
						exit;
					}else document.getElementById('no_rek-error').innerHTML ='';
				}
			}, 
		success:function(){	
			swal({
				    title: 'Order Sukses !',
				    text: 'Auto Close...',
				    icon: 'success',
				    timer: 4000,
				    showConfirmButton: false,
				})
			location.href="#";		
			location.reload(true)
		},
		url: '<?php echo $this->baseUrl();?>/pembayaransupplier/kirimdataedit',
		type: 'post',
		resetForm: false
	};
	
	function isNumber(evt) {
        var iKeyCode = (evt.which) ? evt.which : evt.keyCode
        if (iKeyCode != 46 && iKeyCode > 31 && (iKeyCode < 48 || iKeyCode > 57))
            return false;

        return true;
    } 
	
	function closeDetil(){
	document.getElementById('popupContact').style.display = "none";
	disablePopup();
	}
	
	function deleterow(button,rows){
		var x = button.parentNode.parentNode.rowIndex;
		var total = document.getElementById("total").value;
		var total2 = total.replaceAll(".", "");
		var sub_total = document.getElementById("sub_total"+rows).value;
		var sub_total2 = sub_total.replaceAll(".", "");
		
		var biaya_kirim = document.getElementById("biaya_kirim").value;
		var biaya_kirim2 = biaya_kirim.replaceAll(".", "");
		var diskon = document.getElementById("diskon").value;
		var diskon2 = diskon.replaceAll(".", "");
		var jml_bayar_dp = document.getElementById("jml_bayar_dp").value;
		var jml_bayar_dp2 = jml_bayar_dp.replaceAll(".", "");
		
		var hitung_total = parseInt(total2) - parseInt(sub_total2)
		var hitung_total2 = hitung_total.toString().replaceAll(/(\d)(?=(\d\d\d)+(?!\d))/g, "$1.");
		document.getElementById("total").value=hitung_total2;
		
		var hitung_net_total = hitung_total + parseInt(biaya_kirim2) - parseInt(diskon2);
		var hitung_net_total2 = hitung_net_total.toString().replaceAll(/(\d)(?=(\d\d\d)+(?!\d))/g, "$1.");
		document.getElementById("net_total").value=hitung_net_total2;
		
		var hitung_sisa_bayar = hitung_net_total - parseInt(jml_bayar_dp2);
		var hitung_sisa_bayar2 = hitung_sisa_bayar.toString().replaceAll(/(\d)(?=(\d\d\d)+(?!\d))/g, "$1.");
		document.getElementById("sisa_bayar").value=hitung_sisa_bayar2;
		
		document.getElementById("myTable").deleteRow(x);
		
	}
	
	function beli(button){
		var x = button;
		
		var total = document.getElementById("total").value;
		var total2 = total.replaceAll(".", "");
		var sub_total = document.getElementById("sub_total"+x).value;
		var sub_total2 = sub_total.replaceAll(".", "");
		
		var hitung_total = parseInt(total2) - parseInt(sub_total2);
		var qty = document.getElementById("qty"+x).value;
		
		var harga_beli = document.getElementById("harga_beli"+x).value;
		var harga_beli2 = harga_beli.replaceAll(".", "");
		var harga_beli3 = harga_beli2.toString().replaceAll(/(\d)(?=(\d\d\d)+(?!\d))/g, "$1.");
		document.getElementById("harga_beli"+x).value=harga_beli3;
		
		var kali = qty * harga_beli2;
		var kali2 = kali.toString().replaceAll(/(\d)(?=(\d\d\d)+(?!\d))/g, "$1.");
		
		document.getElementById("sub_total"+x).value=kali2;
		
		var kurangin = parseInt(hitung_total) + parseInt(kali);
		var kurangin2 = kurangin.toString().replaceAll(/(\d)(?=(\d\d\d)+(?!\d))/g, "$1.");
		document.getElementById("total").value=kurangin2;
		
		var biaya_kirim = document.getElementById("biaya_kirim").value;
		var biaya_kirim2 = biaya_kirim.replaceAll(".", "");
		var diskon = document.getElementById("diskon").value;
		var diskon2 = diskon.replaceAll(".", "");
		
		var net_total = parseInt(kurangin)+parseInt(biaya_kirim2)-parseInt(diskon2);
		var net_total2 = net_total.toString().replaceAll(/(\d)(?=(\d\d\d)+(?!\d))/g, "$1.");
			document.getElementById("net_total").value=net_total2;
			document.getElementById("sisa_bayar").value=net_total2;
			
		var stok_gudang = document.getElementById("stok_gudang"+x).value;
		var harga_beli_lama = document.getElementById("harga_beli_lama"+x).value;
		var jumlah1 =  parseInt(stok_gudang) *  parseInt(harga_beli_lama);
		var jumlah2 = parseInt(stok_gudang) + parseInt(qty);
		
		var jumlah3 = parseInt(jumlah1) + parseInt(kali);
		
		var jumlah4 = parseInt(jumlah3) / parseInt(jumlah2);
		
		document.getElementById("stok_gudang_baru"+x).value=jumlah2;
		document.getElementById("harga_beli_baru"+x).value=jumlah4;
	}
	
	function biaya(){
		var total = document.getElementById("total").value;
		var total2 = total.replaceAll(".", "");
		var biaya_kirim = document.getElementById("biaya_kirim").value;
		var biaya_kirim2 = biaya_kirim.replaceAll(".", "");
		var biaya_kirim3 = biaya_kirim2.toString().replaceAll(/(\d)(?=(\d\d\d)+(?!\d))/g, "$1.");
			document.getElementById("biaya_kirim").value=biaya_kirim3;
		
		var diskon = document.getElementById("diskon").value;
		var diskon2 = diskon.replaceAll(".", "");
		
		var net_total = parseInt(total2)+parseInt(biaya_kirim2)-parseInt(diskon);
		var net_total2 = net_total.toString().replaceAll(/(\d)(?=(\d\d\d)+(?!\d))/g, "$1.");
			document.getElementById("net_total").value=net_total2;
			document.getElementById("sisa_bayar").value=net_total2;
	}
	
	function datadiskon(){
		var total = document.getElementById("total").value;
		var total2 = total.replaceAll(".", "");
		var biaya_kirim = document.getElementById("biaya_kirim").value;
		var biaya_kirim2 = biaya_kirim.replaceAll(".", "");
		var diskon = document.getElementById("diskon").value;
		var diskon2 = diskon.replaceAll(".", "");
		var diskon3 = diskon2.toString().replaceAll(/(\d)(?=(\d\d\d)+(?!\d))/g, "$1.");
			document.getElementById("diskon").value=diskon3;
		
		var net_total = parseInt(total2)+parseInt(biaya_kirim2)-parseInt(diskon2);
		var net_total2 = net_total.toString().replaceAll(/(\d)(?=(\d\d\d)+(?!\d))/g, "$1.");
			document.getElementById("net_total").value=net_total2;
			document.getElementById("sisa_bayar").value=net_total2;
	}
	
	function jumlahdp(){
		var sisa_bayar = document.getElementById("sisa_bayar").value;
		var sisa_bayar2 = sisa_bayar.replaceAll(".", "");
		var jml_bayar_dp = document.getElementById("jml_bayar_dp").value;
		var jml_bayar_dp2 = jml_bayar_dp.replaceAll(".", "");
		var jml_bayar_dp3 = jml_bayar_dp2.toString().replaceAll(/(\d)(?=(\d\d\d)+(?!\d))/g, "$1.");
			document.getElementById("jml_bayar_dp").value=jml_bayar_dp3;
		
		if( parseInt(jml_bayar_dp2) >  parseInt(sisa_bayar2)){
			document.getElementById('jml_bayar_dp-error').innerHTML ="<span style='color: red;'>Jumlah bayar melebihi sisa pembayaran.</span>";
			document.getElementById('jml_bayar_dp').focus();
			document.getElementById("jml_bayar_dp").value='0';
			var jml_bayar_dp = document.getElementById("jml_bayar_dp").value;
			var jml_bayar_dp2 = jml_bayar_dp.replaceAll(".", "");
		} else {
			document.getElementById('jml_bayar_dp-error').innerHTML ='';
		}
			
		var telah_dibayar = document.getElementById("telah_dibayar").value;
		var telah_dibayar2 = telah_dibayar.replaceAll(".", "");
		
		var jumlah_total_bayar = parseInt(telah_dibayar2)+parseInt(jml_bayar_dp2);
		var jumlah_total_bayar2 = jumlah_total_bayar.toString().replaceAll(/(\d)(?=(\d\d\d)+(?!\d))/g, "$1.");
			document.getElementById("total_bayar").value=jumlah_total_bayar2;
		
		var sisa_hutang = parseInt(sisa_bayar2)-parseInt(jml_bayar_dp2);
		var sisa_hutang2 = sisa_hutang.toString().replaceAll(/(\d)(?=(\d\d\d)+(?!\d))/g, "$1.");
			document.getElementById("sisa_hutang").value=sisa_hutang2;
	}
	
	function lunasin(){
		var sisa_bayar = document.getElementById("sisa_bayar").value;
		var sisa_bayar2 = sisa_bayar.replaceAll(".", "");
			document.getElementById("jml_bayar_dp").value='0';
		var jml_bayar_dp = document.getElementById("jml_bayar_dp").value;
		var jml_bayar_dp2 = jml_bayar_dp.replaceAll(".", "");
		
		var sisa_hutang = parseInt(sisa_bayar2)-parseInt(jml_bayar_dp2);
		var sisa_hutang2 = sisa_hutang.toString().replaceAll(/(\d)(?=(\d\d\d)+(?!\d))/g, "$1.");
			document.getElementById("sisa_hutang").value=sisa_hutang2;
			
			document.getElementById("total_bayar").value='0';
	}
	
	function lunasin2(){
		var telah_dibayar = document.getElementById("telah_dibayar").value;
		var telah_dibayar2 = telah_dibayar.replaceAll(".", "");
		
		var sisa_bayar = document.getElementById("sisa_bayar").value;
		var sisa_bayar2 = sisa_bayar.replaceAll(".", "");
			document.getElementById("jml_bayar_dp").value=sisa_bayar;
		var jml_bayar_dp = document.getElementById("jml_bayar_dp").value;
		var jml_bayar_dp2 = jml_bayar_dp.replaceAll(".", "");
		
		var sisa_hutang = parseInt(sisa_bayar2)-parseInt(jml_bayar_dp2);
		var sisa_hutang2 = sisa_hutang.toString().replaceAll(/(\d)(?=(\d\d\d)+(?!\d))/g, "$1.");
			document.getElementById("sisa_hutang").value=sisa_hutang2;
			
		var jumlah_total_bayar = parseInt(telah_dibayar2)+parseInt(jml_bayar_dp2);
		var jumlah_total_bayar2 = jumlah_total_bayar.toString().replaceAll(/(\d)(?=(\d\d\d)+(?!\d))/g, "$1.");
			document.getElementById("total_bayar").value=jumlah_total_bayar2;
	}
	
	  function metodebayar(nilai){
    var nilai = nilai.value;
    if(nilai == 'Transfer'){
      $("#transfer").show();
      $("#transfer2").show();
      $("#no_rek").show();
      $("#cash").hide();
       $("#cash").val("");
    } else {
      $("#transfer").show();
      $("#transfer2").show();
      $("#no_rek").hide();
      $("#cash").show();
       $("#no_rek").val("");
    }
    
    }
	
	function PostData2(){
		//alert('Testing2');
        $("#frm_postdata").ajaxSubmit(post_data2);
    }
	
	var post_data2 = {
		target:'',
		beforeSubmit: function() {	
			}, 
		success:function(){	
			swal({
				    title: 'Order Sukses !',
				    text: 'Auto Close...',
				    icon: 'success',
				    timer: 4000,
				    showConfirmButton: false,
				})
			location.href="#";		
			location.reload(true)
		},
		url: '<?php echo $this->baseUrl();?>/pembayaransupplier/kirimdataedithistory',
		type: 'post',
		resetForm: false
	};
	
</script>