<form id="frm_postdata" name="frm_postdata" enctype="multipart/form-data" method="POST">
	<input type="hidden" name="currentPage" id="currentPage" size="6" maxlength="6" value="<?php echo $this->numPage;?>" class="inputbox2 narrowkey1"></input>
		<?php 
			$seq = $this->seq;
			//var_dump($seq);
			$seq += 1;
			$seq2=str_pad($seq, 2, '0', STR_PAD_LEFT);
		?>
		<input type="hidden" id='seq' name='seq' value ='<?php echo $seq;?>'>
		<input type="hidden" id='action' name='action' value =''>
			<input type="hidden" id='id' name='id' value="<?php echo $this->data[0]['id'];?>">
		<div class="panel">
            <fieldset class="panel-dt">	
				<h4 align="left"><u>Edit Sumber Dana</u></h4>
				<br>
					<div class="col-sm-12">
						<table width="100%">
							<!-- baris judul -->
							<tr>
								<td width="10%"><font style="font-size:12px;font-weight:bold;">Sumber Dana</font></td>
								<td> &nbsp;</td>
								<td width="14%"><font style="font-size:12px;font-weight:bold;">Saldo Awal</font></td>
								<td> &nbsp;</td>
								<td width="14%"><font style="font-size:12px;font-weight:bold;">Nomor Rekening</font></td>
								<td> &nbsp;</td>
								<td width="18%"><font style="font-size:12px;font-weight:bold;">Kode Cabang</font></td>
								<td> &nbsp;</td>
								<td width="14%"><font style="font-size:12px;font-weight:bold;">Nama Cabang Pembuka</font></td>
								<td> &nbsp;</td>
								
							</tr> 
						<!-- 	Baris input -->

							<tr>

								<td width="14%"> 	
											<input name="nama_akun" id="nama_akun" type="text" maxlength="50" size="20" class="form-control" value="<?php echo $this->data[0]['nama_akun'];?>"> 
											<span class="input-group-btn add-on">
											
											</span>
										
								</td>

								<td >&nbsp;</td>

							
								<td width="16%"> 
									<input name="saldo_awal" id="saldo_awal" type="text" maxlength="30" size="30" class="form-control input-sm" placeholder="0"  onkeyup='masking("saldo_awal")' value="<?php echo number_format($this->data[0]['saldo_awal'],0,",",".") ?>"> 

								</td>

								<td> &nbsp;</td>
								<td width="20%">
									<input name="no_akun" id="no_akun" type="text" maxlength="30" size="30" class="form-control input-sm"  value="<?php echo $this->data[0]['no_akun'];?>"> 
								</td>

								<td> &nbsp;</td>
								<td width="16%">
									<input name="kode_cabang" id="kode_cabang" type="text" maxlength="30" size="30" class="form-control input-sm" value="<?php echo $this->data[0]['kode_cabang'];?>"> 

								</td>

								<td> &nbsp;</td>
								<td width="16%">
									<input name="nama_cabang_pembuka" id="nama_cabang_pembuka" type="text" maxlength="30" size="30" class="form-control input-sm" value="<?php echo $this->data[0]['nama_cabang_pembuka'];?>"> 
									
						<!-- 		</td>
									<td> &nbsp;</td>
									<td width="16%">
									<label for="transfer">
									 	<input required=""  name="type" type="radio" id="transfer" name="transfer" value="Transfer">

										Transfer
									</label>
									
									<label for="Cash">
										<input required="" name="type"  type="radio" id="cash" name="cash" value="Cash">
										Cash
									</label>
									
								</td> -->
								<td width="16%">
									<label for="cashin">
									 	<input required=""  name="type" type="radio" id="cashin" name="transfer" value="Transfer" <?php if ($this->data[0]['type']=="Transfer"){?> checked <?php }?>>

											Transfer
									</label>
									
									<label for="Cash In">
										<input required="" name="type"  type="radio" id="cashout" name="cash" value="Cash" <?php if ($this->data[0]['type']=="Cash"){?> checked <?php }?>>
										Cash
									</label>
									
								</td>
							</tr> 
								<!-- validasi error -->
							<tr>
								<td width="10%">&nbsp; <label id="nama_akun-error" for="nama_akun" class="error"></font></td>
								<td> &nbsp;</td>
								<td width="14%">&nbsp; <label id="saldo_awal-error" for="saldo_awal" class="error"></font></td>
								<td> &nbsp;</td>
								<td width="14%">&nbsp; <label id="no_akun-error" for="no_akun" class="error"></td>
								<td> &nbsp;</td>
								<td width="18%">&nbsp; <label id="kode_cabang-error" for="kode_cabang" class="error"></td>
								<td> &nbsp;</td>
								<td width="14%">&nbsp; <label id="nama_cabang_pembuka-error" for="nama_cabang_pembuka" class="error"></td>
								<td> &nbsp;</td>
								
							</tr> 

							
						</table>
					</div>
				<div class="col-lg-12">
					<div class="form-group form-group-bottom" align="right">
						<input type="hidden" id="proses" name="proses" value="<?php echo $this->proses?>">	
						<br><br>
							
							<button onclick="back();" type="button" class="btn btn-theme02">
								<span class="fa fa-backward"></span> &nbsp;Kembali
							</button>
							<button type="button" class="btn btn-theme03" onCLick="PostData()">
								<span class="fa fa-save"></span> &nbsp;Simpan
							</button>
					</div>
				</div>
			</fieldset>
		</div>
	</form>			
			