<?php

use \PhpOffice\PhpSpreadsheet\Spreadsheet;
use \PhpOffice\PhpSpreadsheet\Writer\Xlsx;

$spreadsheet = new Spreadsheet();
$sheet = $spreadsheet->getActiveSheet();
$sheet->setCellValue('A1', 'Customer');
$sheet->setCellValue('B1', 'Total');

$index = 0;
$total = 0;
$rowNum = 2;

foreach ($this->totalSales as $sale) {

  $sheet->setCellValue('A' . $rowNum, $sale['nama_customer']);
  $sheet->setCellValue('B' . $rowNum, $sale['total']);

  $spreadsheet->getActiveSheet()->getStyle('B' . $rowNum)->getNumberFormat()
    ->setFormatCode('#,##0.00');

  $total += $sale['total'];

  $rowNum++;
  $index++;
}

$sheet->setCellValue('A' . $rowNum, 'Total');
$sheet->setCellValue('B' . $rowNum, $total);

$spreadsheet->getActiveSheet()->getStyle('B' . $rowNum)->getNumberFormat()
    ->setFormatCode('#,##0.00');

$styleArray = array(
  'borders' => array(
    'top' => array(
      'borderStyle' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THIN,
    ),
    'bottom' => array(
      'borderStyle' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THIN,
    ),
    'right' => array(
      'borderStyle' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THIN,
    ),
    'left' => array(
      'borderStyle' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THIN,
    ),

  ),
);

$borderRange = "A1:B" . ($rowNum);

$sheet = $sheet->getStyle($borderRange)->applyFromArray($styleArray);

$writer = new Xlsx($spreadsheet);
header('Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
header('Content-Disposition: attachment; filename="salesbycustomersummary.xlsx"');
$writer->save("php://output");
