<?php
$mpdf = new \Mpdf\Mpdf([
  'margin_left' => 2,
  'margin_top' => 2,
  'margin_right' => 2,
  'margin_bottom' => 2,
]);
ob_start();
?>
<!DOCTYPE html>
<html>

<head>
  <title>Vapehitz - Print</title>
  <style>
    table {
      border-collapse: collapse;
      width: 100%;
      font-size: 10px;
    }

    td {
      border: 1px solid #000;
      padding: 2px;
    }
  </style>
</head>

<body>
  <div align="center">
    <h2 align="center">Sales By Customer Summary</h2>
    <table>
      <thead style="background-color: #4ECDC4; color: #fff;">
        <tr>
  
          <td>Customer</td>
          <td>Total</td>
        </tr>
      </thead>
      <tbody>
        <?php $no = 1; ?>
        <?php $total = 0; ?>
        <?php foreach ($this->totalSales as $sale) : ?>
          <tr>

            <td><?= $sale['nama_customer'] ?></td>
            <td style="text-align: right;"><?= number_format($sale['total'], 0, ',', '.') ?></td>
          </tr>
          <?php $no++; ?>
          <?php $total += $sale['total']; ?>
        <?php endforeach; ?>
      </tbody>
      <tfoot>
          <tr>
            <td>Total</td>
            <td style="text-align: right;"><?= number_format($total, 0, ',', '.') ?></td>
          </tr>
      </tfoot>
    </table>
  </div>
</body>

</html>
<?php
$html = ob_get_contents();
ob_end_clean();
$mpdf->WriteHTML(utf8_encode($html));
$mpdf->Output();
?>