<script>
	$(document).ready(function () {
		$('#dataTables-emp').dataTable({
			"bPaginate": true,
			"bLengthChange": true,
			"bFilter": true,
			"bInfo": true,
			"bAutoWidth": true});
	});
	 
	function pilihEmp(kode_barang,nama_barang,ket,stok_pusat,stok_retail,on_hand){
		  
		  var count_table_tbody_tr = document.getElementById("counterx").value;
		  
		  var table = document.getElementById("myTable");	  
		  var row = table.insertRow(-1);
		  var cell1 = row.insertCell(0);
		  var cell2 = row.insertCell(1);
		  var cell3 = row.insertCell(2);
		  var cell4 = row.insertCell(3);
		  var cell5 = row.insertCell(4);
		  var cell6 = row.insertCell(5);
		  var cell7 = row.insertCell(6);
		  var cell8 = row.insertCell(7);
		  
		  var rows = parseInt(count_table_tbody_tr) + 1;
		  
		  document.getElementById("counterx").value=rows;
		  
		  cell1.innerHTML = "<input type='text' class='form-control input-sm' name='kode_barang[]' value='"+kode_barang+"' readonly/> <input type='hidden' name='nama_tabel[]' value='atomizer' readonly/>";
		  cell2.innerHTML = "<input type='text' class='form-control input-sm' name='nama_barang[]' value='"+nama_barang+"' readonly/> <input type='hidden' name='kode[]' value='kode_atomizer' readonly/>";
		  cell3.innerHTML = "<input type='text' class='form-control input-sm' id='ket"+rows+"' name='ket[]' value='"+ket+"' readonly/>";
		  cell4.innerHTML = "<input type='text' class='form-control input-sm' id='on_hand"+rows+"' name='on_hand[]' value='"+on_hand+"' readonly/><input type='hidden' id='on_hand_awal"+rows+"' name='on_hand_awal[]' value='"+on_hand+"' readonly/>";
		  cell5.innerHTML = "<input type='text' class='form-control input-sm' id='stok_gudang"+rows+"' name='stok_gudang[]' value='"+stok_pusat+"' readonly/>";
		  cell6.innerHTML = "<input type='text' class='form-control input-sm' id='stok_retail"+rows+"' name='stok_retail[]' value='"+stok_retail+"' readonly/>";
		  cell7.innerHTML = "<input type='text' class='form-control input-sm' id='qty"+rows+"' name='qty[]' value='0' onkeyup='hitung("+rows+")' /><input type='hidden' id='qty_awal"+rows+"' name='qty_awal[]' value='0' readonly/>";
		  cell8.innerHTML = "<input type='button' id='delete' class='btn btn-danger btn-sm mar-ed-button' name='delete' onclick='deleterow(this,"+rows+")' value='Hapus'/>";
		
		closeDetil();
	} 
</script>

<form action="" method="post" name="emplist" id="emplist">
	<div id="popupContact" style="width:75%; min-height:600px">
		<table width="100%">
			<tr>
				<td>
					<button class="btn btn-danger btn-circle right" type="button" onclick="closeDetil()"><i class="glyphicon glyphicon-remove"></i></button>
				</td>
			</tr>
		</table>
	<center>
	<div id="popupContactx">	
	<div class="panel panel-info" style="margin-right: 25px;margin-left: 25px;">
		<div class="panel-heading"><h3 class="title title-custom">List Data Atomizer</h3></div>	
		<div class="panel-body">
			<div class="col-lg-3 col-md-3 col-sm-12">	
				<select class = "form-control input-sm" width="15%" onclick="pilih_barang(this)">
					<option value="0">--Pilih Barang--</option>
					<option value="Liquid">Isi Ulang (Liquid)</option>
					<option value="Device">Perlengkapan (Device)</option>
					<option value="Aksesoris">Aksesoris</option>
					<option value="Atomizer">Atomizer</option>
				</select>
			</div>
			<div class="col-lg-12 col-md-12 col-sm-12">
			<br>
			<form action="" method="post" name="insdata" id="insdata">
				<div class="table-responsive">
					<div style="overflow:auto;height:440px;">
					<table style="font-size:12px;" class="table table-striped table-bordered table-hover" id="dataTables-emp" width="200%">
						<thead>
						<tr bgcolor="#4ECDC4">		
							<th width="20%">Kode Atomizer</th>
							<th width="35%">Nama Atomizer</th>
							<th width="5%">Warna</th>
							<th width="5%">On Hand</th>
							<th width="5%">Stok Pusat</th>
							<th width="5%">Stok Retail</th>
							<th width="5%">Stok Studio</th>
							<th width="5%">Berat (gr)</th>
							<th width="15%">Harga Jual Retail</th>
						</tr>
						</thead>
						<tbody>
						<?php
								  for($x=0; $x<count($this->data); $x++){
									  
										$kode_atomizer 	= $this->data[$x]['kode_atomizer'];
										$merk_atomizer 	= $this->data[$x]['merk_atomizer'];
										$nama_atomizer 	= $this->data[$x]['nama_atomizer'];
										$jenis_atomizer	= $this->data[$x]['jenis_atomizer'];
										$ket 			= $this->data[$x]['ket'];
										//$nama_warna 	= $this->data[$x]['nama_warna'];
										$on_hand 		= $this->data[$x]['on_hand'];
										$stok_pusat 	= number_format($this->data[$x]['stok_pusat'],0,",",".");
										$stok_retail 	= number_format($this->data[$x]['stok_retail'],0,",",".");
										$stok_studio 	= number_format($this->data[$x]['stok_studio'],0,",",".");
										$bad_stock	 	= number_format($this->data[$x]['bad_stock'],0,",",".");
										$berat		 	= number_format($this->data[$x]['berat'],0,",",".");
										$harga_beli	 	= number_format($this->data[$x]['harga_beli'],0,",",".");
										$harga_beli2	= $this->data[$x]['harga_beli'];
										$hj_agen	 	= number_format($this->data[$x]['hj_agen'],0,",",".");
										$hj_retail	 	= number_format($this->data[$x]['hj_retail'],0,",",".");
										$hj_retail2		= $this->data[$x]['hj_retail'];
										$hj_whs		 	= number_format($this->data[$x]['hj_whs'],0,",",".");
										$kode_supplier 	= $this->data[$x]['kode_supplier'];
										
										$kode_warna 	= $this->data[$x]['kode_warna'];
										$warna = $this->Reqretailtocentral_Service->getwarna2($kode_warna);
									?>	
										<tr>
											<td align="left"><a href="#" onclick="javascript:pilihEmp('<?php echo $kode_atomizer; ?>','<?php echo $nama_atomizer; ?>','<?php echo $ket; ?>','<?php echo $stok_pusat; ?>','<?php echo $stok_retail; ?>','<?php echo $on_hand; ?>')"><?php echo $kode_atomizer;?></a></td>
											<td align="left"><?php echo $nama_atomizer;?></td>
											<td align="left"><?php echo $warna;?></td>
											<td align="left"><?php echo $on_hand;?></td>
											<td align="left"><?php echo $stok_pusat;?></td>
											<td align="left"><?php echo $stok_retail;?></td>
											<td align="left"><?php echo $stok_studio;?></td>
											<td align="left"><?php echo $berat;?></td>
											<td align="left"><?php echo $hj_retail;?></td>
										</tr>	
									<?php 
										}
									?>
						</tbody>
					</table>
					</div>
				</div>
			</form>
			</div>			
			<div id='popuptarget'></div>
		</div>
	</div>		
</div>
</center>
</div>
<div id='myDIVx'></div>
<div id="backgroundPopup"></div>
</form>
