<form id="frm_postdata" name="frm_postdata" enctype="multipart/form-data" method="POST">
	<input type="hidden" name="currentPage" id="currentPage" size="6" maxlength="6" value="<?php echo $this->numPage;?>" class="inputbox2 narrowkey1"></input>
		<input type="hidden" id='action' name='action' value =''>
		<input type="hidden" id='no_id' name='no_id' value ='<?php echo $this->data[0]['no_id'];?>'>
		<div class="panel">
            <fieldset class="panel-dt">	
				<h4 align="left"><u>Edit Data</u></h4>
				<br>
					<div class="col-sm-12">
						<table width="100%">
							<tr>
								<td width="10%"><font style="font-size:12px;font-weight:bold;">Nama Bank</font></td>
								<td width="1%">:</td>
								<td>
									<table>
										<td> <input name="nama_bank" id="nama_bank" type="text" maxlength="30" size="40" class="form-control input-sm" value="<?php echo $this->data[0]['nama_bank'];?>"> </td>
										<td> &nbsp; <label id="nama_bank-error" for="nama_bank" class="error"></td>
									</table>
								</td>
							</tr>
							<tr><td>&nbsp;</td></tr>
							<tr>
								<td width="10%"><font style="font-size:12px;font-weight:bold;">Nama Pemilik Rekening</font></td>
								<td width="1%">:</td>
								<td>
									<table>
										<td> <input name="atas_nama" id="atas_nama" type="text" maxlength="40" size="40" class="form-control input-sm" value="<?php echo $this->data[0]['atas_nama'];?>"> </td>
										<td> &nbsp; <label id="atas_nama-error" for="atas_nama" class="error"></td>
									</table>
								</td>
							</tr>
							<tr><td>&nbsp;</td></tr>
							<tr>
								<td width="10%"><font style="font-size:12px;font-weight:bold;">No Rekening</font></td>
								<td width="1%">:</td>
								<td>
									<table>
										<td> <input name="no_rekening" id="no_rekening" type="text" maxlength="50" size="40" class="form-control input-sm" value="<?php echo $this->data[0]['no_rekening'];?>"> </td>
										<td> &nbsp; <label id="no_rekening-error" for="no_rekening" class="error"></td>
									</table>
								</td>
							</tr>
							<tr><td>&nbsp;</td></tr>
							<tr>
								<td width="10%"><font style="font-size:12px;font-weight:bold;">Status</font></td>
								<td width="1%">:</td>
								<td>
									<table>
										<td> 
										<?php 
											$status = $this->data[0]['status'];
											$selected = 'selected';
										?>
											<select id="status" name="status" class = "form-control input-sm" width="15%">
												<option value="">--Pilih Status--</option>
												<option value="1" <?php if($status == '1'){ echo $selected; } ?>>Active</option>
												<option value="0" <?php if($status == '0'){ echo $selected; } ?>>Inactive</option>
											</select>
										</td>
										<td> &nbsp; <label id="status-error" for="status" class="error"></td>
									</table>
								</td>
							</tr>
							<tr><td>&nbsp;</td></tr>
						</table>
					</div>
				<div class="col-lg-12">
					<div class="form-group form-group-bottom" align="right">
						<input type="hidden" id="proses" name="proses" value="<?php echo $this->proses?>">	
						<br><br>
							<a href="rekening">
							<button type="button" class="btn btn-theme02">
								<span class="fa fa-backward"></span> &nbsp;Kembali
							</button></a>
							<button type="button" class="btn btn-theme03" onCLick="PostData()">
								<span class="fa fa-save"></span> &nbsp;Simpan
							</button>
					</div>
				</div>
			</fieldset>
		</div>
	</form>