<style>
#backgroundPopup{  

display:none;  
position:fixed;  
_position:absolute; /* hack for internet explorer 6*/  
height:100%;  
width:100%;  
top:0;  
left:0; 
/*background: rgba(0, 0, 0, 0) url("../img/popup-bg.png");*/
background:rgba(0,0,0,0.85);  
border:1px solid #cecece;  
z-index:1040;  


}  
 
 
.box-popup1{
	position:fixed;
	top:30px;
	left:30px;
	width:40px;
	height:30px;
}
 

#popupContact{  

display:none;  
position:fixed;  
_position:absolute; /* hack for internet explorer 6*/  
height:100%; 
width:90%;  
background:#acacac;  
z-index:999999;  
font-size:13px;  
overflow:auto;
top:2px;
bottom:10px;
padding:15px;
margin: 1%;
}  




#popupContact h1{  
text-align:left;  
color:#6FA5FD;  
font-size:22px;  
font-weight:bold;  
border-bottom:1px dotted #D3D3D3;  
padding-bottom:2px;  
margin-bottom:20px;  
}  
#popupContact textarea{width:90%;height:100px;}
#popupContactClose{  
font-size:14px;  
line-height:14px;  
right:6px;  
top:4px;  
position:absolute;  
color:#6fa5fd;  
font-weight:bold;  
width:16px;
cursor:pointer;
display:block;  
background:url(../images/cross.png)
} 
</style>
<form id="frm_postdata" name="frm_postdata" enctype="multipart/form-data" method="POST">
	<input type="hidden" name="currentPage" id="currentPage" size="6" maxlength="6" value="<?php echo $this->numPage;?>" class="inputbox2 narrowkey1"></input>
		<?php 
			$seq = $this->seq;
			//var_dump($seq);
			$seq += 1;
			$seq=str_pad($seq, 5, '0', STR_PAD_LEFT);
		?>
		<input type="hidden" id='seq' name='seq' value ='<?php echo $seq;?>'>
		<div id="popupview"></div>
		<div class="panel">
            <fieldset class="panel-dt">							
				<h4><i class="fa fa-angle-right"></i> Tambah Pembelian Barang</h4>
						<br>
					<div class="col-sm-12">
						<table width="100%">
							<tr>
								<td width="10%"><font style="font-size:12px;font-weight:bold;">Nomor Order</font></td>
								<td width="1%">:</td>
								<td>
									<table>
										<td> <input name="no_order" id="no_order" type="text" maxlength="50" size="20" class="form-control input-sm" value="PO/VH/<?php echo date("dmY");?>/<?php echo $seq;?>" readonly> </td>
										<td> &nbsp; <label id="no_order-error" for="no_order" class="error"></td>
									</table>
								</td>
							</tr> 
							<tr><td>&nbsp;</td></tr>
							<tr>
								<td width="10%"><font style="font-size:12px;font-weight:bold;">Tanggal Order</font></td>
								<td width="1%">:</td>
								<td>
									<table>
										<td> 
											<input name="tgl_order" id="tgl_order" type="date" maxlength="50" size="20" class="form-control" value=""> 
											<span class="input-group-btn add-on">
												<button class="btn btn-theme" type="button"><i class="fa fa-calendar"></i></button>
											</span>
										</td>
										<td> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <label id="tgl_order-error" for="tgl_order" class="error"></td>
									</table>
								</td>
							</tr> 
							<tr><td>&nbsp;</td></tr>
							<tr>
								<td width="10%"><font style="font-size:12px;font-weight:bold;">Nama Supplier</font></td>
								<td width="1%">:</td>
								<td>
									<table>
										<td>
											<select id="kode_supplier" name="kode_supplier" class="form-control select_group product" width="20%" onchange="getSelectValue();">
												<option value="0">--Pilih Supplier--</option>
												<?php  
													for($x=0; $x<count($this->supplier); $x++){ 
													$kode_supplier = $this->supplier[$x]['kode_supplier'];
													$nama_supplier = $this->supplier[$x]['nama_supplier'];
													$alamat_supplier = $this->supplier[$x]['alamat_supplier'];
													$tipe = $this->supplier[$x]['tipe'];
													$no_tlp = $this->supplier[$x]['no_tlp'];
													$no_hp = $this->supplier[$x]['no_hp'];
													$email = $this->supplier[$x]['email'];
												?>
												<option value="<?php echo $kode_supplier;?>,<?php echo $alamat_supplier;?>,<?php echo $tipe;?>,<?php echo $no_tlp;?>,<?php echo $no_hp;?>,<?php echo $email;?>"><?php echo $nama_supplier;?></option>
												<?php } ?>
											</select>
										</td>
										<td> &nbsp; <label id="kode_supplier-error" for="kode_supplier" class="error"></td>
									</table>
								</td>
							</tr>
							<tr><td>&nbsp;</td></tr>
							<tr>
								<td width="10%"><font style="font-size:12px;font-weight:bold;">Kode Supplier</font></td>
								<td width="1%">:</td>
								<td>
									<table>
										<td> <input name="kode_supplier2" id="kode_supplier2" type="text" maxlength="10" size="10" class="form-control input-sm" value="" readonly> </td>
										<td> </td>
									</table>
								</td>
							</tr> 
							<tr><td>&nbsp;</td></tr>
							<tr>
								<td width="10%"><font style="font-size:12px;font-weight:bold;">Alamat Supplier</font></td>
								<td width="1%">:</td>
								<td>
									<table>
										<td> <input name="alamat_supplier" id="alamat_supplier" type="text" maxlength="100" size="100" class="form-control input-sm" value="" readonly> </td>
										<td> </td>
									</table>
								</td>
							</tr> 
							<tr><td>&nbsp;</td></tr>
							<tr>
								<td width="10%"><font style="font-size:12px;font-weight:bold;">Status Barang Supplier</font></td>
								<td width="1%">:</td>
								<td>
									<table>
										<td> <input name="tipe" id="tipe" type="text" maxlength="20" size="15" class="form-control input-sm" value="" readonly> </td>
										<td> </td>
									</table>
								</td>
							</tr> 
							<tr><td>&nbsp;</td></tr>
							<tr>
								<td width="10%"><font style="font-size:12px;font-weight:bold;">Nomor Telepon</font></td>
								<td width="1%">:</td>
								<td>
									<table>
										<td> <input name="no_tlp" id="no_tlp" type="text" maxlength="20" size="15" class="form-control input-sm" value="" readonly> </td>
										<td> </td>
									</table>
								</td>
							</tr> 
							<tr><td>&nbsp;</td></tr>
							<tr>
								<td width="10%"><font style="font-size:12px;font-weight:bold;">Nomor Handphone / WA</font></td>
								<td width="1%">:</td>
								<td>
									<table>
										<td> <input name="no_hp" id="no_hp" type="text" maxlength="20" size="15" class="form-control input-sm" value="" readonly> </td>
										<td> </td>
									</table>
								</td>
							</tr> 
							<tr><td>&nbsp;</td></tr>
							<tr>
								<td width="10%"><font style="font-size:12px;font-weight:bold;">Email</font></td>
								<td width="1%">:</td>
								<td>
									<table>
										<td> <input name="email" id="email" type="text" maxlength="25" size="25" class="form-control input-sm" value="" readonly> </td>
										<td> </td>
									</table>
								</td>
							</tr> 
							<tr><td>&nbsp;</td></tr>
						</table>
						<hr>
						<div align='left'>
							<input type="button" class="right btn btn-success  btn-xs" style="font-weight:bold;" value="Tambah Barang" onclick="dataliquid()">
							<input type='hidden' name='counterx' id='counterx' value="0">
						</div>
						<br>
						<table width="100%" id="myTable">
							<tr>
								<td> <font style="font-size:12px;font-weight:bold;">Kode Barang</font></td>
								<td> <font style="font-size:12px;font-weight:bold;">Nama Barang</font></td>
								<td> <font style="font-size:12px;font-weight:bold;">Keterangan</font></td>
								<td> <font style="font-size:12px;font-weight:bold;">Stok  Gudang</font></td>
								<td> <font style="font-size:12px;font-weight:bold;">Harga Beli</font></td>
								<td> <font style="font-size:12px;font-weight:bold;">QTY</font></td>
								<td> <font style="font-size:12px;font-weight:bold;">Sub Total</font></td>
								<td> <font style="font-size:12px;font-weight:bold;"></font></td>
							</tr>
						</table>
						<table width="100%" id="myTable2">
						<tr><td>&nbsp;</td></tr>
							<tr>
								<td colspan='5' width="68%">&nbsp; <label id="total-error" for="total" class="error"></td>
								<td width="13%"></><font style="font-size:12px;font-weight:bold;">Total</font></td>
								<td width="19%"></> <input type='text' class="form-control input-sm" name='total' id='total' value='0' readonly> </td>
							</tr>
							<tr><td>&nbsp;</td></tr>
							<tr>
								<td colspan='5' align="right">&nbsp;</td>
								<td><font style="font-size:12px;font-weight:bold;">Biaya Kirim</font></td>
								<td> <input type='text' class="form-control input-sm" name='biaya_kirim' id='biaya_kirim' value='0' onkeyup='biaya()'> </td>
							</tr>
							<tr><td colspan='7' align="right"><label id="biaya_kirim-error" for="biaya_kirim" class="error"></td></tr>
							<tr>
								<td colspan='5'></td>
								<td><font style="font-size:12px;font-weight:bold;">Diskon</font></td>
								<td> <input type='text' class="form-control input-sm" name='diskon' id='diskon' value='0' onkeyup='datadiskon()'> </td>
							</tr>
							<tr><td colspan='7' align="right"><label id="diskon-error" for="diskon" class="error"></td></tr>
							<tr>
								<td colspan='5'></td>
								<td><font style="font-size:12px;font-weight:bold;">Net Total</font></td>
								<td> <input type='text' class="form-control input-sm" name='net_total' id='net_total' value='0' readonly> </td>
							</tr>
							<tr><td>&nbsp;</td></tr>
							<tr>
								<td colspan='5'></td>
								<td><font style="font-size:12px;font-weight:bold;">Jumlah Bayar/DP</font></td>
								<td> <input type='text' class="form-control input-sm" name='jml_bayar_dp' id='jml_bayar_dp' value='0' onkeyup='jumlahdp()'> </td>
							</tr>
							<tr><td colspan='7' align="right"><label id="jml_bayar_dp-error" for="jml_bayar_dp" class="error"></td></tr>
							<tr>
								<td colspan='6'></td>
								<td> 
									<input type="radio" id="metode_bayar_a" name="metode_bayar" value="Hutang" onclick='lunasin()' checked>
									<label for="vehicle1"> Hutang</label> &nbsp;&nbsp;&nbsp;
									<input type="radio" id="metode_bayar_b" name="metode_bayar" value="Lunas" onclick='lunasin2()'>
									<label for="vehicle2"> Lunas</label>
								</td>
							</tr>
							<tr><td>&nbsp;</td></tr>
							<tr>
								<td colspan='5'></td>
								<td><font style="font-size:12px;font-weight:bold;">Sisa Pembayaran</font></td>
								<td> <input type='text' class="form-control input-sm" name='sisa_bayar' id='sisa_bayar' value='0' readonly> </td>
							</tr>
							<tr><td>&nbsp;</td></tr>
							<tr>
								<td colspan='5'></td>
								<td><font style="font-size:12px;font-weight:bold;">Cara Pembayaran</font></td>
								<td> 
									<select id="metode_bayar2" name="metode_bayar2" class = "form-control input-sm" width="15%" onclick="metodebayar(this)">
										<option value="0">--Pilih Cara Pembayaran--</option>
										<option value="Transfer">Transfer</option>
										<option value="Cash">Cash</option>
									</select>
								</td>
							</tr>
							<tr><td colspan='7' align="right"><label id="metode_bayar2-error" for="metode_bayar2" class="error"></td></tr>
							<tr id='transfer'>
								<td colspan='5'></td>
								<td width="10%"><font style="font-size:12px;font-weight:bold;">Bank Transfer</font></td>
								<td>										
									<select id="no_rek" name="no_rek" class = "form-control input-sm" width="15%">
										<option value="0">--Pilih Bank--</option>
										<?php  
											for($x=0; $x<count($this->rek); $x++){ 
											$cek_rek = $this->rek[$x]['nama_bank'].' - '.$this->rek[$x]['no_rekening'] .' ('.$this->rek[$x]['atas_nama'].')';
										?>
										<option value="<?php echo $cek_rek;?>"><?php echo $cek_rek;?></option>
										<?php } ?>
									</select>
								</td>
							</tr>
							<tr id='transfer2'><td colspan='7' align="right"><label id="no_rek-error" for="no_rek" class="error"></td></tr>
						</table>
					</div>				
			</fieldset>
		</div>
		
	</div>
</div>
<div class="col-lg-12">
<div class="form-group form-group-bottom" align="right">
						<input type="hidden" id="proses" name="proses" value="<?php echo $this->proses?>">	
						<br><br>
							
							<a href="atomizer">
							<button type="button" class="btn btn-theme02">
								<span class="fa fa-backward"></span> &nbsp;Kembali
							</button></a>
							<button type="button" class="btn btn-theme03" onCLick="PostData()">
								<span class="fa fa-save"></span> &nbsp;Simpan
							</button>
							
			</div>
</div>
</form>
  
  <script src="<?php echo $this->baseUrl();?>/lib/jquery/jquery.min.js"></script>
  <script src="<?php echo $this->baseUrl();?>/lib/bootstrap/js/bootstrap.min.js"></script>
  <script src="<?php echo $this->baseUrl();?>/lib/jquery.form.js"></script>
  <link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl();?>/css/sweetalert.css">
  <script src="<?php echo $this->baseUrl();?>/lib/sweetalert.min.js"></script>
<script>
	$("#transfer").hide();
	$("#transfer2").hide();
	function loadPopup() {
		var popupStatus = 0;
		if (popupStatus == 0) {
			jQuery("#backgroundPopup").css({"opacity": "1"});
			jQuery("#backgroundPopup").fadeIn("fast");
			jQuery("#popupContact").fadeIn("fast");
			popupStatus = 1
		}
	}

	function centerPopup() {
		var windowWidth = document.documentElement.clientWidth;
		var windowHeight = "1000%";
		var popupHeight = jQuery("#popupContact").height();
		var popupWidth = jQuery("#popupContact").width();
	}

	function closePopup() {
		document.getElementById('popupContact').style.display = "none";
		document.getElementById('backgroundPopup').style.display = "none";
	}

	function disablePopup() {
		document.getElementById('popupContact').style.display = "none";
		document.getElementById('backgroundPopup').style.display = "none";
	}
		
	function dataliquid(){
		var seq = document.getElementById('seq').value;
		
		//alert('maintain'); 
		
		var url = '<?php echo $this->basePath; ?>/ordercentral/dataliquid';
		var opt = {seq:seq};
		
		jQuery.get(url,opt, function(data) {			
			jQuery("#popupview").html(data);
			centerPopup(); 
			loadPopup();		
		})
	}
	
	function datadevice(){
		var seq = document.getElementById('seq').value;
		
		//alert('maintain'); 
		
		var url = '<?php echo $this->basePath; ?>/ordercentral/datadevice';
		var opt = {seq:seq};
		
		jQuery.get(url,opt, function(data) {			
			jQuery("#popupview").html(data);
			centerPopup(); 
			loadPopup();		
		})
	}
	
	function dataaksesoris(){
		var seq = document.getElementById('seq').value;
		
		//alert('maintain'); 
		
		var url = '<?php echo $this->basePath; ?>/ordercentral/dataaksesoris';
		var opt = {seq:seq};
		
		jQuery.get(url,opt, function(data) {			
			jQuery("#popupview").html(data);
			centerPopup(); 
			loadPopup();		
		})
	}
	
	function dataatomizer(){
		var seq = document.getElementById('seq').value;
		
		//alert('maintain'); 
		
		var url = '<?php echo $this->basePath; ?>/ordercentral/dataatomizer';
		var opt = {seq:seq};
		
		jQuery.get(url,opt, function(data) {			
			jQuery("#popupview").html(data);
			centerPopup(); 
			loadPopup();		
		})
	}
	
	function getSelectValue(){
		var selectedValue = document.getElementById("kode_supplier").value;
		var res = selectedValue.split(",");
		var kode_supplier = res[0];
		var alamat = res[1];
		var tipe = res[2];
		var no_tlp = res[3];
		var no_hp = res[4];
		var email = res[5];
		
		document.getElementById("kode_supplier2").value = kode_supplier;
		document.getElementById("alamat_supplier").value = alamat;
		document.getElementById("tipe").value = tipe;
		document.getElementById("no_tlp").value = no_tlp;
		document.getElementById("no_hp").value = no_hp;
		document.getElementById("email").value = email;
	}
                                                                                                                                     
	
	function PostData(){
		//alert('Testing2');
        $("#frm_postdata").ajaxSubmit(post_data);
    }
	
	var post_data = {
		target:'',
		beforeSubmit: function() {	
			var kode_supplier2 	  = document.getElementById("kode_supplier2").value;
			var no_order 	  	  = document.getElementById('no_order').value;
			var tgl_order 	 	  = document.getElementById('tgl_order').value;
			var seq		 	 	  = document.getElementById('seq').value;
			var total		 	  = document.getElementById('total').value;
			var biaya_kirim		  = document.getElementById('biaya_kirim').value;
			var diskon		 	  = document.getElementById('diskon').value;
			var jml_bayar_dp	  = document.getElementById('jml_bayar_dp').value;
			var metode_bayar2	  = document.getElementById('metode_bayar2').value;
			var no_rek	  		  = document.getElementById('no_rek').value;
				
				if (!tgl_order) {
					document.getElementById('tgl_order-error').innerHTML ="<span style='color: red;'>Tanggal Order Harus Diisi.</span>";
					document.getElementById('tgl_order').focus();
					exit;
				}else document.getElementById('tgl_order-error').innerHTML ='';
				
				if (!kode_supplier2) {
					document.getElementById('kode_supplier-error').innerHTML ="<span style='color: red;'>Supplier Harus Dipilih.</span>";
					document.getElementById('kode_supplier').focus();
					exit;
				}else document.getElementById('kode_supplier-error').innerHTML ='';
				
				if (total=='0') {
					document.getElementById('total-error').innerHTML ="<span style='color: red;'>Data Pembelian barang Harus Dipilih.</span>";
					document.getElementById('total').focus();
					exit;
				}else document.getElementById('total-error').innerHTML ='';
				
				if (!biaya_kirim) {
					document.getElementById('biaya_kirim-error').innerHTML ="<span style='color: red;'>Biaya Kirim Harus Diisi.</span>";
					document.getElementById('biaya_kirim').focus();
					exit;
				}else document.getElementById('biaya_kirim-error').innerHTML ='';
				
				if (!diskon) {
					document.getElementById('diskon-error').innerHTML ="<span style='color: red;'>Diskon Harus Diisi.</span>";
					document.getElementById('diskon').focus();
					exit;
				}else document.getElementById('diskon-error').innerHTML ='';
				
				if (!jml_bayar_dp) {
					document.getElementById('jml_bayar_dp-error').innerHTML ="<span style='color: red;'>Jumlah Bayar DP Harus Diisi.</span>";
					document.getElementById('jml_bayar_dp').focus();
					exit;
				}else document.getElementById('jml_bayar_dp-error').innerHTML ='';
				
				if (metode_bayar2=='0') {
					document.getElementById('metode_bayar2-error').innerHTML ="<span style='color: red;'>Metode Bayar Harus Dipilih.</span>";
					document.getElementById('metode_bayar2').focus();
					exit;
				}else document.getElementById('metode_bayar2-error').innerHTML ='';
				
				if(metode_bayar2 == 'Transfer'){
					if (no_rek=='0') {
						document.getElementById('no_rek-error').innerHTML ="<span style='color: red;'>Bank Transfer Harus Dipilih.</span>";
						document.getElementById('no_rek').focus();
						exit;
					}else document.getElementById('no_rek-error').innerHTML ='';
				}
				
			}, 
		success:function(){	
			swal({
				    title: 'Order Sukses !',
				    text: 'Auto Close...',
				    icon: 'success',
				    timer: 4000,
				    showConfirmButton: false,
				})
			location.href="#";		
			location.reload(true)
		},
		url: '<?php echo $this->baseUrl();?>/ordercentral/kirimdata',
		type: 'post',
		resetForm: false
	};
	
	function isNumber(evt) {
        var iKeyCode = (evt.which) ? evt.which : evt.keyCode
        if (iKeyCode != 46 && iKeyCode > 31 && (iKeyCode < 48 || iKeyCode > 57))
            return false;

        return true;
    } 
	
	function closeDetil(){
	document.getElementById('popupContact').style.display = "none";
	disablePopup();
	}
	
	function deleterow(button,rows){
		var x = button.parentNode.parentNode.rowIndex;
		var total = document.getElementById("total").value;
		var total2 = total.replaceAll(".", "");
		var sub_total = document.getElementById("sub_total"+rows).value;
		var sub_total2 = sub_total.replaceAll(".", "");
		
		var biaya_kirim = document.getElementById("biaya_kirim").value;
		var biaya_kirim2 = biaya_kirim.replaceAll(".", "");
		var diskon = document.getElementById("diskon").value;
		var diskon2 = diskon.replaceAll(".", "");
		var jml_bayar_dp = document.getElementById("jml_bayar_dp").value;
		var jml_bayar_dp2 = jml_bayar_dp.replaceAll(".", "");
		
		var hitung_total = parseInt(total2) - parseInt(sub_total2)
		var hitung_total2 = hitung_total.toString().replaceAll(/(\d)(?=(\d\d\d)+(?!\d))/g, "$1.");
		document.getElementById("total").value=hitung_total2;
		
		var hitung_net_total = hitung_total + parseInt(biaya_kirim2) - parseInt(diskon2);
		var hitung_net_total2 = hitung_net_total.toString().replaceAll(/(\d)(?=(\d\d\d)+(?!\d))/g, "$1.");
		document.getElementById("net_total").value=hitung_net_total2;
		
		var hitung_sisa_bayar = hitung_net_total - parseInt(jml_bayar_dp2);
		var hitung_sisa_bayar2 = hitung_sisa_bayar.toString().replaceAll(/(\d)(?=(\d\d\d)+(?!\d))/g, "$1.");
		document.getElementById("sisa_bayar").value=hitung_sisa_bayar2;
		
		document.getElementById("myTable").deleteRow(x);
		
	}
	
	function beli(button){
		var x = button;
		
		var total = document.getElementById("total").value;
		var total2 = total.replaceAll(".", "");
		var sub_total = document.getElementById("sub_total"+x).value;
		var sub_total2 = sub_total.replaceAll(".", "");
		
		var hitung_total = parseInt(total2) - parseInt(sub_total2);
		var qty = document.getElementById("qty"+x).value;
		
		var harga_beli = document.getElementById("harga_beli"+x).value;
		var harga_beli2 = harga_beli.replaceAll(".", "");
		var harga_beli3 = harga_beli2.toString().replaceAll(/(\d)(?=(\d\d\d)+(?!\d))/g, "$1.");
		document.getElementById("harga_beli"+x).value=harga_beli3;
		
		var kali = qty * harga_beli2;
		var kali2 = kali.toString().replaceAll(/(\d)(?=(\d\d\d)+(?!\d))/g, "$1.");
		
		document.getElementById("sub_total"+x).value=kali2;
		
		var kurangin = parseInt(hitung_total) + parseInt(kali);
		var kurangin2 = kurangin.toString().replaceAll(/(\d)(?=(\d\d\d)+(?!\d))/g, "$1.");
		document.getElementById("total").value=kurangin2;
		
		var biaya_kirim = document.getElementById("biaya_kirim").value;
		var biaya_kirim2 = biaya_kirim.replaceAll(".", "");
		var diskon = document.getElementById("diskon").value;
		var diskon2 = diskon.replaceAll(".", "");
		
		var net_total = parseInt(kurangin)+parseInt(biaya_kirim2)-parseInt(diskon2);
		var net_total2 = net_total.toString().replaceAll(/(\d)(?=(\d\d\d)+(?!\d))/g, "$1.");
			document.getElementById("net_total").value=net_total2;
			document.getElementById("sisa_bayar").value=net_total2;
			
		var stok_gudang = document.getElementById("stok_gudang"+x).value;
		var harga_beli_lama = document.getElementById("harga_beli_lama"+x).value;
		var jumlah1 =  parseInt(stok_gudang) *  parseInt(harga_beli_lama);
		var jumlah2 = parseInt(stok_gudang) + parseInt(qty);
		
		var jumlah3 = parseInt(jumlah1) + parseInt(kali);
		
		var jumlah4 = parseInt(jumlah3) / parseInt(jumlah2);
		
		document.getElementById("stok_gudang_baru"+x).value=jumlah2;
		document.getElementById("harga_beli_baru"+x).value=jumlah4;
	}
	
	function biaya(){
		var total = document.getElementById("total").value;
		var total2 = total.replaceAll(".", "");
		var biaya_kirim = document.getElementById("biaya_kirim").value;
		var biaya_kirim2 = biaya_kirim.replaceAll(".", "");
		var biaya_kirim3 = biaya_kirim2.toString().replaceAll(/(\d)(?=(\d\d\d)+(?!\d))/g, "$1.");
			document.getElementById("biaya_kirim").value=biaya_kirim3;
		
		var diskon = document.getElementById("diskon").value;
		var diskon2 = diskon.replaceAll(".", "");
		
		var net_total = parseInt(total2)+parseInt(biaya_kirim2)-parseInt(diskon);
		var net_total2 = net_total.toString().replaceAll(/(\d)(?=(\d\d\d)+(?!\d))/g, "$1.");
			document.getElementById("net_total").value=net_total2;
			document.getElementById("sisa_bayar").value=net_total2;
	}
	
	function datadiskon(){
		var total = document.getElementById("total").value;
		var total2 = total.replaceAll(".", "");
		var biaya_kirim = document.getElementById("biaya_kirim").value;
		var biaya_kirim2 = biaya_kirim.replaceAll(".", "");
		var diskon = document.getElementById("diskon").value;
		var diskon2 = diskon.replaceAll(".", "");
		var diskon3 = diskon2.toString().replaceAll(/(\d)(?=(\d\d\d)+(?!\d))/g, "$1.");
			document.getElementById("diskon").value=diskon3;
		
		var net_total = parseInt(total2)+parseInt(biaya_kirim2)-parseInt(diskon2);
		var net_total2 = net_total.toString().replaceAll(/(\d)(?=(\d\d\d)+(?!\d))/g, "$1.");
			document.getElementById("net_total").value=net_total2;
			document.getElementById("sisa_bayar").value=net_total2;
	}
	
	function jumlahdp(){
		var net_total = document.getElementById("net_total").value;
		var net_total2 = net_total.replaceAll(".", "");
		var jml_bayar_dp = document.getElementById("jml_bayar_dp").value;
		var jml_bayar_dp2 = jml_bayar_dp.replaceAll(".", "");
		var jml_bayar_dp3 = jml_bayar_dp2.toString().replaceAll(/(\d)(?=(\d\d\d)+(?!\d))/g, "$1.");
			document.getElementById("jml_bayar_dp").value=jml_bayar_dp3;
		
		var sisa_bayar = parseInt(net_total2)-parseInt(jml_bayar_dp2);
		var sisa_bayar2 = sisa_bayar.toString().replaceAll(/(\d)(?=(\d\d\d)+(?!\d))/g, "$1.");
			document.getElementById("sisa_bayar").value=sisa_bayar2;
	}
	
	function lunasin(){
		var net_total = document.getElementById("net_total").value;
		var net_total2 = net_total.replaceAll(".", "");
			document.getElementById("jml_bayar_dp").value='0';
		var jml_bayar_dp = document.getElementById("jml_bayar_dp").value;
		var jml_bayar_dp2 = jml_bayar_dp.replaceAll(".", "");
		
		var sisa_bayar = parseInt(net_total2)-parseInt(jml_bayar_dp2);
		var sisa_bayar2 = sisa_bayar.toString().replaceAll(/(\d)(?=(\d\d\d)+(?!\d))/g, "$1.");
			document.getElementById("sisa_bayar").value=sisa_bayar2;
	}
	
	function lunasin2(){
		var net_total = document.getElementById("net_total").value;
		var net_total2 = net_total.replaceAll(".", "");
			document.getElementById("jml_bayar_dp").value=net_total;
		var jml_bayar_dp = document.getElementById("jml_bayar_dp").value;
		var jml_bayar_dp2 = jml_bayar_dp.replaceAll(".", "");
		
		var sisa_bayar = parseInt(net_total2)-parseInt(jml_bayar_dp2);
		var sisa_bayar2 = sisa_bayar.toString().replaceAll(/(\d)(?=(\d\d\d)+(?!\d))/g, "$1.");
			document.getElementById("sisa_bayar").value=sisa_bayar2;
	}
	
	function metodebayar(nilai){
		var nilai = nilai.value;
		if(nilai == 'Transfer'){
			$("#transfer").show();
			$("#transfer2").show();
		} else {
			$("#transfer").hide();
			$("#transfer2").hide();
		}
	}
	
</script>