<script>
	$(document).ready(function () {
		$('#dataTables-liquid').dataTable({
			"bPaginate": true,
			"bLengthChange": true,
			"bFilter": true,
			"bInfo": true,
			"bAutoWidth": true});
	});
	 
	function pilihEmp(kode_barang,nama_barang,merk_barang,rasa,nic,volume,stok_pusat,bad_stock){
		  
		  var count_table_tbody_tr = document.getElementById("counterx").value;
		  
		  var table = document.getElementById("myTable");	  
		  var row = table.insertRow(-1);
		  var cell1 = row.insertCell(0);
		  var cell2 = row.insertCell(1);
		  var cell3 = row.insertCell(2);
		  var cell4 = row.insertCell(3);
		  var cell5 = row.insertCell(4);
		  var cell6 = row.insertCell(5);
		  var cell7 = row.insertCell(6);
		  var cell8 = row.insertCell(7);
		  var cell9 = row.insertCell(8);
		  var cell10 = row.insertCell(9);
		  var cell11 = row.insertCell(10);
		  
		  var rows = parseInt(count_table_tbody_tr) + 1;
		  
		  document.getElementById("counterx").value=rows;
		  
		  cell1.innerHTML = "<input type='text' class='form-control input-sm' name='kode_barang[]' value='"+kode_barang+"' readonly/>";
		  cell2.innerHTML = "<input type='text' class='form-control input-sm' name='nama_barang[]' value='"+nama_barang+"' readonly/> <input type='hidden' name='kode[]' value='kode_barang' readonly/>";
		  cell3.innerHTML = "<input type='text' class='form-control input-sm' id='rasa"+rows+"' name='rasa[]' value='"+rasa+"' readonly/> <input type='hidden' name='nama_tabel[]' value='liquid' readonly/>";
		  cell4.innerHTML = "<input type='text' class='form-control input-sm' id='nic"+rows+"' name='nic[]' value='"+nic+"' readonly/>";
		  cell5.innerHTML = "<input type='text' class='form-control input-sm' id='volume"+rows+"' name='volume[]' value='"+volume+"' readonly/>";
		  cell6.innerHTML = "<input type='text' class='form-control input-sm' id='stok_gudang"+rows+"' name='stok_gudang[]' value='"+stok_pusat+"' readonly/>";
		  cell7.innerHTML = "<input type='text' class='form-control input-sm' id='good_stock"+rows+"' name='good_stock[]' value='0' onkeyup='hitung("+rows+")'/>";
		  cell8.innerHTML = "<input type='text' class='form-control input-sm' id='bad_stock"+rows+"' name='bad_stock[]' value='0' onkeyup='hitung("+rows+")'/><input type='hidden' id='bad_stock_awal"+rows+"' name='bad_stock_awal[]' value='"+bad_stock+"' readonly/><input type='hidden' id='bad_stock_baru"+rows+"' name='bad_stock_baru[]' value='0' readonly/>";
		  cell9.innerHTML = "<input type='text' class='form-control input-sm' id='selisih"+rows+"' name='selisih[]' value='0' readonly/>";
		  cell10.innerHTML = "<input type='text' class='form-control input-sm' id='ket"+rows+"' name='ket[]' value=''/>";
		  cell11.innerHTML = "<input type='button' id='delete' class='btn btn-danger btn-sm mar-ed-button' name='delete' onclick='deleterow(this,"+rows+")' value='Hapus'/>";
		
		closeDetil();
	} 
</script>

<form action="" method="post" name="emplist" id="emplist">
	<div id="popupContact" style="width:75%; min-height:600px">
		<table width="100%">
			<tr>
				<td>
					<button class="btn btn-danger btn-circle right" type="button" onclick="closeDetil()"><i class="glyphicon glyphicon-remove"></i></button>
				</td>
			</tr>
		</table>
	<center>
	<div id="popupContactx">	
	<div class="panel panel-info" style="margin-right: 25px;margin-left: 25px;">
		<div class="panel-heading"><h3 class="title title-custom">List Data Isi Ulang (Liquid)</h3></div>	
		<div class="panel-body">
		<div class="col-lg-3 col-md-3 col-sm-12">	
			<!--select class = "form-control input-sm" width="15%" onclick="pilih_barang(this)">
				<option value="0">--Pilih Barang--</option>
				<option value="Liquid">Isi Ulang (Liquid)</option>
				<option value="Device">Perlengkapan (Device)</option>
				<option value="Aksesoris">Aksesoris</option>
				<option value="Atomizer">Atomizer</option>
			</select-->
		</div>
		<div class="col-lg-12 col-md-12 col-sm-12">
			<br>
			<form action="" method="post" name="insdata" id="insdata">
				<div class="table-responsive">
					<div style="overflow:auto;height:440px;">
					<table style="font-size:12px;" class="table table-striped table-bordered table-hover" id="dataTables-liquid" width="200%">
						<thead>
						<tr bgcolor="#4ECDC4">		
							<th width="15%">Kode Liquid</th>	
							<th width="30%">Nama Liquid</th>
							<th width="5%">Nic (mg)</th>
							<th width="5%">Vol (ml)</th>
							<th width="5%">On Hand</th>
							<th width="5%">Stok Pusat</th>
							<th width="5%">Stok Retail</th>
							<th width="5%">Stok Studio</th>
							<th width="5%">Bad Stock</th>
							<th width="5%">Berat (gr)</th>
							<th width="15%">Harga Jual Retail</th>
						</tr>
						</thead>
						<tbody>
						<?php
								 for($x=0; $x<count($this->data); $x++){
									 
										$kode_barang 	= $this->data[$x]['kode_barang'];
										$merk_barang 	= $this->data[$x]['merk_barang'];
										$nama_barang 	= $this->data[$x]['nama_barang'];
										$nic		 	= number_format($this->data[$x]['nic'],0,",",".");
										$volume		 	= number_format($this->data[$x]['volume'],0,",",".");
										$on_hand 		= $this->data[$x]['on_hand'];
										$stok_pusat 	= number_format($this->data[$x]['stok_pusat'],0,",",".");
										$stok_retail 	= number_format($this->data[$x]['stok_retail'],0,",",".");
										$stok_studio 	= number_format($this->data[$x]['stok_studio'],0,",",".");
										$bad_stock	 	= number_format($this->data[$x]['bad_stock'],0,",",".");
										$berat		 	= number_format($this->data[$x]['berat'],0,",",".");
										$harga_beli	 	= number_format($this->data[$x]['harga_beli'],0,",",".");
										$harga_beli2	= $this->data[$x]['harga_beli'];
										$hj_agen	 	= number_format($this->data[$x]['hj_agen'],0,",",".");
										$hj_retail	 	= number_format($this->data[$x]['hj_retail'],0,",",".");
										$hj_retail2		= $this->data[$x]['hj_retail'];
										$hj_whs		 	= number_format($this->data[$x]['hj_whs'],0,",",".");
										$kode_supplier 	= $this->data[$x]['kode_supplier'];
										
										$kode_rasa 		= $this->data[$x]['kode_rasa'];
										$rasa = $this->Sopgudang_Service->getrasa($kode_rasa);
									?>	
										<tr>
											<td align="left"><a href="#" onclick="javascript:pilihEmp('<?php echo $kode_barang; ?>','<?php echo $nama_barang; ?>','<?php echo $merk_barang; ?>','<?php echo $rasa; ?>','<?php echo $nic; ?>','<?php echo $volume; ?>','<?php echo $stok_pusat; ?>','<?php echo $bad_stock; ?>')"><?php echo $kode_barang;?></a></td>
											<td align="left"><?php echo $merk_barang;?> - <?php echo $nama_barang;?></td>
											<td align="left"><?php echo $nic;?></td>
											<td align="left"><?php echo $volume;?></td>
											<td align="left"><?php echo $on_hand;?></td>
											<td align="left"><?php echo $stok_pusat;?></td>
											<td align="left"><?php echo $stok_retail;?></td>
											<td align="left"><?php echo $stok_studio;?></td>
											<td align="left"><?php echo $bad_stock;?></td>
											<td align="left"><?php echo $berat;?></td>
											<td align="left"><?php echo $hj_retail;?></td>
										</tr>	
									<?php 
										}
									?>
						</tbody>
					</table>
					</div>
				</div>
			</form>
			</div>			
			<div id='popuptarget'></div>
		</div>
	</div>		
</div>
</center>
</div>
<div id='myDIVx'></div>
<div id="backgroundPopup"></div>
</form>
