<?php require('partial/header.php');?>
<?php require('partial/menu.php');?>    
<script>
	$(document).ready(function () {
		$('#dataTables-emp').dataTable({
			"bPaginate": true,
			"bLengthChange": true,
			"bFilter": true,
			"bInfo": true,
			"bAutoWidth": true});
	});
	 
</script>
    <!-- **********************************************************************************************************************************************************
        MAIN CONTENT
        *********************************************************************************************************************************************************** -->
    <!--main content start-->
	<?php $serialize_permission = unserialize($this->permission);?>
    <section id="main-content">
      <section class="wrapper" style="min-height:522px">
        <h3><i class="fa fa-angle-right"></i> Master Data Customer</h3>
        <div class="row mb">
          <!-- page start-->
          <div class="content-panel">
            <div class="adv-table">
			<div id="listprogram" align="center"  class="col-xs-12">
				<br>
					<div id="page-content">
						<div class="form-group form-group-bottom" align="left">
						<?php if($serialize_permission) { if(in_array('tambahCustomer', $serialize_permission)) { ?>
							<button class="right btn btn-success  btn-xs" onClick="open_url_to_div('/customer/tambahdata')"><i class="fa fa-plus"></i>&nbsp;&nbsp;Tambah Customer</button>		
						<?php } } ?>
						</div>
						<table style="font-size:12px;" class="table table-striped table-bordered table-hover" id="dataTables-emp">
							<thead>
							<tr bgcolor="#4ECDC4">
								<th width="3%" style="text-align:center;">No</th>
								<th width="11%" style="text-align:center;">Kode Customer</th>
								<th width="12%%" style="text-align:center;">Nama Customer</th>
								<th width="12%" style="text-align:center;">Alamat</th>
								<th width="10%" style="text-align:center;">No Tlp</th>
								<th width="10%" style="text-align:center;">No Handphone</th>
								<th width="10%" style="text-align:center;">Email</th>
								<th width="10%" style="text-align:center;">Status</th>
								<th width="10%" style="text-align:center;">Edit</th>
								<th width="10%" style="text-align:center;">Hapus</th>
							</tr>
							</thead>
							<tbody>
							<?php
								 for($x=0; $x<count($this->data); $x++){

										$nomer			= $x+1;
										$kode_customer 	= $this->data[$x]['kode_customer'];
										$nama_customer 	= $this->data[$x]['nama_customer'];
										$alamat_customer = $this->data[$x]['alamat_customer'];
										$no_tlp 		= $this->data[$x]['no_tlp'];
										$no_hp 			= $this->data[$x]['no_hp'];
										$email 			= $this->data[$x]['email'];
										$status 		= $this->data[$x]['status'];
										if($status=='1'){
											$stat = 'Active';
										} else {
											$stat = 'Inactive';
										}
									?>	
											<td align="center"><?php echo $nomer;?></td>	  
											<td align="center"><?php echo $kode_customer;?></td>
											<td align="center"><?php echo $nama_customer;?></td>
											<td align="center"><?php echo $alamat_customer;?></td>
											<td align="center"><?php echo $no_tlp;?></td>
											<td align="center"><?php echo $no_hp;?></td>
											<td align="center"><?php echo $email;?></td>
											<td align="center"><?php echo $stat;?></td>
											<td width="7%">
											<?php if($serialize_permission) { if(in_array('editCustomer', $serialize_permission)) { ?>
                                                <a href="#" title="Edit" onclick="open_url_to_div('/customer/editdata?id=<?php echo $kode_customer;?>')" class="btn-warning btn-sm mar-ed-button"><i class="fa fa-edit pad-ico-button"></i>Edit</a>
                                            <?php } } ?>
											</td>
                                            <td width="8%">
											<?php if($serialize_permission) { if(in_array('hapusCustomer', $serialize_permission)) { ?>
												<a href="#" title="Hapus" onclick="hapusdata('<?php echo $kode_customer; ?>')" class="btn-danger btn-sm mar-ed-button"><i class="fa fa-trash-o pad-ico-button"></i>Hapus</a>
                                            <?php } } ?>
											</td>	
										</tr>	
									<?php 
										}
									?>
								
							</tbody>
						</table>
					  </div>
				</div>
            </div>
          </div>
          <!-- page end-->
        </div>
        <!-- /row -->
      </section>
      <!-- /wrapper -->
    </section>
    <!--main content end-->
    <?php require('partial/main-footer.php');?> 
  </section>
   <!-- js placed at the end of the document so the pages load faster -->
  <script src="lib/jquery/jquery.min.js"></script>
  <script type="text/javascript" language="javascript" src="lib/advanced-datatable/js/jquery.js"></script>
  <script src="lib/bootstrap/js/bootstrap.min.js"></script>
  <script class="include" type="text/javascript" src="lib/jquery.dcjqaccordion.2.7.js"></script>
  <script src="lib/jquery.scrollTo.min.js"></script>
  <script src="lib/jquery.nicescroll.js" type="text/javascript"></script>
  <script type="text/javascript" language="javascript" src="lib/advanced-datatable/js/jquery.dataTables.js"></script>
  <script type="text/javascript" src="lib/advanced-datatable/js/DT_bootstrap.js"></script>
  <!--common script for all pages-->
  <script src="lib/common-scripts.js"></script>
  <!--script for this page-->
  <script type="text/javascript">
	function hapusdata(kode_customer){
			var r = confirm("Anda yakin akan menghapus data ini ?");
			if (r == true) {
					var url = "<?php echo $this->basePath; ?>/customer/hapusdata";
					var opt = {kode_customer:kode_customer}
					
					jQuery.get(url,opt, function(data) {	
						location.reload(true)
						//jQuery("div#example1").html(data);
						//jQuery("#page-content").html(data);
					})
					//open_url_to_div('<?php echo $this->baseUrl(); ?>/pengaduan/index');
					//location.reload(true)
			} else {
				close();
			}
		}
  </script>
</body>

</html>
