<?php require('partial/header.php');?>
<?php require('partial/menu.php');?>    
<script>





	$(document).ready(function () {
		$('#dataTables-emp').dataTable({
			"bPaginate": true,
			"bLengthChange": true,
			"bFilter": true,
			"bInfo": true,
			"bAutoWidth": true});
	});


	 
</script>
    <!-- **********************************************************************************************************************************************************
        MAIN CONTENT
        *********************************************************************************************************************************************************** -->
    <!--main content start-->
    <section id="main-content">
      <section class="wrapper" style="min-height:522px">
        <h3><i class="fa fa-angle-right"></i> Data Batas Waktu</h3>
        <div class="row mb">
          <!-- page start-->
          <div class="content-panel">
            <div class="adv-table">
			<div id="listprogram" align="center"  class="col-xs-12">
				<br>
					<div id="page-content">
					<?php $jumlah = count($this->data); ?>
					<?php if($jumlah == '0'){ ?>
						<div class="form-group form-group-bottom" align="left" id="tambah">
							<button class="right btn btn-success  btn-xs" onClick="tambahdata()"><i class="fa fa-plus"></i>&nbsp;&nbsp;Tambah Data</button>		
						</div>
					<?php } ?>
						
						
	<form id="frm_postdata" name="frm_postdata" enctype="multipart/form-data" method="POST">
	<input type="hidden" name="currentPage" id="currentPage" size="6" maxlength="6" value="<?php echo $this->numPage;?>" class="inputbox2 narrowkey1"></input>
		<?php 
			$seq = $this->seq;
			//var_dump($seq);
			$seq += 1;
			$seq2=str_pad($seq, 2, '0', STR_PAD_LEFT);
		?>
		<input type="hidden" id='seq' name='seq' value ='<?php echo $seq;?>'>
		<input type="hidden" id='action' name='action' value =''>
		<div class="panel">
            <fieldset class="panel-dt">	
				<h4 align="left"><u>Tambah Data</u></h4>
				<br>
					<div class="col-sm-12">
						<table width="100%">
							<tr>
								<td width="10%"><font style="font-size:12px;font-weight:bold;">ID COT</font></td>
								<td width="1%">:</td>
								<td>
									<table>
										<td> <input name="id_cot" id="id_cot" type="text" maxlength="5" size="10" class="form-control input-sm" value="COT<?php echo $seq2;?>" readonly> </td>
										<td> &nbsp; <label id="id_cot-error" for="id_cot" class="error"></td>
									</table>
								</td>
							</tr> 
							<tr><td>&nbsp;</td></tr>
							<tr>
								<td width="10%"><font style="font-size:12px;font-weight:bold;">Batas Waktu</font></td>
								<td width="1%">:</td>
								<td>
									<table>
										<td> <input name="batas_waktu" id="batas_waktu" type="text" maxlength="5" size="10" class="form-control input-sm" value=""> </td>
										<td> &nbsp; <label id="batas_waktu-error" for="batas_waktu" class="error"></td>
									</table>
								</td>
							</tr>
							<tr><td>&nbsp;</td></tr>
							<tr>
								<td width="10%"><font style="font-size:12px;font-weight:bold;">Status</font></td>
								<td width="1%">:</td>
								<td>
									<table>
										<td> 
											<select id="status" name="status" class = "form-control input-sm" width="15%">
												<option value="">--Pilih Status--</option>
												<option value="1">Active</option>
												<option value="0">Inactive</option>
											</select>
										</td>
										<td> &nbsp; <label id="status-error" for="status" class="error"></td>
									</table>
								</td>
							</tr>
							<tr><td>&nbsp;</td></tr>
						</table>
					</div>
				<div class="col-lg-12">
					<div class="form-group form-group-bottom" align="right">
						<input type="hidden" id="proses" name="proses" value="<?php echo $this->proses?>">	
						<br><br>
							<a href="dateline">
							<button type="button" class="btn btn-theme02">
								<span class="fa fa-backward"></span> &nbsp;Kembali
							</button></a>
							<button type="button" class="btn btn-theme03" onCLick="PostData()">
								<span class="fa fa-save"></span> &nbsp;Simpan
							</button>
					</div>
				</div>
			</fieldset>
		</div>
	</form>			
						
						<table style="font-size:12px;" class="table table-striped table-bordered table-hover" id="dataTables-emp">
							<thead>
							<tr bgcolor="#4ECDC4">
								<th width="3%" style="text-align:center;">No</th>
								<th width="7%" style="text-align:center;">ID COT</th>
								<th width="10%" style="text-align:center;">Batas Waktu</th>
								<th width="10%" style="text-align:center;">Status</th>
								<th width="10%" style="text-align:center;">Edit</th>
								<th width="10%" style="text-align:center;">Hapus</th>
							</tr>
							</thead>
							<tbody>
							<?php
								 for($x=0; $x<count($this->data); $x++){

										$nomer		= $x+1;
										$id_cot 	= $this->data[$x]['id_cot'];
										$batas_waktu 	= $this->data[$x]['batas_waktu'];
										$status 	= $this->data[$x]['status'];
										if($status=='1'){
											$stat = 'Active';
										} else {
											$stat = 'Inactive';
										}
									?>	
											<td align="center"><?php echo $nomer;?></td>	  
											<td align="center"><?php echo $id_cot;?></td>
											<td align="center"><?php echo $batas_waktu;?></td>
											<td align="center"><?php echo $stat;?></td>
											<td width="7%">
                                                <a href="#" title="Edit" onClick="editdata('<?php echo $id_cot;?>')" class="btn-warning btn-sm mar-ed-button"><i class="fa fa-edit pad-ico-button"></i>Edit</a>
                                            </td>
                                            <td width="8%">
												<a href="#" title="Hapus" onclick="hapusdata('<?php echo $id_cot; ?>')" class="btn-danger btn-sm mar-ed-button"><i class="fa fa-trash-o pad-ico-button"></i>Hapus</a>
                                            </td>	
										</tr>	
									<?php 
										}
									?>
								
							</tbody>
						</table>
					  </div>
				</div>
            </div>
          </div>
          <!-- page end-->
        </div>
        <!-- /row -->
      </section>
      <!-- /wrapper -->
    </section>
    <!--main content end-->
    <?php require('partial/main-footer.php');?> 
  </section>
   <!-- js placed at the end of the document so the pages load faster -->
  <script src="lib/jquery/jquery.min.js"></script>
  <script type="text/javascript" language="javascript" src="lib/advanced-datatable/js/jquery.js"></script>
  <script src="lib/bootstrap/js/bootstrap.min.js"></script>
  <script class="include" type="text/javascript" src="lib/jquery.dcjqaccordion.2.7.js"></script>
  <script src="lib/jquery.scrollTo.min.js"></script>
  <script src="lib/jquery.nicescroll.js" type="text/javascript"></script>
  <script type="text/javascript" language="javascript" src="lib/advanced-datatable/js/jquery.dataTables.js"></script>
  <script type="text/javascript" src="lib/advanced-datatable/js/DT_bootstrap.js"></script>
  
		<script src="<?php echo $this->baseUrl();?>/lib/jquery.form.js"></script>
		<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl();?>/css/sweetalert.css">
		<script src="<?php echo $this->baseUrl();?>/lib/sweetalert.min.js"></script>
  
  <!--common script for all pages-->
  <script src="lib/common-scripts.js"></script>
  <!--script for this page-->
  <script type="text/javascript">
  $("#frm_postdata").hide();
  
  function tambahdata(){
	  $("#frm_postdata").show();
	  $("#tambah").hide();
	  document.getElementById('action').value="tambah";
  }
  
  function editdata(id_cot){
		$("#frm_postdata").show();
		$("#tambah").hide();
		
		var url = "<?php echo $this->baseUrl; ?>/dateline/editdata";
		var opt = {id_cot:id_cot};
		jQuery.get(url,opt, function(data) { 
			document.getElementById('frm_postdata').innerHTML = data;
			document.getElementById('action').value="edit";
		});
  }
	function hapusdata(id_cot){
			var r = confirm("Anda yakin akan menghapus data ini ?");
			if (r == true) {
					var url = "<?php echo $this->basePath; ?>/dateline/hapusdata";
					var opt = {id_cot:id_cot}
					
					jQuery.get(url,opt, function(data) {	
						location.reload(true)
						//jQuery("div#example1").html(data);
						//jQuery("#page-content").html(data);
					})
					//open_url_to_div('<?php echo $this->baseUrl(); ?>/pengaduan/index');
					//location.reload(true)
			} else {
				close();
			}
		}
	
	function PostData(){
		//alert('Testing2');
        $("#frm_postdata").ajaxSubmit(post_data);
    }
	
	var post_data = {
		target:'',
		beforeSubmit: function() {	
			var batas_waktu = document.getElementById('batas_waktu').value;
			var status = document.getElementById('status').value;
				if (!batas_waktu) {
					document.getElementById('batas_waktu-error').innerHTML ="<span style='color: red;'>batas_waktu Harus Dipilih.</span>";
					document.getElementById('batas_waktu').focus();
					exit;
				}else document.getElementById('batas_waktu-error').innerHTML ='';
				if (status=='') {
					document.getElementById('status-error').innerHTML ="<span style='color: red;'>Status Harus Dipilih.</span>";
					document.getElementById('status').focus();
					exit;
				}else document.getElementById('status-error').innerHTML ='';
			}, 
		success:function(){	
			swal({
				    title: 'Tambah Liquid Berhasil !',
				    text: 'Auto Close...',
				    icon: 'success',
				    timer: 4000,
				    showConfirmButton: false,
				})
			//location.href="#";		
			location.reload(true);
		},
		url: '<?php echo $this->baseUrl();?>/dateline/kirimdata',
		type: 'post',
		resetForm: false
	};
  </script>
</body>

</html>
