<?php require('partial/header.php');?>
<?php require('partial/menu.php');?>    
<script>
	$(document).ready(function () {
		$('#dataTables-emp').dataTable({
			"bPaginate": true,
			"bLengthChange": true,
			"bFilter": true,
			"bInfo": true,
			"bAutoWidth": true});
	});
	 
</script>
    <!-- **********************************************************************************************************************************************************
        MAIN CONTENT
        *********************************************************************************************************************************************************** -->
    <!--main content start-->
	<?php $serialize_permission = unserialize($this->permission);?>
    <section id="main-content">
      <section class="wrapper" style="min-height:522px">
        <h3><i class="fa fa-angle-right"></i> Master Data Perlengkapan (Device)</h3>
        <div class="row mb">
          <!-- page start-->
          <div class="content-panel">
            <div class="adv-table">
			<div id="listprogram" align="center"  class="col-xs-12">
				<br>
					<div id="page-content">
						<div class="form-group form-group-bottom" align="left">
						<?php if($serialize_permission) { if(in_array('tambahPerlengkapan', $serialize_permission)) { ?>
							<button class="right btn btn-success  btn-xs" onClick="open_url_to_div('/device/tambahdata')"><i class="fa fa-plus"></i>&nbsp;&nbsp;Tambah Device</button>		
						<?php } } ?>
						</div>
						<table style="font-size:12px;" class="table table-striped table-bordered table-hover" id="dataTables-emp">
							<thead>
							<tr bgcolor="#4ECDC4">
								<th width="3%" style="text-align:center;">No</th>
								<th width="7%" style="text-align:center;">Kode Device</th>
								<th width="20%" style="text-align:center;">Merk Device</th>
								<th width="10%" style="text-align:center;">Nama Device</th>
								<th width="10%" style="text-align:center;">Jenis Device</th>
								<th width="10%" style="text-align:center;">Stok Pusat</th>
								<th width="10%" style="text-align:center;">Stok Retail</th>
								<th width="10%" style="text-align:center;">Stok Studio</th>
								<th width="10%" style="text-align:center;">Bad Stock</th>
								<th width="10%" style="text-align:center;">Berat (gr)</th>
								<th width="10%" style="text-align:center;">Harga Beli</th>
								<th width="10%" style="text-align:center;">Harga Jual Agn</th>
								<th width="10%" style="text-align:center;">Harga Jual Ret</th>
								<th width="10%" style="text-align:center;">Harga Jual Whs</th>
								<th width="10%" style="text-align:center;">Nama Supplier</th>
								<th width="10%" style="text-align:center;">Tipe</th>
								<th width="10%" style="text-align:center;">Status</th>
								<th width="10%" style="text-align:center;">Edit</th>
								<th width="10%" style="text-align:center;">Hapus</th>
							</tr>
							</thead>
							<tbody>
							<?php
								 for($x=0; $x<count($this->data); $x++){

										$nomer			= $x+1;
										$kode_device 	= $this->data[$x]['kode_device'];
										$merk_device 	= $this->data[$x]['merk_device'];
										$nama_device 	= $this->data[$x]['nama_device'];
										$jenis_device 	= $this->data[$x]['jenis_device'];
										$stok_pusat 	= $this->data[$x]['stok_pusat'];
										$stok_retail 	= $this->data[$x]['stok_retail'];
										$stok_studio 	= $this->data[$x]['stok_studio'];
										$bad_stock	 	= $this->data[$x]['bad_stock'];
										$berat		 	= $this->data[$x]['berat'];
										$harga_beli	 	= $this->data[$x]['harga_beli'];
										$hj_agen	 	= $this->data[$x]['hj_agen'];
										$hj_retail	 	= $this->data[$x]['hj_retail'];
										$hj_whs		 	= $this->data[$x]['hj_whs'];
										$kode_supplier 	= $this->data[$x]['kode_supplier'];
										$status 		= $this->data[$x]['status'];
										if($status=='1'){
											$stat = 'Active';
										} else {
											$stat = 'Inactive';
										}
										
										$supplier = $this->Device_Service->getdatasupplierid($kode_supplier);
										$nama_supplier  = $supplier[0]['nama_supplier'];
										$tipe		 	= $supplier[0]['tipe'];
									?>	
											<td align="center"><?php echo $nomer;?></td>	  
											<td align="center"><?php echo $kode_device;?></td>
											<td align="center"><?php echo $merk_device;?></td>
											<td align="center"><?php echo $nama_device;?></td>
											<td align="center"><?php echo $jenis_device;?></td>
											<td align="center"><?php echo $stok_pusat;?></td>
											<td align="center"><?php echo $stok_retail;?></td>
											<td align="center"><?php echo $stok_studio;?></td>
											<td align="center"><?php echo $bad_stock;?></td>
											<td align="center"><?php echo $berat;?></td>
											<td align="center"><?php echo number_format($harga_beli,0,",",".");?></td>
											<td align="center"><?php echo number_format($hj_agen,0,",",".");?></td>
											<td align="center"><?php echo number_format($hj_retail,0,",",".");?></td>
											<td align="center"><?php echo number_format($hj_whs,0,",",".");?></td>
											<td align="center"><?php echo $nama_supplier;?></td>
											<td align="center"><?php echo $tipe;?></td>
											<td align="center"><?php echo $stat;?></td>
											<td width="7%">
											<?php if($serialize_permission) { if(in_array('editPerlengkapan', $serialize_permission)) { ?>
                                                <a href="#" title="Edit" onclick="open_url_to_div('/device/editdata?id=<?php echo $kode_device;?>')" class="btn-warning btn-sm mar-ed-button"><i class="fa fa-edit pad-ico-button"></i>Edit</a>
                                            <?php } } ?>
											</td>
                                            <td width="8%">
											<?php if($serialize_permission) { if(in_array('hapusPerlengkapan', $serialize_permission)) { ?>
												<a href="#" title="Hapus" onclick="hapusdata('<?php echo $kode_device; ?>')" class="btn-danger btn-sm mar-ed-button"><i class="fa fa-trash-o pad-ico-button"></i>Hapus</a>
                                            <?php } } ?>
											</td>	
										</tr>	
									<?php 
										}
									?>
								
							</tbody>
						</table>
					  </div>
				</div>
            </div>
          </div>
          <!-- page end-->
        </div>
        <!-- /row -->
      </section>
      <!-- /wrapper -->
    </section>
    <!--main content end-->
    <?php require('partial/main-footer.php');?> 
  </section>
   <!-- js placed at the end of the document so the pages load faster -->
  <script src="lib/jquery/jquery.min.js"></script>
  <script type="text/javascript" language="javascript" src="lib/advanced-datatable/js/jquery.js"></script>
  <script src="lib/bootstrap/js/bootstrap.min.js"></script>
  <script class="include" type="text/javascript" src="lib/jquery.dcjqaccordion.2.7.js"></script>
  <script src="lib/jquery.scrollTo.min.js"></script>
  <script src="lib/jquery.nicescroll.js" type="text/javascript"></script>
  <script type="text/javascript" language="javascript" src="lib/advanced-datatable/js/jquery.dataTables.js"></script>
  <script type="text/javascript" src="lib/advanced-datatable/js/DT_bootstrap.js"></script>
  <!--common script for all pages-->
  <script src="lib/common-scripts.js"></script>
  <!--script for this page-->
  <script type="text/javascript">
	function hapusdata(kode_device){
			var r = confirm("Anda yakin akan menghapus data ini ?");
			if (r == true) {
					var url = "<?php echo $this->basePath; ?>/device/hapusdata";
					var opt = {kode_device:kode_device}
					
					jQuery.get(url,opt, function(data) {	
						location.reload(true)
						//jQuery("div#example1").html(data);
						//jQuery("#page-content").html(data);
					})
					//open_url_to_div('<?php echo $this->baseUrl(); ?>/pengaduan/index');
					//location.reload(true)
			} else {
				close();
			}
		}
  </script>
</body>

</html>
