<?php require('partial/header.php');?>
<?php require('partial/menu.php');?>    
<script>
	$(document).ready(function () {
		$('#dataTables-emp').dataTable({
			"bPaginate": true,
			"bLengthChange": true,
			"bFilter": true,
			"bInfo": true,
			"bAutoWidth": true});
	});
	 
</script>
    <!-- **********************************************************************************************************************************************************
        MAIN CONTENT
        *********************************************************************************************************************************************************** -->
    <!--main content start-->
    <section id="main-content">
      <section class="wrapper" style="min-height:522px">
        <h3><i class="fa fa-angle-right"></i> Data User</h3>
        <div class="row mb">
          <!-- page start-->
          <div class="content-panel">
            <div class="adv-table">
			<div id="listprogram" align="center"  class="col-xs-12">
				<br>
					<div id="page-content">
						<form id="frm_postdata" name="frm_postdata" enctype="multipart/form-data" method="POST">
							<input type="hidden" name="i_entry" id="i_entry" value="<?php echo $this->user_id;?>">
							<input type="hidden" id='action' name='action' value =''>
							<div class="panel">
								<fieldset class="panel-dt">	
									<h4 align="left"><u>Ganti Password</u></h4>
									<br>
										<div class="col-sm-12">
											<table width="100%">
												<tr>
													<td width="10%"><font style="font-size:12px;font-weight:bold;">User ID</font></td>
													<td width="1%">:</td>
													<td>
														<table>
															<td> <input name="user_id" id="user_id" type="text" maxlength="20" size="30" class="form-control input-sm" value="<?php echo $this->user_id;?>" readonly > </td>
															<td> &nbsp; <label id="user_id-error" for="user_id" class="error"></td>
														</table>
													</td>
												</tr> 
												<tr><td>&nbsp;</td></tr>
												<tr>
													<td width="10%"><font style="font-size:12px;font-weight:bold;">Password Lama</font></td>
													<td width="1%">:</td>
													<td>
														<table>
															<td> <input type="password" name="oldpassword" id="oldpassword" maxlength="50" size="50" class="form-control input-sm" value="" onchange="checkData(this)" > </td>
															<td> &nbsp; <label id="oldpassword-error" for="oldpassword" class="error"></td>
														</table>
													</td>
												</tr>
												<tr><td>&nbsp;</td></tr>
												<tr>
													<td width="10%"><font style="font-size:12px;font-weight:bold;">Password Baru</font></td>
													<td width="1%">:</td>
													<td>
														<table>
															<td> <input name="password" id="password" type="password" maxlength="50" size="30" class="form-control input-sm" value=""> </td>
															<td> &nbsp; <label id="password-error" for="password" class="error"></td>
														</table>
													</td>
												</tr>
												<tr><td>&nbsp;</td></tr>
												<tr>
													<td width="10%"><font style="font-size:12px;font-weight:bold;">Ulangi Password Baru</font></td>
													<td width="1%">:</td>
													<td>
														<table>
															<td> <input name="password2" id="password2" type="password" maxlength="50" size="30" class="form-control input-sm" value=""> </td>
															<td> &nbsp; <label id="password2-error" for="password2" class="error"></td>
														</table>
													</td>
												</tr>
												<tr><td>&nbsp;</td></tr>
											</table>
										</div>
									<div class="col-lg-12">
										<div class="form-group form-group-bottom" align="right">
											<input type="hidden" id="proses" name="proses" value="<?php echo $this->proses?>">	
											<br><br>
												<a href="user">
												<button type="button" class="btn btn-theme02">
													<span class="fa fa-backward"></span> &nbsp;Kembali
												</button></a>
												<button type="button" class="btn btn-theme03" onCLick="PostData()">
													<span class="fa fa-save"></span> &nbsp;Simpan
												</button>
										</div>
									</div>
								</fieldset>
							</div>
						</form>			
					  </div>
				</div>
            </div>
          </div>
          <!-- page end-->
        </div>
        <!-- /row -->
      </section>
      <!-- /wrapper -->
    </section>
    <!--main content end-->
    <?php require('partial/main-footer.php');?> 
  </section>
   <!-- js placed at the end of the document so the pages load faster -->
  <script src="lib/jquery/jquery.min.js"></script>
  <script type="text/javascript" language="javascript" src="lib/advanced-datatable/js/jquery.js"></script>
  <script src="lib/bootstrap/js/bootstrap.min.js"></script>
  <script class="include" type="text/javascript" src="lib/jquery.dcjqaccordion.2.7.js"></script>
  <script src="lib/jquery.scrollTo.min.js"></script>
  <script src="lib/jquery.nicescroll.js" type="text/javascript"></script>
  <script type="text/javascript" language="javascript" src="lib/advanced-datatable/js/jquery.dataTables.js"></script>
  <script type="text/javascript" src="lib/advanced-datatable/js/DT_bootstrap.js"></script>
  
		<script src="<?php echo $this->baseUrl();?>/lib/jquery.form.js"></script>
		<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl();?>/css/sweetalert.css">
		<script src="<?php echo $this->baseUrl();?>/lib/sweetalert.min.js"></script>
  
  <!--common script for all pages-->
  <script src="lib/common-scripts.js"></script>
  <!--script for this page-->
  <script type="text/javascript">
	function checkData(input){
		var oldpassword = input.value;
		var user_id = document.getElementById('user_id').value;
		//alert(user_id);
				
		var url = "<?php echo $this->baseUrl; ?>/gntpassword/cekdatapassword";
		var opt = {oldpassword:oldpassword,user_id:user_id};
	
		jQuery.get(url,opt, function(data) {
			//alert(data);
			if(data == '0'){
				document.getElementById('oldpassword-error').innerHTML ="<span style='color: red;'>Password lama tidak sesuai.</span>";
				document.getElementById('oldpassword').focus();
				document.getElementById('oldpassword').value = '';
			}else document.getElementById('oldpassword-error').innerHTML ='';
		});
		
		//alert(test);
	}
	
	function PostData(){
		//alert('Testing2');
        $("#frm_postdata").ajaxSubmit(post_data);
    }
	
	var post_data = {
		target:'',
		beforeSubmit: function() {	
			var oldpassword = document.getElementById('oldpassword').value;
			var password = document.getElementById('password').value;
			var password2 = document.getElementById('password2').value;
				if (!oldpassword) {
					document.getElementById('oldpassword-error').innerHTML ="<span style='color: red;'>Password Lama Harus Diisi.</span>";
					document.getElementById('oldpassword').focus();
					exit;
				}else document.getElementById('oldpassword-error').innerHTML ='';
				
				if (!password) {
					document.getElementById('password-error').innerHTML ="<span style='color: red;'>Password Baru Harus Diisi.</span>";
					document.getElementById('password').focus();
					exit;
				}else document.getElementById('password-error').innerHTML ='';
				if (!password2) {
					document.getElementById('password2-error').innerHTML ="<span style='color: red;'>Ulang Password Baru.</span>";
					document.getElementById('password2').focus();
					exit;
				}else document.getElementById('password2-error').innerHTML ='';
				if (password == password2) {
					document.getElementById('password2-error').innerHTML ='';
				} else {
					document.getElementById('password2-error').innerHTML ="<span style='color: red;'>Password Baru Tidak Cocok.</span>";
					document.getElementById('password2').focus();
					exit;
				}
			}, 
		success:function(){	
			swal({
				    title: 'Tambah Liquid Berhasil !',
				    text: 'Auto Close...',
				    icon: 'success',
				    timer: 4000,
				    showConfirmButton: false,
				})
			//location.href="#";		
			location.reload(true);
		},
		url: '<?php echo $this->baseUrl();?>/gntpassword/kirimdata',
		type: 'post',
		resetForm: false
	};
  </script>
</body>

</html>
