<div id="layoutnya">
  <?php require('partial/header.php'); ?>
  <?php require('partial/menu.php'); ?>
  <?php
  require_once 'Zend/View.php';
  require_once 'share/oa_page.php';
  $halaman = new oa_page();
  $ctrlFrm = new Zend_View();

  $currentPage  = $this->currentPage;
  ?>
  <script>
    $(document).ready(function() {
      $('#dataTables-emp').dataTable({
        "bPaginate": true,
        "bLengthChange": true,
        "bFilter": true,
        "bInfo": true,
        "bAutoWidth": true
      });
    });
  </script>
  <link href="<?php echo $this->baseUrl(); ?>/css/select2.min.css" rel="stylesheet">
  <link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/calendar/daterangepicker-master/daterangepicker.css" />
  <style>
    .select2-selection__rendered {
      font-size: 13px;
    }

    tfoot {
      background-color: #fafafa;
      /* color: #fff; */
    }
  </style>
  <!-- **********************************************************************************************************************************************************
        MAIN CONTENT
        *********************************************************************************************************************************************************** -->
  <!--main content start-->
  <?php $serialize_permission = unserialize($this->permission); ?>
  <section id="main-content">
    <section class="wrapper">
      <h3><i class="fa fa-angle-right"></i> Sales By Customer Summary</h3>
      <div class="row mb">
        <!-- page start-->
        <div class="content-panel">
          <div class="adv-table">
            <div id="listprogram" class="col-xs-12">
              <br>
              <div id="page-content">
                <div class="col-lg-12">
                  <div class="panel">
                    <div class="panel-body">
                      <form class="form-horizontal">
                        <div class="form-group">
                          <label for="inputEmail3" class="col-sm-2 control-label">Pilih Tanggal</label>
                          <div class="col-sm-4">
                            <input type="text" class="form-control readonly" id="perioddate" name="perioddate" value="" readonly />
                          </div>
                        </div>
                        <div class="form-group">
                          <div class="col-sm-offset-2 col-sm-10">
                            <button type="submit" class="btn btn-default">Terapkan</button>
                          </div>
                        </div>
                      </form>

                    </div>
                  </div>
                  <table class="table" id="sales-by-customer-detail-table" style="font-size: 1.25rem;">
                    <thead style="background-color: #4ECDC4; color: #fff;">
                      <tr>
                        <td>Product</td>
                        <td>Total</td>
                      </tr>
                    </thead>
                    <tbody>
                      <?php foreach ($this->totalPurchases as $purchase) : ?>
                        <tr>
                          <td><?= $purchase['nama_barang'] ?></td>
                          <td class="text-right"><?= number_format($purchase['total'], 0, ',', '.') ?></td>
                        </tr>
                      <?php endforeach; ?>
                    </tbody>
                    <tfoot>
                      <tr>
                        <td><strong>TOTAL</strong></td>
                        <td></td>
                      </tr>
                    </tfoot>
                  </table>
                </div>
              </div>
            </div>
          </div>
        </div>
        <!-- page end-->
      </div>
      <!-- /row -->
    </section>
    <!-- /wrapper -->
  </section>
  <!--main content end-->
  <?php require('partial/main-footer.php'); ?>
  </section>
  <!-- js placed at the end of the document so the pages load faster -->
  <script src="lib/jquery/jquery.min.js"></script>
  <script type="text/javascript" language="javascript" src="lib/advanced-datatable/js/jquery.js"></script>
  <script src="lib/bootstrap/js/bootstrap.min.js"></script>
  <script class="include" type="text/javascript" src="lib/jquery.dcjqaccordion.2.7.js"></script>
  <script src="lib/jquery.scrollTo.min.js"></script>
  <script src="lib/jquery.nicescroll.js" type="text/javascript"></script>
  <!-- <script type="text/javascript" language="javascript" src="lib/advanced-datatable/js/jquery.dataTables.js"></script> -->
  <script type="text/javascript" src="https://cdn.datatables.net/v/dt/dt-1.10.23/datatables.min.js"></script>
  <script type="text/javascript" src="lib/advanced-datatable/js/DT_bootstrap.js"></script>
  <script src="https://cdn.datatables.net/rowgroup/1.1.2/js/dataTables.rowGroup.min.js"></script>
  <script src="https://cdn.datatables.net/buttons/1.7.0/js/dataTables.buttons.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/pdfmake.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/vfs_fonts.js"></script>
  <script src="https://cdn.datatables.net/buttons/1.7.0/js/buttons.html5.min.js"></script>
  <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/calendar/daterangepicker-master/moment.min.js"></script>
  <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/calendar/daterangepicker-master/daterangepicker.js"></script>
  <script src="<?php echo $this->baseUrl(); ?>/lib/select2.full.min.js"></script>
  <!--common script for all pages-->
  <script src="lib/common-scripts.js"></script>
  <script>
    $('#sales-by-customer-detail-table').DataTable({
      "paging": false,
      "footerCallback": function(row, data, start, end, display) {
        var api = this.api(),
          data;

        // Remove the formatting to get integer data for summation
        var intVal = function(i) {
          return typeof i === 'string' ?
            i.replace(/[\$.]/g, '') * 1 :
            typeof i === 'number' ?
            i : 0;
        };

        // Total over all pages
        total = api
          .column(1)
          .data()
          .reduce(function(a, b) {
            return intVal(a) + intVal(b);
          }, 0);

        total = $.fn.dataTable.render.number('.', ',', 0, 'Rp ').display(total);
        // Update footer
        $(api.column(1).footer()).html(`<span class="text-right" style="display: block"><strong>${total}</strong></span>`);
      },
      dom: 'Bfrtip',
        buttons: [
            'copyHtml5',
            'excelHtml5',
            'csvHtml5',
            'pdfHtml5'
        ]
    });

    $('#perioddate').daterangepicker({
      autoUpdateInput: true,
      "opens": "left",
      locale: {
        "format": "DD/MM/YYYY",
        "separator": " - ",
        "applyLabel": "Apply",
        "cancelLabel": "Clear",
        "firstDay": 1
      }
    });

    $('#perioddate').on('apply.daterangepicker', function(ev, picker) {
      console.log(picker.startDate.format('YYYY-MM-DD'));
      console.log(picker.endDate.format('YYYY-MM-DD'));
    })

    $('#perioddate').on('cancel.daterangepicker', function(ev, picker) {
      //do something, like clearing an input
      $('#perioddate').val('');
    });
  </script>

</div>
</body>

</html>