<?php require('partial/header.php');?>
<?php require('partial/menu.php');?>    
<script>
	$(document).ready(function () {
		$('#dataTables-emp').dataTable({
			"bPaginate": true,
			"bLengthChange": true,
			"bFilter": true,
			"bInfo": true,
			"bAutoWidth": true});
	});
	 
</script>
    <!-- **********************************************************************************************************************************************************
        MAIN CONTENT
        *********************************************************************************************************************************************************** -->
    <!--main content start-->
	<?php $serialize_permission = unserialize($this->permission);?>
    <section id="main-content">
      <section class="wrapper" style="min-height:522px">
        <h3><i class="fa fa-angle-right"></i> Transaksi Pembelian Barang</h3>
        <div class="row mb">
          <!-- page start-->
          <div class="content-panel">
            <div class="adv-table">
			<div id="listprogram" align="center"  class="col-xs-12">
				<br>
					<div id="page-content">
						<div class="form-group form-group-bottom" align="left">
						<?php if($serialize_permission) { if(in_array('tambahOrderCentral', $serialize_permission)) { ?>
							<button class="right btn btn-success  btn-xs" onClick="open_url_to_div('/ordercentral/tambahdata')"><i class="fa fa-plus"></i>&nbsp;&nbsp;Tambah Pembelian Barang</button>		
						<?php } } ?>
						</div>
						<table style="font-size:12px;" class="table table-striped table-bordered table-hover" id="dataTables-emp">
							<thead>
							<tr bgcolor="#4ECDC4">
								<th width="3%" style="text-align:center;">No</th>
								<th width="7%" style="text-align:center;">Nomor Order</th>
								<th width="20%" style="text-align:center;">Nama Supplier</th>
								<th width="10%" style="text-align:center;">Kode Supplier</th>
								<th width="10%" style="text-align:center;">Status Barang</th>
								<th width="10%" style="text-align:center;">Total</th>
								<th width="10%" style="text-align:center;">Biaya Kirim</th>
								<th width="10%" style="text-align:center;">Diskon</th>
								<th width="10%" style="text-align:center;">Net Total</th>
								<th width="10%" style="text-align:center;">Jumah Bayar/DP</th>
								<th width="10%" style="text-align:center;">Sisa Pembayaran</th>
								<th width="10%" style="text-align:center;">Tanggal Order</th>
								<th width="10%" style="text-align:center;">Edit/Detail</th>
								<th width="10%" style="text-align:center;">Hapus</th>
							</tr>
							</thead>
							<tbody>
							<?php
								 for($x=0; $x<count($this->data); $x++){

										$nomer			= $x+1;
										$no_order 		= $this->data[$x]['no_order'];
										$kode_supplier 	= $this->data[$x]['kode_supplier'];
										$total 			= number_format($this->data[$x]['total'],0,",",".");
										$biaya_kirim	= number_format($this->data[$x]['biaya_kirim'],0,",",".");
										$diskon 		= number_format($this->data[$x]['diskon'],0,",",".");
										$net_total	 	= number_format($this->data[$x]['net_total'],0,",",".");
										$jml_bayar_dp 	= number_format($this->data[$x]['jml_bayar_dp'],0,",",".");
										$sisa_bayar	 	= number_format($this->data[$x]['sisa_bayar'],0,",",".");
										$tgl_order	 	= date_create($this->data[$x]['tgl_order']);
										$tgl_order		= date_format($tgl_order,"d-m-Y");
										
										$supplier = $this->Ordercentral_Service->getdatasupplierid($kode_supplier);
										$nama_supplier  = $supplier[0]['nama_supplier'];
										$tipe		 	= $supplier[0]['tipe'];
										
										$hutang = $this->Ordercentral_Service->getDataHutang($no_order);
									?>	
										<tr>
											<td align="center"><?php echo $nomer;?></td>	  
											<td align="center"><?php echo $no_order;?></td>
											<td align="center"><?php echo $nama_supplier;?></td>
											<td align="center"><?php echo $kode_supplier;?></td>
											<td align="center"><?php echo $tipe;?></td>
											<td align="center"><?php echo $total;?></td>
											<td align="center"><?php echo $biaya_kirim;?></td>
											<td align="center"><?php echo $diskon;?></td>
											<td align="center"><?php echo $net_total;?></td>
											<td align="center"><?php echo $jml_bayar_dp;?></td>
											<td align="center"><?php echo $sisa_bayar;?></td>
											<td align="center"><?php echo $tgl_order;?></td>
										<?php if($hutang == '1'){ ?>
											<td width="7%">
											<?php if($serialize_permission) { if(in_array('editOrderCentral', $serialize_permission)) { ?>
                                                <a href="#" title="Edit" onclick="open_url_to_div('/ordercentral/editdata?id=<?php echo $no_order;?>')" class="btn-warning btn-sm mar-ed-button"><i class="fa fa-edit pad-ico-button"></i>Edit</a>
                                            <?php } } ?>
											</td>
                                            <td width="8%">
											<?php if($serialize_permission) { if(in_array('hapusOrderCentral', $serialize_permission)) { ?>
												<a href="#" title="Hapus" onclick="hapusdata('<?php echo $no_order; ?>')" class="btn-danger btn-sm mar-ed-button"><i class="fa fa-trash-o pad-ico-button"></i>Hapus</a>
                                            <?php } } ?>
											</td>
										<?php } else { ?>
											<td width="7%">
                                                <a href="#" title="Detail" onclick="open_url_to_div('/ordercentral/detail?id=<?php echo $no_order;?>')" class="btn-warning btn-sm mar-ed-button">Detail</a>
                                            </td>
                                            <td width="8%"></td>
										<?php }	?>
										</tr>	
									<?php 
										}
									?>
								
							</tbody>
						</table>
					  </div>
				</div>
            </div>
          </div>
          <!-- page end-->
        </div>
        <!-- /row -->
      </section>
      <!-- /wrapper -->
    </section>
    <!--main content end-->
    <?php require('partial/main-footer.php');?> 
  </section>
   <!-- js placed at the end of the document so the pages load faster -->
  <script src="lib/jquery/jquery.min.js"></script>
  <script type="text/javascript" language="javascript" src="lib/advanced-datatable/js/jquery.js"></script>
  <script src="lib/bootstrap/js/bootstrap.min.js"></script>
  <script class="include" type="text/javascript" src="lib/jquery.dcjqaccordion.2.7.js"></script>
  <script src="lib/jquery.scrollTo.min.js"></script>
  <script src="lib/jquery.nicescroll.js" type="text/javascript"></script>
  <script type="text/javascript" language="javascript" src="lib/advanced-datatable/js/jquery.dataTables.js"></script>
  <script type="text/javascript" src="lib/advanced-datatable/js/DT_bootstrap.js"></script>
  <!--common script for all pages-->
  <script src="lib/common-scripts.js"></script>
  <!--script for this page-->
  <script type="text/javascript">
	function hapusdata(no_order){
			var r = confirm("Anda yakin akan menghapus data ini ?");
			if (r == true) {
					var url = "<?php echo $this->basePath; ?>/ordercentral/hapusdata";
					var opt = {no_order:no_order}
					
					jQuery.get(url,opt, function(data) {	
						location.reload(true)
						//jQuery("div#example1").html(data);
						//jQuery("#page-content").html(data);
					})
					//open_url_to_div('<?php echo $this->baseUrl(); ?>/pengaduan/index');
					//location.reload(true)
			} else {
				close();
			}
		}
  </script>
</body>

</html>
