<?php require('partial/header.php');?>
<?php require('partial/menu.php');?>    
<script>
	$(document).ready(function () {
		$('#dataTables-emp').dataTable({
			"bPaginate": true,
			"bLengthChange": true,
			"bFilter": true,
			"bInfo": true,
			"bAutoWidth": true});
	});
	 
</script>
    <!-- **********************************************************************************************************************************************************
        MAIN CONTENT
        *********************************************************************************************************************************************************** -->
    <!--main content start-->
	<?php $serialize_permission = unserialize($this->permission);?>
    <section id="main-content">
      <section class="wrapper" style="min-height:522px">
        <h3><i class="fa fa-angle-right"></i> Transaksi Pembayaran Customer (Piutang)</h3>
        <div class="row mb">
          <!-- page start-->
          <div class="content-panel">
            <div class="adv-table">
			<div id="listprogram" align="center"  class="col-xs-12">
				<br>
					<div id="page-content">
						<!--div class="form-group form-group-bottom" align="left">
							<button class="right btn btn-success  btn-xs" onClick="open_url_to_div('/pembayarancustomer/tambahdata')"><i class="fa fa-plus"></i>&nbsp;&nbsp;Tambah Pembelian Barang</button>		
						</div-->
						<table style="font-size:12px;" class="table table-striped table-bordered table-hover" id="dataTables-emp">
							<thead>
							<tr bgcolor="#4ECDC4">
								<th width="3%" style="text-align:center;">No</th>
								<th width="20%" style="text-align:center;">Nomor Invoice</th>
								<th width="15%" style="text-align:center;">Nama Pelanggan</th>
								<th width="15%" style="text-align:center;">Nama Sales</th>
								<th width="8%" style="text-align:center;">Grand Total</th>
								<th width="8%" style="text-align:center;">Jumlah Bayar</th>
								<th width="8%" style="text-align:center;">Sisa Pembayaran</th>
								<th width="8%" style="text-align:center;">Tanggal Invoice</th>
								<th width="9%" style="text-align:center;">Status</th>
								<th width="6%" style="text-align:center;">Action</th>
							</tr>
							</thead>
							<tbody>
							<?php
								 for($x=0; $x<count($this->data); $x++){

										$nomer			= $x+1;
										$no_invoice 	= $this->data[$x]['no_invoice'];
										$tgl_invoice	= date_create($this->data[$x]['tgl_invoice']);
										$tgl_invoice	= date_format($tgl_invoice,"d-m-Y");
										$kode_customer 	= $this->data[$x]['kode_customer'];
										$kode_sales 	= $this->data[$x]['kode_sales'];
										$net_total	 	= $this->data[$x]['net_total'];
										$jml_bayar	 	= $this->data[$x]['jml_bayar'];
										$sisa_bayar	 	= $this->data[$x]['sisa_bayar'];
										$nama_customer  = '';
										$nama_sales  	= '';
										
										if($kode_customer){
											$customer = $this->Pembayarancustomer_Service->getdatacustomerid($kode_customer);
											$nama_customer  = $customer[0]['nama_customer'];
										}
										
										if($kode_sales){
											$sales = $this->Pembayarancustomer_Service->getdatasalesid($kode_sales);
											$nama_sales  = $sales[0]['nama_sales'];
										}
										
										
										if(($jml_bayar >= $net_total) || ($sisa_bayar <= 0)){
											$status = 'Finished';
										} else {
											$status = 'Un-Finished';
										}
									?>	
										<tr>
											<td align="center"><?php echo $nomer;?></td>	  
											<td align="center"><?php echo $no_invoice;?></td>
											<td align="center"><?php echo $nama_customer;?></td>
											<td align="center"><?php echo $nama_sales;?></td>
											<td align="center"><?php echo number_format($net_total,0,",",".");?></td>
											<td align="center"><?php echo number_format($jml_bayar,0,",",".");?></td>
											<td align="center"><?php echo number_format($sisa_bayar,0,",",".");?></td>
											<td align="center"><?php echo $tgl_invoice;?></td>
											<td align="center"><?php echo $status;?></td>
											<td width="7%" align="center">
											<?php if($status == 'Finished'){ ?>
													<a href="#" title="Detail" onclick="open_url_to_div('/pembayarancustomer/detail?id=<?php echo $no_invoice;?>')" class="btn-warning btn-sm mar-ed-button">Detail</a>
											<?php } else { ?>
												<?php if($serialize_permission) { if(in_array('tambahPembayaranCustomer', $serialize_permission)) { ?>
													<a href="#" title="Bayar" onclick="open_url_to_div('/pembayarancustomer/editdata?id=<?php echo $no_invoice;?>')" class="btn-warning btn-sm mar-ed-button">Bayar</a>
												<?php } } ?>
											<?php } ?>
                                            </td>
										</tr>	
									<?php 
										}
									?>
								
							</tbody>
						</table>
					  </div>
				</div>
            </div>
          </div>
          <!-- page end-->
        </div>
        <!-- /row -->
      </section>
      <!-- /wrapper -->
    </section>
    <!--main content end-->
    <?php require('partial/main-footer.php');?> 
  </section>
   <!-- js placed at the end of the document so the pages load faster -->
  <script src="lib/jquery/jquery.min.js"></script>
  <script type="text/javascript" language="javascript" src="lib/advanced-datatable/js/jquery.js"></script>
  <script src="lib/bootstrap/js/bootstrap.min.js"></script>
  <script class="include" type="text/javascript" src="lib/jquery.dcjqaccordion.2.7.js"></script>
  <script src="lib/jquery.scrollTo.min.js"></script>
  <script src="lib/jquery.nicescroll.js" type="text/javascript"></script>
  <script type="text/javascript" language="javascript" src="lib/advanced-datatable/js/jquery.dataTables.js"></script>
  <script type="text/javascript" src="lib/advanced-datatable/js/DT_bootstrap.js"></script>
  <!--common script for all pages-->
  <script src="lib/common-scripts.js"></script>
  <!--script for this page-->
  <script type="text/javascript">
	function hapusdata(no_order){
			var r = confirm("Anda yakin akan menghapus data ini ?");
			if (r == true) {
					var url = "<?php echo $this->basePath; ?>/pembayarancustomer/hapusdata";
					var opt = {no_order:no_order}
					
					jQuery.get(url,opt, function(data) {	
						location.reload(true)
						//jQuery("div#example1").html(data);
						//jQuery("#page-content").html(data);
					})
					//open_url_to_div('<?php echo $this->baseUrl(); ?>/pengaduan/index');
					//location.reload(true)
			} else {
				close();
			}
		}
  </script>
</body>

</html>
