<?php require('partial/header.php');?>
<?php require('partial/menu.php');?>    
<script>
	$(document).ready(function () {
		$('#dataTables-emp').dataTable({
			"bPaginate": true,
			"bLengthChange": true,
			"bFilter": true,
			"bInfo": true,
			"bAutoWidth": true});
	});
	 
</script>
    <!-- **********************************************************************************************************************************************************
        MAIN CONTENT
        *********************************************************************************************************************************************************** -->
    <!--main content start-->
	<?php $serialize_permission = unserialize($this->permission);?>
    <section id="main-content">
      <section class="wrapper" style="min-height:522px">
        <h3><i class="fa fa-angle-right"></i> Penyelesaian Retur Penjualan</h3>
        <div class="row mb">
          <!-- page start-->
          <div class="content-panel">
            <div class="adv-table">
			<div id="listprogram" align="center"  class="col-xs-12">
				<br>
					<div id="page-content">
						<div class="form-group form-group-bottom" align="left">
							<button class="right btn btn-success  btn-xs" onClick="open_url_to_div('/penyelesaianpenjualan/history')">&nbsp;&nbsp;Lihat Hystory</button>		
						</div>
						<table style="font-size:12px;" class="table table-striped table-bordered table-hover" id="dataTables-emp">
							<thead>
							<tr bgcolor="#4ECDC4">
								<th width="3%" style="text-align:center;">No</th>
								<th width="7%" style="text-align:center;">Nomor Retur</th>
								<th width="10%" style="text-align:center;">Tanggal Retur</th>
								<th width="7%" style="text-align:center;">Nomor Invoice</th>
								<th width="10%" style="text-align:center;">Tanggal Invoice</th>
								<th width="20%" style="text-align:center;">Nama Supplier</th>
								<th width="10%" style="text-align:center;">Selisih Pembayaran</th>
								<th width="10%" style="text-align:center;">Action</th>
							</tr>
							</thead>
							<tbody>
							<?php
								 for($x=0; $x<count($this->data); $x++){

										$nomer			= $x+1;
										$no_invoice 		= $this->data[$x]['no_invoice'];
										$tgl_invoice	 	= date_create($this->data[$x]['tgl_invoice']);
										$tgl_invoice		= date_format($tgl_invoice,"d-m-Y");
										$sisa_bayar	 	= number_format($this->data[$x]['sisa_bayar'],0,",",".");
										$kode_customer 	= $this->data[$x]['kode_customer'];
										$no_retur 		= $this->data[$x]['no_retur'];
										$tgl_retur	 	= date_create($this->data[$x]['tgl_retur']);
										$tgl_retur		= date_format($tgl_retur,"d-m-Y");
										
										$customer = $this->Penyelesaianpenjualan_Service->getdatasupplierid($kode_customer);
										$nama_customer  = $customer[0]['nama_customer'];
									?>	
										<tr>
											<td align="center"><?php echo $nomer;?></td>	
											<td align="center"><?php echo $no_retur;?></td>
											<td align="center"><?php echo $tgl_retur;?></td>	
											<td align="center"><?php echo $no_invoice;?></td>
											<td align="center"><?php echo $tgl_invoice;?></td>
											<td align="center"><?php echo $nama_customer;?></td>
											<td align="center"><?php echo $sisa_bayar;?></td>
											<td width="7%" align="center">
											<?php if($serialize_permission) { if(in_array('tambahPenyelesaianPenjualan', $serialize_permission)) { ?>
												<a href="#" title="Bayar" onclick="open_url_to_div('/penyelesaianpenjualan/editdata?id=<?php echo $no_retur;?>')" class="btn-warning btn-sm mar-ed-button">Bayar</a>
											<?php } } ?>
										    </td>
										</tr>	
									<?php 
										}
									?>
								
							</tbody>
						</table>
					  </div>
				</div>
            </div>
          </div>
          <!-- page end-->
        </div>
        <!-- /row -->
      </section>
      <!-- /wrapper -->
    </section>
    <!--main content end-->
    <?php require('partial/main-footer.php');?> 
  </section>
   <!-- js placed at the end of the document so the pages load faster -->
  <script src="lib/jquery/jquery.min.js"></script>
  <script type="text/javascript" language="javascript" src="lib/advanced-datatable/js/jquery.js"></script>
  <script src="lib/bootstrap/js/bootstrap.min.js"></script>
  <script class="include" type="text/javascript" src="lib/jquery.dcjqaccordion.2.7.js"></script>
  <script src="lib/jquery.scrollTo.min.js"></script>
  <script src="lib/jquery.nicescroll.js" type="text/javascript"></script>
  <script type="text/javascript" language="javascript" src="lib/advanced-datatable/js/jquery.dataTables.js"></script>
  <script type="text/javascript" src="lib/advanced-datatable/js/DT_bootstrap.js"></script>
  <!--common script for all pages-->
  <script src="lib/common-scripts.js"></script>
  <!--script for this page-->
  <script type="text/javascript">
	function hapusdata(no_invoice){
			var r = confirm("Anda yakin akan menghapus data ini ?");
			if (r == true) {
					var url = "<?php echo $this->basePath; ?>/penyelesaianpenjualan/hapusdata";
					var opt = {no_invoice:no_invoice}
					
					jQuery.get(url,opt, function(data) {	
						location.reload(true)
						//jQuery("div#example1").html(data);
						//jQuery("#page-content").html(data);
					})
					//open_url_to_div('<?php echo $this->baseUrl(); ?>/pengaduan/index');
					//location.reload(true)
			} else {
				close();
			}
		}
  </script>
</body>

</html>
