<?php require('partial/header.php');?>
<?php require('partial/menu.php');?>    
<script>
	$(document).ready(function () {
		$('#dataTables-emp').dataTable({
			"bPaginate": true,
			"bLengthChange": true,
			"bFilter": true,
			"bInfo": true,
			"bAutoWidth": true});
	});
	 
</script>
    <!-- **********************************************************************************************************************************************************
        MAIN CONTENT
        *********************************************************************************************************************************************************** -->
    <!--main content start-->
    <section id="main-content">
      <section class="wrapper" style="min-height:522px">
        <h3><i class="fa fa-angle-right"></i> Transaksi Penjualan Barang</h3>
        <div class="row mb">
          <!-- page start-->
          <div class="content-panel">
            <div class="adv-table">
			<div id="listprogram" align="center"  class="col-xs-12">
				<br>
					<div id="page-content">
						<div class="form-group form-group-bottom" align="left">
							<button class="right btn btn-success  btn-xs" onClick="open_url_to_div('/saleretail/tambahdata')"><i class="fa fa-plus"></i>&nbsp;&nbsp;Tambah Penjualan Barang</button>		
						</div>
						<div class="table-responsive">
						<table style="font-size:12px;" class="table table-striped table-bordered table-hover" id="dataTables-emp">
							<thead>
							<tr bgcolor="#4ECDC4">
								<th width="2%" style="text-align:center;">No</th>
								<th width="18%" style="text-align:center;">Nomor Invoice</th>
								<th width="4%" style="text-align:center;">Tanggal Invoice</th>
								<th width="5%" style="text-align:center;">Total</th>
								<th width="5%" style="text-align:center;">Pembayaran</th>
								<th width="5%" style="text-align:center;">Jumlah Bayar</th>
								<th width="5%" style="text-align:center;">Kembali</th>
								<th width="5%" style="text-align:center;">Biaya Admin</th>
								<th width="3%" style="text-align:center;">Detail</th>
							</tr>
							</thead>
							<tbody>
							<?php
								 for($x=0; $x<count($this->data); $x++){

										$nomer			 = $x+1;
										$no_invoice 	 = $this->data[$x]['no_invoice'];
										$tgl_invoice	 = date_create($this->data[$x]['tgl_invoice']);
										$tgl_invoice	 = date_format($tgl_invoice,"d-m-Y");
										$total_biaya 	 = number_format($this->data[$x]['total_biaya'],0,",",".");
										$metode_pembayaran 	 = $this->data[$x]['metode_pembayaran'];
										$no_rekening 		 = $this->data[$x]['no_rekening'];
										$jml_pembayaran 	 = number_format($this->data[$x]['jml_pembayaran'],0,",",".");
										$uang_kembali 		 = number_format($this->data[$x]['uang_kembali'],0,",",".");
										$biaya_admin	 = number_format($this->data[$x]['biaya_admin'],0,",",".");
										
									?>	
										<tr>
											<td align="center"><?php echo $nomer;?></td>	  
											<td align="center"><?php echo $no_invoice;?></td>
											<td align="center"><?php echo $tgl_invoice;?></td>
											<td align="center"><?php echo $total_biaya;?></td>
											<td align="center"><?php echo $metode_pembayaran;?></td>
											<td align="center"><?php echo $jml_pembayaran;?></td>
											<td align="center"><?php echo $uang_kembali;?></td>
											<td align="center"><?php echo $biaya_admin;?></td>
											<td align="center"><a href="#" title="Detail" onclick="open_url_to_div('/saleretail/detail?id=<?php echo $no_invoice;?>')" class="btn-warning btn-sm mar-ed-button">Detail</a></td>
										</tr>	
									<?php 
										}
									?>
								
							</tbody>
						</table>
						</div>
					  </div>
				</div>
            </div>
          </div>
          <!-- page end-->
        </div>
        <!-- /row -->
      </section>
      <!-- /wrapper -->
    </section>
    <!--main content end-->
    <?php require('partial/main-footer.php');?> 
  </section>
   <!-- js placed at the end of the document so the pages load faster -->
  <script src="lib/jquery/jquery.min.js"></script>
  <script type="text/javascript" language="javascript" src="lib/advanced-datatable/js/jquery.js"></script>
  <script src="lib/bootstrap/js/bootstrap.min.js"></script>
  <script class="include" type="text/javascript" src="lib/jquery.dcjqaccordion.2.7.js"></script>
  <script src="lib/jquery.scrollTo.min.js"></script>
  <script src="lib/jquery.nicescroll.js" type="text/javascript"></script>
  <script type="text/javascript" language="javascript" src="lib/advanced-datatable/js/jquery.dataTables.js"></script>
  <script type="text/javascript" src="lib/advanced-datatable/js/DT_bootstrap.js"></script>
  <!--common script for all pages-->
  <script src="lib/common-scripts.js"></script>
  <!--script for this page-->
  <script type="text/javascript">
	function hapusdata(no_invoice){
			var r = confirm("Anda yakin akan menghapus data ini ?");
			if (r == true) {
					var url = "<?php echo $this->basePath; ?>/saleretail/hapusdata";
					var opt = {no_invoice:no_invoice}
					
					jQuery.get(url,opt, function(data) {	
						location.reload(true)
						//jQuery("div#example1").html(data);
						//jQuery("#page-content").html(data);
					})
					//open_url_to_div('<?php echo $this->baseUrl(); ?>/pengaduan/index');
					//location.reload(true)
			} else {
				close();
			}
		}
  </script>
</body>

</html>
