<?php require('partial/header.php'); ?>
<?php require('partial/menu.php'); ?>
<script>
	$(document).ready(function() {
		$('#dataTables-emp').dataTable({
			"bPaginate": true,
			"bLengthChange": true,
			"bFilter": true,
			"bInfo": true,
			"bAutoWidth": true
		});
	});
</script>
<!-- **********************************************************************************************************************************************************
        MAIN CONTENT
        *********************************************************************************************************************************************************** -->
<!--main content start-->
<?php $serialize_permission = unserialize($this->permission); ?>
<section id="main-content">
	<section class="wrapper" style="min-height:522px">
		<h3><i class="fa fa-angle-right"></i> Transaksi Penjualan Barang</h3>
		<div class="row mb">
			<!-- page start-->
			<div class="content-panel">
				<div class="adv-table">
					<div id="listprogram" align="center" class="col-xs-12">
						<br>
						<div id="page-content">
							<div class="form-group form-group-bottom" align="left">
								<?php if ($serialize_permission) {
									if (in_array('tambahSaleCentral', $serialize_permission)) { ?>
										<!-- <button class="right btn btn-success  btn-xs" onClick="open_url_to_div('/salecentral/tambahdata')"><i class="fa fa-plus"></i>&nbsp;&nbsp;Tambah Penjualan Barang</button>		 -->
										<a href="/salecentraltambah" class="btn btn-success btn-sm"><i class="fa fa-plus"></i>&nbsp;&nbsp;Tambah Penjualan Barang</a>
								<?php }
								} ?>
							</div>
							<div class="table-responsive">
								<table style="font-size:12px;" class="table table-striped table-bordered table-hover" id="dataTables-emp">
									<thead>
										<tr bgcolor="#4ECDC4">
											<th width="2%" style="text-align:center;">No</th>
											<th width="18%" style="text-align:center;">Nomor Invoice</th>
											<th width="4%" style="text-align:center;">Tanggal Invoice</th>
											<th width="4%" style="text-align:center;">Shipment</th>
											<th width="4%" style="text-align:center;">Sales</th>
											<th width="5%" style="text-align:center;">Total</th>
											<th width="2%" style="text-align:center;">%</th>
											<th width="5%" style="text-align:center;">Discount</th>
											<th width="5%" style="text-align:center;">Shipping</th>
											<th width="5%" style="text-align:center;">Grand Total</th>
											<th width="5%" style="text-align:center;">Pembayaran 1</th>
											<th width="5%" style="text-align:center;">Pembayaran 2</th>
											<th width="5%" style="text-align:center;">Sisa</th>
											<th width="5%" style="text-align:center;">Nama Penerima</th>
											<th width="5%" style="text-align:center;">Status Gudang</th>
											<th width="5%" style="text-align:center;">Status Bayar</th>
											<th width="5%" style="text-align:center;">Berat (Gr)</th>
											<th width="5%" style="text-align:center;">Nama Kurir</th>
											<th width="3%" style="text-align:center;">Edit</th>
											<th width="3%" style="text-align:center;">Hapus</th>
										</tr>
									</thead>
									<tbody>
										<?php
										for ($x = 0; $x < count($this->data); $x++) {

											$nomer			 = $x + 1;
											$no_invoice 	 = $this->data[$x]['no_invoice'];
											$kode_customer 	 = $this->data[$x]['kode_customer'];
											$shipment 		 = $this->data[$x]['shipment'];
											$nama_kurir 	 = $this->data[$x]['nama_kurir'];
											$total_berat 	 = number_format($this->data[$x]['total_berat'], 0, ",", ".");
											$total_biaya 	 = number_format($this->data[$x]['total_biaya'], 0, ",", ".");
											$diskon 		 = number_format($this->data[$x]['diskon'], 0, ",", ".");
											$biaya_kirim	 = number_format($this->data[$x]['biaya_kirim'], 0, ",", ".");
											$net_total	 	 = number_format($this->data[$x]['net_total'], 0, ",", ".");
											$jml_penerimaan  = number_format($this->data[$x]['jml_penerimaan'], 0, ",", ".");
											$jml_penerimaan2 = number_format($this->data[$x]['jml_penerimaan2'], 0, ",", ".");
											$jml_bayar 		 = number_format($this->data[$x]['jml_bayar'], 0, ",", ".");
											$sisa_bayar	 	 = number_format($this->data[$x]['sisa_bayar'], 0, ",", ".");
											$tgl_invoice	 = date_create($this->data[$x]['tgl_invoice']);
											$tgl_invoice	 = date_format($tgl_invoice, "d-m-Y");
											$nama_penerima 	 = $this->data[$x]['nama_penerima'];
											$alamat_penerima = $this->data[$x]['alamat_penerima'];
											$keterangan 	 = $this->data[$x]['keterangan'];
											$kode_sales 	 = $this->data[$x]['kode_sales'];
											$status 	 	 = $this->data[$x]['status'];
											$nama_customer   = '';
											$nama_sales  	 = '';

											if ($kode_customer) {
												$customer = $this->Salecentral_Service->getdatacustomerid($kode_customer);
												$nama_customer  = $customer[0]['nama_customer'];
											}

											if ($kode_sales) {
												$sales = $this->Salecentral_Service->getdatasalesid($kode_sales);
												$nama_sales  = $sales[0]['nama_sales'];
											}

											if ($sisa_bayar == '0') {
												$statusbayar = 'finished';
											} else {
												$statusbayar = 'un-finished';
											}
										?>
											<tr>
												<td align="center"><?php echo $nomer; ?></td>
												<td align="center"><?php echo $no_invoice; ?></td>
												<td align="center"><?php echo $tgl_invoice; ?></td>
												<td align="center"><?php echo $shipment; ?></td>
												<td align="center"><?php echo $nama_sales; ?></td>
												<td align="center"><?php echo $total_biaya; ?></td>
												<td align="center">-</td>
												<td align="center"><?php echo $diskon; ?></td>
												<td align="center"><?php echo $biaya_kirim; ?></td>
												<td align="center"><?php echo $net_total; ?></td>
												<td align="center"><?php echo $jml_penerimaan; ?></td>
												<td align="center"><?php echo $jml_penerimaan2; ?></td>
												<td align="center"><?php echo $sisa_bayar; ?></td>
												<td align="center"><?php echo $nama_penerima; ?></td>
												<td align="center">-</td>
												<td align="center"><?php echo $statusbayar; ?></td>
												<td align="center"><?php echo $total_berat; ?></td>
												<td align="center"><?php echo $nama_kurir; ?></td>
												<?php if ($status == 'Approve' or $status == 'Not-Approve') { ?>
													<td width="5%"><a href="#" title="Detail" onclick="open_url_to_div('/salecentral/detail?id=<?php echo $no_invoice; ?>')" class="btn-warning btn-sm mar-ed-button">Detail</a></td>
													<td width="5%"></td>
												<?php } else { ?>
													<td width="5%">
														<?php if ($serialize_permission) {
															if (in_array('editSaleCentral', $serialize_permission)) { ?>
																<a href="#" title="Edit" onclick="open_url_to_div('/salecentral/editdata?id=<?php echo $no_invoice; ?>')" class="btn-warning btn-sm mar-ed-button"><i class="fa fa-edit pad-ico-button"></i>Edit</a>
														<?php }
														} ?>
														<?php if ($serialize_permission) {
															if (in_array('approvalSaleCentral', $serialize_permission)) { ?>
																<a href="#" title="Approve" onclick="open_url_to_div('/salecentral/approval?id=<?php echo $no_invoice; ?>')" class="btn-warning btn-sm mar-ed-button"><i class="fa fa-edit pad-ico-button"></i>Appoval</a>
														<?php }
														} ?>
													</td>
													<td width="5%">
														<?php if ($serialize_permission) {
															if (in_array('hapusSaleCentral', $serialize_permission)) { ?>
																<a href="#" title="Hapus" onclick="hapusdata('<?php echo $no_invoice; ?>')" class="btn-danger btn-sm mar-ed-button"><i class="fa fa-trash-o pad-ico-button"></i>Hapus</a>
														<?php }
														} ?>
													</td>
												<?php } ?>

											</tr>
										<?php
										}
										?>

									</tbody>
								</table>
							</div>
						</div>
					</div>
				</div>
			</div>
			<!-- page end-->
		</div>
		<!-- /row -->
	</section>
	<!-- /wrapper -->
</section>
<!--main content end-->
<?php require('partial/main-footer.php'); ?>
</section>
<!-- js placed at the end of the document so the pages load faster -->
<script src="lib/jquery/jquery.min.js"></script>
<script type="text/javascript" language="javascript" src="lib/advanced-datatable/js/jquery.js"></script>
<script src="lib/bootstrap/js/bootstrap.min.js"></script>
<script class="include" type="text/javascript" src="lib/jquery.dcjqaccordion.2.7.js"></script>
<script src="lib/jquery.scrollTo.min.js"></script>
<script src="lib/jquery.nicescroll.js" type="text/javascript"></script>
<script type="text/javascript" language="javascript" src="lib/advanced-datatable/js/jquery.dataTables.js"></script>
<script type="text/javascript" src="lib/advanced-datatable/js/DT_bootstrap.js"></script>
<!--common script for all pages-->
<script src="lib/common-scripts.js"></script>
<!--script for this page-->
<script type="text/javascript">
	function hapusdata(no_invoice) {
		var r = confirm("Anda yakin akan menghapus data ini ?");
		if (r == true) {
			var url = "<?php echo $this->basePath; ?>/salecentral/hapusdata";
			var opt = {
				no_invoice: no_invoice
			}

			jQuery.get(url, opt, function(data) {
				location.reload(true)
				//jQuery("div#example1").html(data);
				//jQuery("#page-content").html(data);
			})
			//open_url_to_div('<?php echo $this->baseUrl(); ?>/pengaduan/index');
			//location.reload(true)
		} else {
			close();
		}
	}
</script>
</body>

</html>