<?php require('partial/header.php'); ?>
<?php require('partial/menu.php'); ?>
<link href="<?php echo $this->baseUrl(); ?>/css/select2.min.css" rel="stylesheet">
<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl(); ?>/css/sweetalert.css">
<style>
    body {
        font-family: Arial, Helvetica, sans-serif;
    }

    #backgroundPopup {

        display: none;
        position: fixed;
        _position: absolute;
        /* hack for internet explorer 6*/
        height: 100%;
        width: 100%;
        top: 0;
        left: 0;
        /*background: rgba(0, 0, 0, 0) url("../img/popup-bg.png");*/
        background: rgba(0, 0, 0, 0.85);
        border: 1px solid #cecece;
        z-index: 1040;
    }

    .box-popup1 {
        position: fixed;
        top: 30px;
        left: 30px;
        width: 40px;
        height: 30px;
    }

    #popupContact {

        display: none;
        position: fixed;
        _position: absolute;
        /* hack for internet explorer 6*/
        height: 100%;
        width: 90%;
        background: #acacac;
        z-index: 999999;
        font-size: 13px;
        overflow: auto;
        top: 2px;
        bottom: 10px;
        padding: 15px;
        margin: 1%;
    }

    #popupContact h1 {
        text-align: left;
        color: #6FA5FD;
        font-size: 22px;
        font-weight: bold;
        border-bottom: 1px dotted #D3D3D3;
        padding-bottom: 2px;
        margin-bottom: 20px;
    }

    #popupContact textarea {
        width: 90%;
        height: 100px;
    }

    #popupContactClose {
        font-size: 14px;
        line-height: 14px;
        right: 6px;
        top: 4px;
        position: absolute;
        color: #6fa5fd;
        font-weight: bold;
        width: 16px;
        cursor: pointer;
        display: block;
        background: url(../images/cross.png)
    }

    @media screen and (min-width: 768px) {
        .modal-center:before {
            display: inline-block;
            vertical-align: middle;
            content: " ";
            height: 100%;
        }
    }

    .modal-center .modal-dialog {
        display: inline-block;
        text-align: left;
        vertical-align: middle;
    }
</style>


<!-- **********************************************************************************************************************************************************
        MAIN CONTENT
        *********************************************************************************************************************************************************** -->
<!--main content start-->
<?php $serialize_permission = unserialize($this->permission); ?>
<section id="main-content">
    <section class="wrapper" style="min-height:522px">
        <h3><i class="fa fa-angle-right"></i> Transaksi Penjualan Barang</h3>
        <button @click="onClickButton" class="btn btn-primary">Send Data</button>
        <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#tesModal">Large modal</button>
        <button type="button" class="btn btn-warning button-test">Change Modal Content</button>
        <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#myModal">Otorisasi</button>
        <div class="row mb">
            <!-- page start-->
            <div class="content-panel">
                <div class="adv-table">
                    <div id="listprogram" align="center" class="col-xs-12">
                        <br>
                        <div id="page-content">

                            <!-- The Modal -->
                            <div id="myModal" class="modal modal-center">
                                <div class="modal-dialog">
                                    <!-- Modal content -->
                                    <div class="modal-content">
                                        <!-- <span class="close">&times;</span> -->
                                        <div class="modal-header">
                                            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                                            <p class="modal-title"><strong><em>*Otoritas dibutuhkan (untuk harga jual lebih rendah)!</em></strong></p>
                                        </div>
                                        <div class="modal-body">
                                            <table width="100%">
                                                <tr>
                                                    <td width="10%">
                                                        <font style="font-size:12px;font-weight:bold;">User ID</font>
                                                    </td>
                                                    <td width="1%">:</td>
                                                    <td>
                                                        <table>
                                                            <td>
                                                                <input name="user_id" id="user_id" type="text" maxlength="20" size="20" class="form-control input-sm" value="">
                                                                <input type="hidden" id="baris" name="baris" value="">
                                                            </td>
                                                            <td> &nbsp; <label id="user_id-error" for="user_id" class="error"></td>
                                                        </table>
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td>&nbsp;</td>
                                                </tr>
                                                <tr>
                                                    <td width="10%">
                                                        <font style="font-size:12px;font-weight:bold;">Password</font>
                                                    </td>
                                                    <td width="1%">:</td>
                                                    <td>
                                                        <table>
                                                            <td> <input name="password" id="password" type="password" maxlength="30" size="30" class="form-control input-sm" value=""> </td>
                                                            <td> &nbsp; <label id="password-error" for="password" class="error"></td>
                                                        </table>
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td>&nbsp;</td>
                                                </tr>
                                                <tr>
                                                    <td colspan="3">
                                                        <label id="gagal-error" for="password" class="error">
                                                    </td>
                                                </tr>
                                            </table><br>
                                            <button type="button" class="btn btn-theme03" onCLick="checkData()"><span class="fa fa-save"></span> &nbsp;Simpan Perubahan</button>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <form id="frm_postdata" name="frm_postdata" enctype="multipart/form-data" method="POST" autocomplete="off">
                                <input type="hidden" name="currentPage" id="currentPage" size="6" maxlength="6" value="<?php echo $this->numPage; ?>" class="inputbox2 narrowkey1"></input>
                                <?php
                                $seq = $this->seq;
                                //var_dump($seq);
                                $seq += 1;
                                $seq = str_pad($seq, 5, '0', STR_PAD_LEFT);
                                ?>
                                <input type="hidden" id='seq' name='seq' value='<?php echo $seq; ?>'>
                                <div id="popupview"></div>
                                <div class="panel">
                                    <fieldset class="panel-dt">
                                        <h4><i class="fa fa-angle-right"></i> Tambah Penjualan Barang</h4>
                                        <br>
                                        <div class="col-sm-12">
                                            <table width="100%">
                                                <tr>
                                                    <td width="10%">
                                                        <font style="font-size:12px;font-weight:bold;">Nomor Invoice</font>
                                                    </td>
                                                    <td width="1%">:</td>
                                                    <td>
                                                        <table>
                                                            <td> <input name="no_invoice" id="no_invoice" type="text" maxlength="50" size="30" class="form-control input-sm" value="SO/VH/<?php echo date("dmy H:i:s"); ?>/<?php echo $seq; ?>" readonly> </td>
                                                            <td> &nbsp; <label id="no_invoice-error" for="no_invoice" class="error"></td>
                                                        </table>
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td>&nbsp;</td>
                                                </tr>
                                                <tr>
                                                    <td width="10%">
                                                        <font style="font-size:12px;font-weight:bold;">Tanggal Invoice</font>
                                                    </td>
                                                    <td width="1%">:</td>
                                                    <td>
                                                        <table>
                                                            <td>
                                                                <input name="tgl_invoice" id="tgl_invoice" type="text" maxlength="50" size="20" class="form-control" value="">
                                                                <span class="input-group-btn add-on">
                                                                    <button class="btn btn-theme" type="button"><i class="fa fa-calendar"></i></button>
                                                                </span>
                                                            </td>
                                                            <td> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <label id="tgl_invoice-error" for="tgl_invoice" class="error"></td>
                                                        </table>
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td>&nbsp;</td>
                                                </tr>
                                                <tr>
                                                    <td width="10%">
                                                        <font style="font-size:12px;font-weight:bold;">Shipment</font>
                                                    </td>
                                                    <td width="1%">:</td>
                                                    <td>
                                                        <table>
                                                            <td>
                                                                <select id="shipment" name="shipment" class="form-control select_group product" width="15%" onclick="statuskurir(this)">
                                                                    <option value="">--Pilih Shipment--</option>
                                                                    <option value="COD">COD</option>
                                                                    <option value="Gojek">Gojek</option>
                                                                    <option value="Kurir">Kurir</option>
                                                                </select>
                                                            </td>
                                                            <td> &nbsp; <label id="shipment-error" for="shipment" class="error"></td>
                                                        </table>
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td>&nbsp;</td>
                                                </tr>
                                                <tr id='kurir'>
                                                    <td width="10%">
                                                        <font style="font-size:12px;font-weight:bold;">Nama Kurir</font>
                                                    </td>
                                                    <td width="1%">:</td>
                                                    <td>
                                                        <table>
                                                            <td> <input name="nama_kurir" id="nama_kurir" type="text" maxlength="30" size="30" class="form-control input-sm" value=""> </td>
                                                            <td> &nbsp; <label id="nama_kurir-error" for="nama_kurir" class="error"></td>
                                                        </table>
                                                    </td>
                                                </tr>
                                                <tr id='kurir2'>
                                                    <td>&nbsp;</td>
                                                </tr>
                                                <tr>
                                                    <td width="10%">
                                                        <font style="font-size:12px;font-weight:bold;">Nama Pelanggan</font>
                                                    </td>
                                                    <td width="1%">:</td>
                                                    <td>
                                                        <table>
                                                            <td>
                                                                <select id="kode_customer" name="kode_customer" class="form-control select_group product" width="20%" onchange="getSelectValue();">
                                                                    <option value="">--Pilih Customer--</option>
                                                                    <?php
                                                                    for ($x = 0; $x < count($this->customer); $x++) {
                                                                        $kode_customer = $this->customer[$x]['kode_customer'];
                                                                        $nama_customer = $this->customer[$x]['nama_customer'];
                                                                        $alamat_customer = $this->customer[$x]['alamat_customer'];
                                                                        $no_tlp = $this->customer[$x]['no_tlp'];
                                                                        $no_hp = $this->customer[$x]['no_hp'];
                                                                        $email = $this->customer[$x]['email'];
                                                                    ?>
                                                                        <option value="<?php echo $kode_customer; ?>,<?php echo $alamat_customer; ?>,<?php echo $no_tlp; ?>,<?php echo $no_hp; ?>,<?php echo $email; ?>"><?php echo $nama_customer; ?></option>
                                                                    <?php } ?>
                                                                </select>
                                                            </td>
                                                            <td> &nbsp;
                                                                <label id="kode_customer-error" for="kode_customer" class="error">
                                                                    <input name="kode_customer2" id="kode_customer2" type="hidden" value="" readonly>
                                                            </td>
                                                        </table>
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td>&nbsp;</td>
                                                </tr>
                                                <tr>
                                                    <td width="10%">
                                                        <font style="font-size:12px;font-weight:bold;">Alamat Pelanggan</font>
                                                    </td>
                                                    <td width="1%">:</td>
                                                    <td>
                                                        <table>
                                                            <td> <input name="alamat_customer" id="alamat_customer" type="text" maxlength="100" size="100" class="form-control input-sm" value="" readonly> </td>
                                                            <td> </td>
                                                        </table>
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td>&nbsp;</td>
                                                </tr>
                                                <tr>
                                                    <td width="10%">
                                                        <font style="font-size:12px;font-weight:bold;">Nomor Telepon</font>
                                                    </td>
                                                    <td width="1%">:</td>
                                                    <td>
                                                        <table>
                                                            <td> <input name="no_tlp" id="no_tlp" type="text" maxlength="20" size="15" class="form-control input-sm" value="" readonly> </td>
                                                            <td> </td>
                                                        </table>
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td>&nbsp;</td>
                                                </tr>
                                                <tr>
                                                    <td width="10%">
                                                        <font style="font-size:12px;font-weight:bold;">Nomor Handphone / WA</font>
                                                    </td>
                                                    <td width="1%">:</td>
                                                    <td>
                                                        <table>
                                                            <td> <input name="no_hp" id="no_hp" type="text" maxlength="20" size="15" class="form-control input-sm" value="" readonly> </td>
                                                            <td> </td>
                                                        </table>
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td>&nbsp;</td>
                                                </tr>
                                                <tr>
                                                    <td width="10%">
                                                        <font style="font-size:12px;font-weight:bold;">Email</font>
                                                    </td>
                                                    <td width="1%">:</td>
                                                    <td>
                                                        <table>
                                                            <td> <input name="email" id="email" type="text" maxlength="40" size="40" class="form-control input-sm" value="" readonly> </td>
                                                            <td> </td>
                                                        </table>
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td>&nbsp;</td>
                                                </tr>
                                                <tr>
                                                    <td width="10%">
                                                        <font style="font-size:12px;font-weight:bold;">Termin Hutang</font>
                                                    </td>
                                                    <td width="1%">:</td>
                                                    <td>
                                                        <table>
                                                            <td>
                                                                <select id="termin_hutang" name="termin_hutang" class="form-control select_group product" width="15%">
                                                                    <option value="">0 Hari</option>
                                                                    <option value="7">7 Hari</option>
                                                                    <option value="15">15 Hari</option>
                                                                    <option value="30">30 Hari</option>
                                                                </select>
                                                            </td>
                                                            <td> &nbsp; <label id="shipment-error" for="shipment" class="error"></td>
                                                        </table>
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td>&nbsp;</td>
                                                </tr>
                                            </table>
                                            <hr>
                                            <table class="table table-striped table-bordered">
                                                <thead style="background-color: #4ECDC4; color: #fff">
                                                    <tr>
                                                        <th>Jenis Barang</th>
                                                        <th>Kode Barang</th>
                                                        <th>Nama Barang</th>
                                                        <th>Berat (gr)</th>
                                                        <th>Booking</th>
                                                        <th>Stok</th>
                                                        <th>Harga Jual</th>
                                                        <th>Qty</th>
                                                        <th>Free</th>
                                                        <th>Subtotal</th>
                                                        <th></th>
                                                    </tr>
                                                </thead>
                                                <tbody>
                                                    <tr v-for="(finalGood, index) in finalSelectedGoods" is="selected-good" :key="index" :good="finalGood" :index="index" :ondelete="deleteFinalGood" :calculate="calculateFinalGoods"></tr>
                                                    <tr v-if="finalSelectedGoods.length < 1">
                                                        <td colspan="11" style="text-align: center;">Belum ada barang dipilih</td>
                                                    </tr>
                                                </tbody>
                                            </table>
                                            <!-- <div align='left'>
                                                <input type="button" class="right btn btn-success  btn-xs" style="font-weight:bold;" value="Tambah Barang" onclick="dataliquid()">
                                                <input type='hidden' name='counterx' id='counterx' value="0">
                                            </div>
                                            <br>
                                            <table width="100%" id="myTable" style="font-size:12px;" class="table-bordered">
                                                <tr bgcolor="#4ECDC4">
                                                    <td style="text-align:center;" width="15%">
                                                        <font style="font-size:12px;font-weight:bold;">Kode Barang</font>
                                                    </td>
                                                    <td style="text-align:center;" width="34%">
                                                        <font style="font-size:12px;font-weight:bold;">Nama Barang</font>
                                                    </td>
                                                    <td style="text-align:center;" width="6%">
                                                        <font style="font-size:12px;font-weight:bold;">Berat (gr)</font>
                                                    </td>
                                                    <td style="text-align:center;" width="5%">
                                                        <font style="font-size:12px;font-weight:bold;">Booking</font>
                                                    </td>
                                                    <td style="text-align:center;" width="5%">
                                                        <font style="font-size:12px;font-weight:bold;">Stok</font>
                                                    </td>
                                                    <td style="text-align:center;" width="10%">
                                                        <font style="font-size:12px;font-weight:bold;">Harga Jual</font>
                                                    </td>
                                                    <td style="text-align:center;" width="5%">
                                                        <font style="font-size:12px;font-weight:bold;">QTY</font>
                                                    </td>
                                                    <td style="text-align:center;" width="5%">
                                                        <font style="font-size:12px;font-weight:bold;">free</font>
                                                    </td>
                                                    <td style="text-align:center;" width="10%">
                                                        <font style="font-size:12px;font-weight:bold;">Sub Total</font>
                                                    </td>
                                                    <td style="text-align:center;" width="5%">
                                                        <font style="font-size:12px;font-weight:bold;">Action</font>
                                                    </td>
                                                </tr>
                                            </table> -->
                                            <table width="100%" id="myTable2">
                                                <tr>
                                                    <td>&nbsp;</td>
                                                </tr>
                                                <tr>
                                                    <td colspan='5' width="68%">&nbsp; <label id="total_berat-error" for="total_berat" class="error"></td>
                                                    <td width="13%">
                                                        </>
                                                        <font style="font-size:12px;font-weight:bold;">Total Berat</font>
                                                    </td>
                                                    <td width="19%">
                                                        </> <input type='text' class="form-control input-sm" name='total_berat' id='total_berat' value='0' readonly> </td>
                                                </tr>
                                                <tr>
                                                    <td>&nbsp;</td>
                                                </tr>
                                                <tr>
                                                    <td colspan='5' width="68%">&nbsp; <label id="total_biaya-error" for="total_biaya" class="error"></td>
                                                    <td width="13%">
                                                        </>
                                                        <font style="font-size:12px;font-weight:bold;">Total Biaya</font>
                                                    </td>
                                                    <td width="19%">
                                                        </> <input type='text' class="form-control input-sm" name='total_biaya' id='total_biaya' value='0' readonly> </td>
                                                </tr>
                                                <!-- <tr><td>&nbsp;</td></tr> -->

                                                <tr>
                                                    <td colspan='7' align="right"><label id="biaya_kirim-error" for="biaya_kirim" class="error"></td>
                                                </tr>
                                                <tr>
                                                    <td colspan='5'></td>
                                                    <td>
                                                        <font style="font-size:12px;font-weight:bold;">Diskon</font>
                                                    </td>
                                                    <td>
                                                        <input type='text' class="form-control input-sm" name='diskon' id='diskon' value='0' onkeyup='datadiskon()' style="width: 55%; display: inline">
                                                        <select class="form-control input-sm" id="jenis_diskon" name="jenis_diskon" style="width: 43%; display: inline">
                                                            <option value="nominal">Nominal</option>
                                                            <option value="persen">Persen (%)</option>
                                                        </select>
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td colspan='7' align="right"><label id="diskon-error" for="diskon" class="error"></td>
                                                </tr>
                                                <tr>
                                                    <td colspan='5'></td>
                                                    <td>
                                                        <font style="font-size:12px;font-weight:bold;">Sub Total</font>
                                                    </td>
                                                    <td> <input type='text' class="form-control input-sm" name='sub_total' id='sub_total' value='0' readonly> </td>
                                                </tr>
                                                <tr>
                                                    <td>&nbsp;</td>
                                                </tr>
                                                <tr>
                                                    <td colspan='5' align="right">&nbsp;</td>
                                                    <td>
                                                        <font style="font-size:12px;font-weight:bold;">Biaya Kirim</font>
                                                    </td>
                                                    <td> <input type='text' class="form-control input-sm" name='biaya_kirim' id='biaya_kirim' value='0' onkeyup='biaya()'> </td>
                                                </tr>
                                                <tr>
                                                    <td>&nbsp;</td>
                                                </tr>
                                                <tr>
                                                    <td colspan='5' align="right">&nbsp;</td>
                                                    <td>
                                                        <font style="font-size:12px;font-weight:bold;">Biaya Lainnya</font>
                                                    </td>
                                                    <td>
                                                        <input type='text' class="form-control input-sm" name='biaya_lain' id='biaya_lain' value='0' onkeyup='biayaLain()'>
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td>&nbsp;</td>
                                                </tr>
                                                <tr>
                                                    <td colspan='5' align="right">&nbsp;</td>
                                                    <td>
                                                        <font style="font-size:12px;font-weight:bold;"></font>
                                                    </td>
                                                    <td>
                                                        <input type='text' class="form-control input-sm" name='ket_biaya_lain' id='ket_biaya_lain' placeholder="Ket. Biaya Lainnya">
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td>&nbsp;</td>
                                                </tr>
                                                <tr>
                                                    <td colspan='5' align="right">&nbsp;</td>
                                                    <td>
                                                        <font style="font-size:12px;font-weight:bold;">Deposit Customer</font>
                                                    </td>
                                                    <td> <input type='text' class="form-control input-sm" name='deposit' id='deposit' value='0' onkeyup='onDepositChange()'> </td>
                                                </tr>
                                                <tr>
                                                    <td>&nbsp;</td>
                                                </tr>
                                                <tr>
                                                    <td colspan='5'></td>
                                                    <td>
                                                        <font style="font-size:12px;font-weight:bold;">Net Total</font>
                                                    </td>
                                                    <td> <input type='text' class="form-control input-sm" name='net_total' id='net_total' value='0' readonly> </td>
                                                </tr>
                                                <tr>
                                                    <td>&nbsp;</td>
                                                </tr>
                                                <tr>
                                                    <td colspan='5'></td>
                                                    <td width="10%">
                                                        <font style="font-size:12px;font-weight:bold;">Sumber Penerimaan 1</font>
                                                    </td>
                                                    <td>

                                                        <select id="metode_penerimaan" name="metode_penerimaan" class="form-control input-sm" width="15%">
                                                            <option value="0">--Pilih Sumber Dana--</option>
                                                            <?php
                                                            for ($x = 0; $x < count($this->rek); $x++) {
                                                                if ($this->rek[$x]['no_akun'] == 0) {
                                                                    $cek_rek = $this->rek[$x]['nama_akun'];
                                                                } else {
                                                                    $cek_rek = $this->rek[$x]['nama_akun'] . ' - ' . $this->rek[$x]['no_akun'] . ' (' . $this->rek[$x]['nama_cabang_pembuka'] . ')';
                                                                }


                                                                $id = $this->rek[$x]['id'];
                                                            ?>
                                                                <option value="<?php echo $id; ?>"><?php echo $cek_rek; ?></option>
                                                            <?php } ?>
                                                        </select>

                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td colspan='7' align="right"><label id="metode_penerimaan-error" for="metode_penerimaan" class="error"></td>
                                                </tr>
                                                <tr>
                                                    <td colspan='5'></td>
                                                    <td>
                                                        <font style="font-size:12px;font-weight:bold;">Rp</font>
                                                    </td>
                                                    <td> <input type='text' class="form-control input-sm" name='jml_penerimaan' id='jml_penerimaan' value='0' onkeyup='jumlahdp()'> </td>
                                                </tr>
                                                <tr>
                                                    <td colspan='7' align="right"><label id="jml_penerimaan-error" for="jml_penerimaan" class="error"></td>
                                                </tr>
                                                <tr>
                                                    <td colspan='5'></td>
                                                    <td width="10%">
                                                        <font style="font-size:12px;font-weight:bold;">Sumber Penerimaan 2</font>
                                                    </td>
                                                    <td>

                                                        <select id="metode_penerimaan2" name="metode_penerimaan2" class="form-control input-sm" width="15%">
                                                            <option value="0">--Pilih Sumber Dana--</option>
                                                            <?php
                                                            for ($x = 0; $x < count($this->rek); $x++) {
                                                                if ($this->rek[$x]['no_akun'] == 0) {
                                                                    $cek_rek = $this->rek[$x]['nama_akun'];
                                                                } else {
                                                                    $cek_rek = $this->rek[$x]['nama_akun'] . ' - ' . $this->rek[$x]['no_akun'] . ' (' . $this->rek[$x]['nama_cabang_pembuka'] . ')';
                                                                }


                                                            ?>

                                                                <option value="<?php echo $id; ?>"><?php echo $cek_rek; ?></option>
                                                            <?php } ?>
                                                        </select>

                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td colspan='7' align="right"><label id="metode_penerimaan2-error" for="metode_penerimaan2" class="error"></td>
                                                </tr>
                                                <tr>
                                                    <td colspan='5'></td>
                                                    <td>
                                                        <font style="font-size:12px;font-weight:bold;">Rp</font>
                                                    </td>
                                                    <td> <input type='text' class="form-control input-sm" name='jml_penerimaan2' id='jml_penerimaan2' value='0' onkeyup='jumlahdp()'> </td>
                                                </tr>
                                                <tr>
                                                    <td colspan='7' align="right"><label id="jml_penerimaan2-error" for="jml_penerimaan2" class="error"></td>
                                                </tr>
                                                <tr>
                                                    <td colspan='5'></td>
                                                    <td>
                                                        <font style="font-size:12px;font-weight:bold;">Jumlah Pembayaran</font>
                                                    </td>
                                                    <td> <input type='text' class="form-control input-sm" name='jml_bayar' id='jml_bayar' value='0' readonly> </td>
                                                </tr>
                                                <tr>
                                                    <td>&nbsp;</td>
                                                </tr>
                                                <tr>
                                                    <td colspan='5'></td>
                                                    <td>
                                                        <font style="font-size:12px;font-weight:bold;">Sisa Pembayaran</font>
                                                    </td>
                                                    <td> <input type='text' class="form-control input-sm" name='sisa_bayar' id='sisa_bayar' value='0' readonly> </td>
                                                </tr>
                                                <tr>
                                                    <td>&nbsp;</td>
                                                </tr>
                                                <tr>
                                                    <td colspan='5'></td>
                                                    <td>
                                                        <font style="font-size:12px;font-weight:bold;">Nama Penerima</font>
                                                    </td>
                                                    <td> <input type='text' class="form-control input-sm" name='nama_penerima' id='nama_penerima' value=''> </td>
                                                </tr>
                                                <tr>
                                                    <td colspan='7' align="right"><label id="nama_penerima-error" for="nama_penerima" class="error"></td>
                                                </tr>
                                                <tr>
                                                    <td colspan='5'></td>
                                                    <td>
                                                        <font style="font-size:12px;font-weight:bold;">Alamat Penerima</font>
                                                    </td>
                                                    <td> <textarea class="form-control input-sm" name='alamat_penerima' id='alamat_penerima'></textarea></td>
                                                </tr>
                                                <tr>
                                                    <td colspan='7' align="right"><label id="alamat_penerima-error" for="alamat_penerima" class="error"></td>
                                                </tr>
                                                <tr>
                                                    <td colspan='5'></td>
                                                    <td>
                                                        <font style="font-size:12px;font-weight:bold;">Keterangan</font>
                                                    </td>
                                                    <td> <input type='text' class="form-control input-sm" name='keterangan' id='keterangan' value=''> </td>
                                                </tr>
                                                <tr>
                                                    <td colspan='7' align="right"><label id="keterangan-error" for="keterangan" class="error"></td>
                                                </tr>
                                            </table>
                                        </div>
                                    </fieldset>
                                </div>

                        </div>
                    </div>

                    <div class="col-lg-12">
                        <div class="form-group form-group-bottom" align="right">
                            <input type="hidden" id="proses" name="proses" value="<?php echo $this->proses ?>">
                            <br><br>

                            <a href="salecentral">
                                <button type="button" class="btn btn-theme02">
                                    <span class="fa fa-backward"></span> &nbsp;Kembali
                                </button>
                            </a>
                            <button type="button" class="btn btn-theme03" onCLick="PostData()">
                                <span class="fa fa-save"></span> &nbsp;Simpan
                            </button>

                        </div>
                    </div>
                    </form>
                </div>
            </div>
        </div>
        </div>
        <!-- page end-->
        </div>
        <!-- /row -->
    </section>
    <!-- /wrapper -->
    <!-- Modal -->
    <div class="modal" id="tesModal">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h4 class="modal-title" id="myModalLabel">Pilih barang</h4>
                </div>
                <div class="modal-body">
                    <div style="padding-top: 1em; ">
                        <div class="row" style="margin-bottom: 2em;">
                            <div class="col-md-6">
                                <select v-model="shownContent" class="form-control">
                                    <option value="liquid">Liquids</option>
                                    <option value="device">Devices</option>
                                    <option value="accessories">Accesories</option>
                                    <option value="atomizer">Atomizer</option>
                                </select>
                            </div>
                        </div>
                        <div style="display: none; overflow-x: auto;" :style="(shownContent == 'liquid') ? { display: 'block' } : ''">
                            <table class="table table-striped table-responsive use-datatable">
                                <thead>
                                    <tr>
                                        <th></th>
                                        <th>Kode Liquid</th>
                                        <th>Nama Liquid</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <?php foreach ($this->liquids as $liquid) : ?>
                                        <tr>
                                            <td style="text-align: center;"><input type="checkbox" :value='{...JSON.parse(`<?= json_encode($liquid) ?>`), qty: 1, free: 0, subTotal: JSON.parse(`<?= json_encode($liquid) ?>`).hj_retail}' v-model="tempSelectedGoods"></td>
                                            <td><?= $liquid['kode_barang'] ?></td>
                                            <td><?= $liquid['nama_barang'] ?></td>
                                        </tr>
                                    <?php endforeach; ?>
                                </tbody>
                            </table>
                        </div>
                        <div style="display: none; overflow-x: auto;" :style="(shownContent == 'device') ? { display: 'block' } : ''">
                            <table class="table table-striped table-responsive use-datatable">
                                <thead>
                                    <tr>
                                        <th></th>
                                        <th>Kode Device</th>
                                        <th>Nama Device</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <?php foreach ($this->devices as $device) : ?>
                                        <tr>
                                            <td style="text-align: center;"><input type="checkbox" :value='{...JSON.parse(`<?= json_encode($device) ?>`), qty: 1, free: 0, subTotal: JSON.parse(`<?= json_encode($device) ?>`).hj_retail}' v-model="tempSelectedGoods"></td>
                                            <td><?= $device['kode_device'] ?></td>
                                            <td><?= $device['nama_device'] ?></td>
                                        </tr>
                                    <?php endforeach; ?>
                                </tbody>
                            </table>
                        </div>
                        <div style="display: none; overflow-x: auto;" :style="(shownContent == 'atomizer') ? { display: 'block' } : ''">
                            <table class="table table-striped table-responsive use-datatable">
                                <thead>
                                    <tr>
                                        <th></th>
                                        <th>Kode Atomizer</th>
                                        <th>Nama Atomizer</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <?php foreach ($this->atomizers as $atomizer) : ?>
                                        <tr>
                                            <td style="text-align: center;"><input type="checkbox" :value='{...JSON.parse(`<?= json_encode($atomizer) ?>`), qty: 1, free: 0, subTotal: JSON.parse(`<?= json_encode($atomizer) ?>`).hj_retail}' v-model="tempSelectedGoods"></td>
                                            <td><?= $atomizer['kode_atomizer'] ?></td>
                                            <td><?= $atomizer['nama_atomizer'] ?></td>
                                        </tr>
                                    <?php endforeach; ?>
                                </tbody>
                            </table>
                        </div>
                        <div style="display: none; overflow-x: auto;" :style="(shownContent == 'accessories') ? { display: 'block' } : ''">
                            <table class="table table-striped table-responsive use-datatable">
                                <thead>
                                    <tr>
                                        <th></th>
                                        <th>Kode Aksesoris</th>
                                        <th>Nama Aksesoris</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <?php foreach ($this->accessories as $accessories) : ?>
                                        <tr>
                                            <td style="text-align: center;"><input type="checkbox" :value='{...JSON.parse(`<?= json_encode($accessories) ?>`), qty: 1, free: 0, subTotal: JSON.parse(`<?= json_encode($accessories) ?>`).hj_retail}' v-model="tempSelectedGoods"></td>
                                            <td><?= $accessories['kode_aksesoris'] ?></td>
                                            <td><?= $accessories['nama_aksesoris'] ?></td>
                                        </tr>
                                    <?php endforeach; ?>
                                </tbody>
                            </table>
                        </div>
                    </div>
                    <div style="margin: 1.25em 0;">
                        <table class="table table-striped table-bordered" v-if="tempSelectedGoods.length">
                            <thead>
                                <tr>
                                    <th>Jenis Barang</th>
                                    <th>Kode Barang</th>
                                    <th>Nama Barang</th>
                                    <th></th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr v-for="(good, index) in tempSelectedGoods">
                                    <td v-if="good.kode_barang">Liquid</td>
                                    <td v-else-if="good.kode_device">Device</td>
                                    <td v-else-if="good.kode_aksesoris">Aksesoris</td>
                                    <td v-else-if="good.kode_atomizer">Atomizer</td>
                                    <td>{{ good.kode_barang || good.kode_device || good.kode_aksesoris || good.kode_atomizer }}</td>
                                    <td>{{ good.nama_barang || good.nama_device || good.nama_aksesoris || good.nama_atomizer }}</td>
                                    <td style="text-align: center;"><a href="#" style="color: red;" @click.prevent="unselectGood(index)"><i class="fa fa-times"></i></a></td>
                                </tr>
                            </tbody>
                        </table>
                        <p style="text-align: center;" v-if="tempSelectedGoods.length < 1"><strong><em>Belum ada barang dipilih</em></strong></p>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    <button type="button" @click="setFinalGoods" class="btn btn-primary">Tambah</button>
                </div>
            </div>
        </div>
    </div>
</section>
<!--main content end-->
<?php require('partial/main-footer.php'); ?>

</section>




<!-- js placed at the end of the document so the pages load faster -->
<!-- <script src="lib/jquery/jquery.min.js"></script> -->
<!-- <script src="https://cdn.jsdelivr.net/npm/jquery@3.6.0/dist/jquery.min.js"></script> -->
<!-- <script src="https://cdn.jsdelivr.net/npm/jquery@1.9.1/jquery.min.js"></script> -->
<!-- <script type="text/javascript" language="javascript" src="lib/advanced-datatable/js/jquery.js"></script> -->
<script src="lib/bootstrap/js/bootstrap.min.js"></script>
<script class="include" type="text/javascript" src="lib/jquery.dcjqaccordion.2.7.js"></script>
<script src="lib/jquery.scrollTo.min.js"></script>
<script src="lib/jquery.nicescroll.js" type="text/javascript"></script>
<script type="text/javascript" language="javascript" src="lib/advanced-datatable/js/jquery.dataTables.js"></script>
<script type="text/javascript" src="lib/advanced-datatable/js/DT_bootstrap.js"></script>
<script src="<?php echo $this->baseUrl(); ?>/lib/select2.full.min.js"></script>
<script src="<?php echo $this->baseUrl(); ?>/lib/jquery-ui-1.9.2.custom.min.js"></script>
<!--common script for all pages-->
<script src="lib/common-scripts.js"></script>
<!--script for this page-->
<script src="<?php echo $this->baseUrl(); ?>/lib/jquery.form.js"></script>

<script src="<?php echo $this->baseUrl(); ?>/lib/sweetalert.min.js"></script>
<!-- <script src="<?php echo $this->baseUrl(); ?>/lib/jquery.scrollTo.min.js"></script>
<script src="<?php echo $this->baseUrl(); ?>/lib/jquery.nicescroll.js" type="text/javascript"></script> -->
<script src="https://cdn.jsdelivr.net/npm/vue@2/dist/vue.js"></script>
<script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
<script>
    $(function() {
        // $('#table-test').DataTable({
        //     "destroy": true
        // });

        let table = $('.use-datatable').dataTable({
            "sorting": false,
            "destroy": true
        });

        // console.log(table);
    })

    Vue.component('selected-good', {
        props: ['good', 'index', 'ondelete', 'calculate'],
        template: `
        <tr>
            <td v-if="good.kode_barang">Liquid</td>
            <td v-else-if="good.kode_device">Device</td>
            <td v-else-if="good.kode_aksesoris">Aksesoris</td>
            <td v-else-if="good.kode_atomizer">Atomizer</td>
            <td>{{ good.kode_barang || good.kode_device || good.kode_aksesoris || good.kode_atomizer }}</td>
            <td>{{ good.nama_barang || good.nama_device || good.nama_aksesoris || good.nama_atomizer }}</td>
            <td>{{ good.berat }}</td>
            <td>{{ good.on_hand }}</td>
            <td>{{ good.stok_pusat }}</td>
            <td><input type="text" @input="calculate(good)" v-model="good.hj_retail" class="form-control input-sm" style="text-align: right" /></td>
            <td><input type="text" @input="calculate(good)" v-model="good.qty" class="form-control input-sm" /></td>
            <td><input type="text" @input="calculate(good)" v-model="good.free" class="form-control input-sm" /></td>
            <td><input type="text" v-model="good.subTotal" class="form-control input-sm" style="text-align: right" readonly /></td>
            <td style="text-align: center;"><a href="#" style="color: red;" @click.prevent="ondelete(index)"><i class="fa fa-times"></i></a></td>
        </tr>
        `
    })

    let app = new Vue({
        el: '#main-content',
        data: {
            name: 'Reza',
            shownContent: 'liquid',
            tempSelectedGoods: [],
            finalSelectedGoods: [],
        },

        methods: {
            onClickButton: function() {
                swal({
                    title: 'Order Sukses !',
                    text: 'Auto Close...',
                    icon: 'success',
                    timer: 4000,
                    showConfirmButton: false,
                })
            },
            selectGood: function(e, good) {
                console.log(e);
                this.tempSelectedGoods.push(Object.assign(good, {
                    qty: 1,
                    free: 0,
                    subTotal: parseInt(good.hj_retail) * 1
                }));
            },
            unselectGood: function(index) {
                this.tempSelectedGoods.splice(index, 1);
            },
            setFinalGoods: function() {
                this.finalSelectedGoods = [...this.finalSelectedGoods, ...this.tempSelectedGoods];
                $('#tesModal').modal('hide');
            },
            deleteFinalGood: function(index) {
                this.finalSelectedGoods.splice(index, 1);
            },
            calculateFinalGoods: function(item) {
                item.subTotal = Number(item.qty) * Number(item.hj_retail);
                // let stok = item.stok_pusat;
                // item.stok_pusat = Number(item.stok_pusat) - Number(item.qty) - Number(item.free);
            }
        }
    })
</script>
<script>
    $(function() {
        $('#tesModal').on('hidden.bs.modal', function(e) {
            app.$data.tempSelectedGoods = [];
        })
    })
</script>
<script>
    $("#kurir").hide();
    $("#kurir2").hide();

    function statuskurir(nilai) {
        var nilai = nilai.value;
        if (nilai == 'Kurir') {
            $("#kurir").show();
            $("#kurir2").show();
        } else {
            $("#kurir").hide();
            $("#kurir2").hide();
        }
    }

    $("#transfer").hide();
    $("#transfer2").hide();

    function loadPopup() {
        var popupStatus = 0;
        if (popupStatus == 0) {
            jQuery("#backgroundPopup").css({
                "opacity": "1"
            });
            jQuery("#backgroundPopup").fadeIn("fast");
            jQuery("#popupContact").fadeIn("fast");
            popupStatus = 1
        }
    }

    function centerPopup() {
        var windowWidth = document.documentElement.clientWidth;
        var windowHeight = "1000%";
        var popupHeight = jQuery("#popupContact").height();
        var popupWidth = jQuery("#popupContact").width();
    }

    function closePopup() {
        document.getElementById('popupContact').style.display = "none";
        document.getElementById('backgroundPopup').style.display = "none";
    }

    function disablePopup() {
        document.getElementById('popupContact').style.display = "none";
        document.getElementById('backgroundPopup').style.display = "none";
    }

    function pilih_barang(x) {
        var nilai = x.value;
        if (nilai == 'Liquid') {
            dataliquid();
        } else if (nilai == 'Device') {
            datadevice();
        } else if (nilai == 'Aksesoris') {
            dataaksesoris();
        } else if (nilai == 'Atomizer') {
            dataatomizer();
        }
    }

    function dataliquid() {
        var seq = document.getElementById('seq').value;

        //alert('maintain'); 

        var url = '<?php echo $this->basePath; ?>/salecentral/dataliquid';
        var opt = {
            seq: seq
        };

        jQuery.get(url, opt, function(data) {
            jQuery("#popupview").html(data);
            centerPopup();
            loadPopup();
        })
    }

    function datadevice() {
        var seq = document.getElementById('seq').value;

        //alert('maintain'); 

        var url = '<?php echo $this->basePath; ?>/salecentral/datadevice';
        var opt = {
            seq: seq
        };

        jQuery.get(url, opt, function(data) {
            jQuery("#popupview").html(data);
            centerPopup();
            loadPopup();
        })
    }

    function dataaksesoris() {
        var seq = document.getElementById('seq').value;

        //alert('maintain'); 

        var url = '<?php echo $this->basePath; ?>/salecentral/dataaksesoris';
        var opt = {
            seq: seq
        };

        jQuery.get(url, opt, function(data) {
            jQuery("#popupview").html(data);
            centerPopup();
            loadPopup();
        })
    }

    function dataatomizer() {
        var seq = document.getElementById('seq').value;

        //alert('maintain'); 

        var url = '<?php echo $this->basePath; ?>/salecentral/dataatomizer';
        var opt = {
            seq: seq
        };

        jQuery.get(url, opt, function(data) {
            jQuery("#popupview").html(data);
            centerPopup();
            loadPopup();
        })
    }

    function getSelectValue() {
        var selectedValue = document.getElementById("kode_customer").value;
        var res = selectedValue.split(",");
        var kode_customer = res[0];
        var alamat = res[1];
        var no_tlp = res[2];
        var no_hp = res[3];
        var email = res[4];

        document.getElementById("alamat_customer").value = alamat;
        document.getElementById("no_tlp").value = no_tlp;
        document.getElementById("no_hp").value = no_hp;
        document.getElementById("email").value = email;
        document.getElementById("kode_customer2").value = kode_customer;
    }


    function PostData() {
        //alert('Testing2');
        $("#frm_postdata").ajaxSubmit(post_data);
    }

    var post_data = {
        target: '',
        beforeSubmit: function() {
            var tgl_invoice = document.getElementById("tgl_invoice").value;
            var shipment = document.getElementById('shipment').value;
            var kode_customer = document.getElementById('kode_customer').value;
            var nama_kurir = document.getElementById('nama_kurir').value;
            /* var total		 	  = document.getElementById('total').value;
            var biaya_kirim		  = document.getElementById('biaya_kirim').value;
            var diskon		 	  = document.getElementById('diskon').value;
            var jml_bayar_dp	  = document.getElementById('jml_bayar_dp').value;
            var metode_bayar2	  = document.getElementById('metode_bayar2').value;
            var no_rek	  		  = document.getElementById('no_rek').value; */

            if (!tgl_invoice) {
                document.getElementById('tgl_invoice-error').innerHTML = "<span style='color: red;'>Tanggal Invoice Harus Diisi.</span>";
                document.getElementById('tgl_invoice').focus();
                // exit;
                return false;
            } else document.getElementById('tgl_invoice-error').innerHTML = '';

            if (shipment == '') {
                document.getElementById('shipment-error').innerHTML = "<span style='color: red;'>Shipment Harus Dipilih.</span>";
                document.getElementById('shipment').focus();
                // exit;
                return false;
            } else document.getElementById('shipment-error').innerHTML = '';

            if (shipment == 'Kurir') {
                if (!nama_kurir) {
                    document.getElementById('nama_kurir-error').innerHTML = "<span style='color: red;'>Nama Kurir Harus Diisi.</span>";
                    document.getElementById('nama_kurir').focus();
                    // exit;
                    return false;
                } else document.getElementById('nama_kurir-error').innerHTML = '';
            }

            if (kode_customer == '') {
                document.getElementById('kode_customer-error').innerHTML = "<span style='color: red;'>Nama Pelanggan Harus Dipilih.</span>";
                document.getElementById('kode_customer').focus();
                // exit;
                return false;
            } else document.getElementById('kode_customer-error').innerHTML = '';

            return true;

            /* if (!biaya_kirim) {
            	document.getElementById('biaya_kirim-error').innerHTML ="<span style='color: red;'>Biaya Kirim Harus Diisi.</span>";
            	document.getElementById('biaya_kirim').focus();
            	exit;
            }else document.getElementById('biaya_kirim-error').innerHTML ='';

            if (!diskon) {
            	document.getElementById('diskon-error').innerHTML ="<span style='color: red;'>Diskon Harus Diisi.</span>";
            	document.getElementById('diskon').focus();
            	exit;
            }else document.getElementById('diskon-error').innerHTML ='';

            if (!jml_bayar_dp) {
            	document.getElementById('jml_bayar_dp-error').innerHTML ="<span style='color: red;'>Jumlah Bayar DP Harus Diisi.</span>";
            	document.getElementById('jml_bayar_dp').focus();
            	exit;
            }else document.getElementById('jml_bayar_dp-error').innerHTML ='';

            if (metode_bayar2=='0') {
            	document.getElementById('metode_bayar2-error').innerHTML ="<span style='color: red;'>Metode Bayar Harus Dipilih.</span>";
            	document.getElementById('metode_bayar2').focus();
            	exit;
            }else document.getElementById('metode_bayar2-error').innerHTML ='';

            if(metode_bayar2 == 'Transfer'){
            	if (no_rek=='0') {
            		document.getElementById('no_rek-error').innerHTML ="<span style='color: red;'>Bank Transfer Harus Dipilih.</span>";
            		document.getElementById('no_rek').focus();
            		exit;
            	}else document.getElementById('no_rek-error').innerHTML ='';
            } */

        },
        success: function() {
            swal({
                title: 'Order Sukses !',
                text: 'Auto Close...',
                icon: 'success',
                timer: 4000,
                showConfirmButton: false,
            })
            location.href = "#";
            location.reload(true)
        },
        url: '<?php echo $this->baseUrl(); ?>/salecentral/kirimdata',
        type: 'post',
        resetForm: false
    };

    function isNumber(evt) {
        var iKeyCode = (evt.which) ? evt.which : evt.keyCode
        if (iKeyCode != 46 && iKeyCode > 31 && (iKeyCode < 48 || iKeyCode > 57))
            return false;

        return true;
    }

    function closeDetil() {
        document.getElementById('popupContact').style.display = "none";
        disablePopup();
    }

    function deleterow(button, rows) {
        var x = button.parentNode.parentNode.rowIndex;

        var total_berat = document.getElementById("total_berat").value;
        var total_berat2 = total_berat.replaceAll(".", "");
        var sub_total_berat = document.getElementById("sub_total_berat" + rows).value;
        var sub_total_berat2 = sub_total_berat.replaceAll(".", "");

        var hitung_total_berat = parseInt(total_berat2) - parseInt(sub_total_berat2);
        var hitung_total_berat2 = hitung_total_berat.toString().replaceAll(/(\d)(?=(\d\d\d)+(?!\d))/g, "$1.");
        document.getElementById("total_berat").value = hitung_total_berat2;

        var total_biaya = document.getElementById("total_biaya").value;
        var total_biaya2 = total_biaya.replaceAll(".", "");
        var sub_total = document.getElementById("sub_total" + rows).value;
        var sub_total2 = sub_total.replaceAll(".", "");

        var biaya_kirim = document.getElementById("biaya_kirim").value;
        var biaya_kirim2 = biaya_kirim.replaceAll(".", "");
        var diskon = document.getElementById("diskon").value;
        var diskon2 = diskon.replaceAll(".", "");

        if (document.getElementById("jenis_diskon").value == 'persen') {
            diskon2 = (parseInt(diskon2) / 100) * parseInt(total_biaya2);
        }

        var jml_bayar = document.getElementById("jml_bayar").value;
        var jml_bayar2 = jml_bayar.replaceAll(".", "");

        var hitung_total = parseInt(total_biaya2) - parseInt(sub_total2)
        var hitung_total2 = hitung_total.toString().replaceAll(/(\d)(?=(\d\d\d)+(?!\d))/g, "$1.");
        document.getElementById("total_biaya").value = hitung_total2;

        var hitung_sub_total = hitung_total - parseInt(diskon2);
        var hitung_sub_total2 = hitung_sub_total.toString().replaceAll(/(\d)(?=(\d\d\d)+(?!\d))/g, "$1.");
        document.getElementById("sub_total").value = hitung_sub_total2;

        var biaya_lain = document.getElementById("biaya_lain").value;
        var biaya_lain2 = biaya_lain.replaceAll(".", "");

        var deposit = document.getElementById("deposit").value;
        var deposit2 = deposit.replaceAll(".", "");

        var hitung_net_total = hitung_sub_total + parseInt(biaya_kirim2) + parseInt(biaya_lain2) - parseInt(deposit2);
        var hitung_net_total2 = hitung_net_total.toString().replaceAll(/(\d)(?=(\d\d\d)+(?!\d))/g, "$1.");
        document.getElementById("net_total").value = hitung_net_total2;

        var hitung_sisa_bayar = hitung_net_total - parseInt(jml_bayar2);
        var hitung_sisa_bayar2 = hitung_sisa_bayar.toString().replaceAll(/(\d)(?=(\d\d\d)+(?!\d))/g, "$1.");
        document.getElementById("sisa_bayar").value = hitung_sisa_bayar2;

        document.getElementById("myTable").deleteRow(x);

    }

    function jual(button) {
        var x = button;

        var modal = document.getElementById("myModal");
        var span = document.getElementsByClassName("close")[0];

        var total_berat = document.getElementById("total_berat").value;
        var total_berat2 = total_berat.replaceAll(".", "");
        var sub_total_berat = document.getElementById("sub_total_berat" + x).value;
        var sub_total_berat2 = sub_total_berat.replaceAll(".", "");

        var hitung_total_berat = parseInt(total_berat2) - parseInt(sub_total_berat2);

        var total_biaya = document.getElementById("total_biaya").value;
        var total_biaya2 = total_biaya.replaceAll(".", "");
        var sub_total = document.getElementById("sub_total" + x).value;
        var sub_total2 = sub_total.replaceAll(".", "");
        var sub_total3 = sub_total2.toString().replaceAll(/(\d)(?=(\d\d\d)+(?!\d))/g, "$1.");
        document.getElementById("sub_total" + x).value = sub_total3;

        var hitung_total = parseInt(total_biaya2) - parseInt(sub_total2);
        var qty = document.getElementById("qty" + x).value;

        var hj_retail = document.getElementById("hj_retail" + x).value;
        var hj_retail2 = hj_retail.replaceAll(".", "");
        var hj_retail3 = hj_retail2.toString().replaceAll(/(\d)(?=(\d\d\d)+(?!\d))/g, "$1.");
        document.getElementById("hj_retail" + x).value = hj_retail3;

        var hj_retail_lama = document.getElementById("hj_retail_lama" + x).value;
        var hj_retail_lama2 = hj_retail_lama.replaceAll(".", "");
        var hj_retail_lama3 = hj_retail_lama2.toString().replaceAll(/(\d)(?=(\d\d\d)+(?!\d))/g, "$1.");

        var otorisasi_harga = document.getElementById("otorisasi_harga" + x).value;

        if (parseInt(hj_retail2) < parseInt(hj_retail_lama2)) {
            //alert('harga jual baru tidak boleh lebih rendah dari harga jual awal !');

            if (otorisasi_harga == '1') {
                modal.style.display = "block";
            }

            span.onclick = function() {
                modal.style.display = "none";

                document.getElementById("hj_retail" + x).value = hj_retail_lama3;
                var hj_retail = document.getElementById("hj_retail" + x).value;
                var hj_retail2 = hj_retail.replaceAll(".", "");

                var kali = qty * hj_retail2;
                var kali2 = kali.toString().replaceAll(/(\d)(?=(\d\d\d)+(?!\d))/g, "$1.");

                document.getElementById("sub_total" + x).value = kali2;

                var berat = document.getElementById("berat" + x).value;
                var berat2 = berat.replaceAll(".", "");

                var free = document.getElementById("free" + x).value;
                var free2 = free.replaceAll(".", "");

                var hitung_qty_berat = (parseInt(qty) + parseInt(free2)) * parseInt(berat2);
                var hitung_qty_berat2 = hitung_qty_berat.toString().replaceAll(/(\d)(?=(\d\d\d)+(?!\d))/g, "$1.");
                document.getElementById("sub_total_berat" + x).value = hitung_qty_berat2;

                var on_hands = document.getElementById("on_hands" + x).value;
                var on_hands2 = on_hands.replaceAll(".", "");


                var hitung_on_hand = parseInt(on_hands2) + parseInt(qty) + parseInt(free2);
                var hitung_on_hand2 = hitung_on_hand.toString().replaceAll(/(\d)(?=(\d\d\d)+(?!\d))/g, "$1.");
                document.getElementById("on_hand" + x).value = hitung_on_hand2;

                var stok_gudang = document.getElementById("stok_gudang" + x).value;
                var stok_gudang2 = stok_gudang.replaceAll(".", "");

                if (hitung_on_hand > stok_gudang2) {
                    alert('Maksimal qty adalah');
                    var stok_gudang3 = stok_gudang2.toString().replaceAll(/(\d)(?=(\d\d\d)+(?!\d))/g, "$1.");
                    document.getElementById("on_hand" + x).value = stok_gudang3;
                    var on_hands = document.getElementById("on_hands" + x).value;
                    var max_qty = parseInt(stok_gudang2) - parseInt(on_hands);
                    document.getElementById("qty" + x).value = max_qty;

                    var kali = max_qty * hj_retail2;
                    var kali2 = kali.toString().replaceAll(/(\d)(?=(\d\d\d)+(?!\d))/g, "$1.");
                    document.getElementById("sub_total" + x).value = kali2;

                    var hitung_qty_berat = max_qty * berat2;
                    var hitung_qty_berat2 = hitung_qty_berat.toString().replaceAll(/(\d)(?=(\d\d\d)+(?!\d))/g, "$1.");
                    document.getElementById("sub_total_berat" + x).value = hitung_qty_berat2;

                    document.getElementById("free" + x).value = '0';
                }

                var kurangin = parseInt(hitung_total) + parseInt(kali);
                var kurangin2 = kurangin.toString().replaceAll(/(\d)(?=(\d\d\d)+(?!\d))/g, "$1.");
                document.getElementById("total_biaya").value = kurangin2;

                var tambahin = parseInt(hitung_total_berat) + parseInt(hitung_qty_berat);
                var tambahin2 = tambahin.toString().replaceAll(/(\d)(?=(\d\d\d)+(?!\d))/g, "$1.");
                document.getElementById("total_berat").value = tambahin2;

                var biaya_kirim = document.getElementById("biaya_kirim").value;
                var biaya_kirim2 = biaya_kirim.replaceAll(".", "");
                var diskon = document.getElementById("diskon").value;
                var diskon2 = diskon.replaceAll(".", "");

                if (document.getElementById("jenis_diskon").value == 'persen') {
                    diskon2 = (parseInt(diskon2) / 100) * parseInt(total_biaya2);
                }

                // Sub Total
                var main_sub_total = parseInt(kurangin) - parseInt(diskon2);
                var main_sub_total2 = main_sub_total.toString().replaceAll(/(\d)(?=(\d\d\d)+(?!\d))/g, "$1.");
                document.getElementById("sub_total").value = main_sub_total2;

                var biaya_lain = document.getElementById("biaya_lain").value;
                var biaya_lain2 = biaya_lain.replaceAll(".", "");

                var deposit = document.getElementById("deposit").value;
                var deposit2 = deposit.replaceAll(".", "");
                // Net Total
                // var net_total = parseInt(kurangin) + main_sub_total + parseInt(biaya_kirim2);
                // var net_total2 = net_total.toString().replaceAll(/(\d)(?=(\d\d\d)+(?!\d))/g, "$1.");
                // document.getElementById("net_total").value=net_total2;

                var net_total = main_sub_total + parseInt(biaya_kirim2) + parseInt(biaya_lain2) - parseInt(deposit2);
                var net_total2 = net_total.toString().replaceAll(/(\d)(?=(\d\d\d)+(?!\d))/g, "$1.");
                document.getElementById("net_total").value = net_total2;

                document.getElementById("sisa_bayar").value = net_total2;

                var hj_retail_lama = document.getElementById("hj_retail_lama" + x).value;
                var jumlah1 = parseInt(stok_gudang2) * parseInt(hj_retail_lama);
                var jumlah2 = parseInt(stok_gudang2) + parseInt(qty);

                var jumlah3 = parseInt(jumlah1) + parseInt(kali);

                var jumlah4 = parseInt(jumlah3) / parseInt(jumlah2);

                //document.getElementById("stok_gudang_baru"+x).value=jumlah2;
                document.getElementById("hj_retail_baru" + x).value = jumlah4;
            }

            document.getElementById("baris").value = x;
        }

        var kali = qty * hj_retail2;
        var kali2 = kali.toString().replaceAll(/(\d)(?=(\d\d\d)+(?!\d))/g, "$1.");

        document.getElementById("sub_total" + x).value = kali2;

        var berat = document.getElementById("berat" + x).value;
        var berat2 = berat.replaceAll(".", "");

        var free = document.getElementById("free" + x).value;
        if (free == '') {
            free = '0';
        }
        var free2 = free.replaceAll(".", "");

        if (qty == '') {
            qty = '0';
        }
        // console.log(qty, free2, berat2);
        var hitung_qty_berat = (parseInt(qty) + parseInt(free2)) * parseInt(berat2);
        var hitung_qty_berat2 = hitung_qty_berat.toString().replaceAll(/(\d)(?=(\d\d\d)+(?!\d))/g, "$1.");
        document.getElementById("sub_total_berat" + x).value = hitung_qty_berat2;

        var on_hands = document.getElementById("on_hands" + x).value;
        var on_hands2 = on_hands.replaceAll(".", "");


        var hitung_on_hand = parseInt(on_hands2) + parseInt(qty) + parseInt(free2);
        var hitung_on_hand2 = hitung_on_hand.toString().replaceAll(/(\d)(?=(\d\d\d)+(?!\d))/g, "$1.");
        document.getElementById("on_hand" + x).value = hitung_on_hand2;

        var stok_gudang = document.getElementById("stok_gudang" + x).value;
        var stok_gudang2 = stok_gudang.replaceAll(".", "");

        if (hitung_on_hand > stok_gudang2) {
            alert('Maksimal qty adalah');
            var stok_gudang3 = stok_gudang2.toString().replaceAll(/(\d)(?=(\d\d\d)+(?!\d))/g, "$1.");
            document.getElementById("on_hand" + x).value = stok_gudang3;
            var on_hands = document.getElementById("on_hands" + x).value;
            var max_qty = parseInt(stok_gudang2) - parseInt(on_hands);
            document.getElementById("qty" + x).value = max_qty;

            var kali = max_qty * hj_retail2;
            var kali2 = kali.toString().replaceAll(/(\d)(?=(\d\d\d)+(?!\d))/g, "$1.");
            document.getElementById("sub_total" + x).value = kali2;

            var hitung_qty_berat = max_qty * berat2;
            var hitung_qty_berat2 = hitung_qty_berat.toString().replaceAll(/(\d)(?=(\d\d\d)+(?!\d))/g, "$1.");
            document.getElementById("sub_total_berat" + x).value = hitung_qty_berat2;

            document.getElementById("free" + x).value = '0';
        }

        var kurangin = parseInt(hitung_total) + parseInt(kali);
        var kurangin2 = kurangin.toString().replaceAll(/(\d)(?=(\d\d\d)+(?!\d))/g, "$1.");
        document.getElementById("total_biaya").value = kurangin2;

        // console.log(hitung_total_berat, hitung_qty_berat);

        var tambahin = parseInt(hitung_total_berat) + parseInt(hitung_qty_berat);
        var tambahin2 = tambahin.toString().replaceAll(/(\d)(?=(\d\d\d)+(?!\d))/g, "$1.");
        document.getElementById("total_berat").value = tambahin2;

        var biaya_kirim = document.getElementById("biaya_kirim").value;
        var biaya_kirim2 = biaya_kirim.replaceAll(".", "");
        var diskon = document.getElementById("diskon").value;
        var diskon2 = diskon.replaceAll(".", "");

        if (document.getElementById("jenis_diskon").value == 'persen') {
            diskon2 = (parseInt(diskon2) / 100) * parseInt(total_biaya2);
        }

        // Sub Total
        var main_sub_total = parseInt(kurangin) - parseInt(diskon2);
        var main_sub_total2 = sub_total.toString().replaceAll(/(\d)(?=(\d\d\d)+(?!\d))/g, "$1.");
        document.getElementById("sub_total").value = main_sub_total2;

        var biaya_lain = document.getElementById("biaya_lain").value;
        var biaya_lain2 = biaya_lain.replaceAll(".", "");

        var deposit = document.getElementById("deposit").value;
        var deposit2 = deposit.replaceAll(".", "");

        // Net Total
        var net_total = main_sub_total + parseInt(biaya_kirim2) + parseInt(biaya_lain2) - parseInt(deposit2);
        var net_total2 = net_total.toString().replaceAll(/(\d)(?=(\d\d\d)+(?!\d))/g, "$1.");
        document.getElementById("net_total").value = net_total2;

        // var net_total = parseInt(kurangin)+parseInt(biaya_kirim2)-parseInt(diskon2);
        // var net_total2 = net_total.toString().replaceAll(/(\d)(?=(\d\d\d)+(?!\d))/g, "$1.");
        // document.getElementById("net_total").value=net_total2;

        document.getElementById("sisa_bayar").value = net_total2;

        var hj_retail_lama = document.getElementById("hj_retail_lama" + x).value;
        var jumlah1 = parseInt(stok_gudang2) * parseInt(hj_retail_lama);
        var jumlah2 = parseInt(stok_gudang2) + parseInt(qty);

        var jumlah3 = parseInt(jumlah1) + parseInt(kali);

        var jumlah4 = parseInt(jumlah3) / parseInt(jumlah2);

        //document.getElementById("stok_gudang_baru"+x).value=jumlah2;
        document.getElementById("hj_retail_baru" + x).value = jumlah4;
    }

    function checkData() {
        var user_id = document.getElementById('user_id').value;
        var password = document.getElementById('password').value;
        var x = document.getElementById('baris').value;
        var modal = document.getElementById("myModal");
        var span = document.getElementsByClassName("close")[0];

        var url = "<?php echo $this->baseUrl; ?>/salecentral/cekdatauser";
        var opt = {
            password: password,
            user_id: user_id
        };

        jQuery.get(url, opt, function(data) {
            if (data == '0') {

                span.onclick = function() {
                    modal.style.display = "none";

                    var total_berat = document.getElementById("total_berat").value;
                    var total_berat2 = total_berat.replaceAll(".", "");
                    var sub_total_berat = document.getElementById("sub_total_berat" + x).value;
                    var sub_total_berat2 = sub_total_berat.replaceAll(".", "");

                    var hitung_total_berat = parseInt(total_berat2) - parseInt(sub_total_berat2);

                    var total_biaya = document.getElementById("total_biaya").value;
                    var total_biaya2 = total_biaya.replaceAll(".", "");
                    var sub_total = document.getElementById("sub_total" + x).value;
                    var sub_total2 = sub_total.replaceAll(".", "");

                    var hitung_total = parseInt(total_biaya2) - parseInt(sub_total2);
                    var qty = document.getElementById("qty" + x).value;

                    var hj_retail = document.getElementById("hj_retail" + x).value;
                    var hj_retail2 = hj_retail.replaceAll(".", "");
                    var hj_retail3 = hj_retail2.toString().replaceAll(/(\d)(?=(\d\d\d)+(?!\d))/g, "$1.");
                    document.getElementById("hj_retail" + x).value = hj_retail3;

                    var hj_retail_lama = document.getElementById("hj_retail_lama" + x).value;
                    var hj_retail_lama2 = hj_retail_lama.replaceAll(".", "");
                    var hj_retail_lama3 = hj_retail_lama2.toString().replaceAll(/(\d)(?=(\d\d\d)+(?!\d))/g, "$1.");

                    document.getElementById("hj_retail" + x).value = hj_retail_lama3;
                    var hj_retail = document.getElementById("hj_retail" + x).value;
                    var hj_retail2 = hj_retail.replaceAll(".", "");

                    var kali = qty * hj_retail2;
                    var kali2 = kali.toString().replaceAll(/(\d)(?=(\d\d\d)+(?!\d))/g, "$1.");

                    document.getElementById("sub_total" + x).value = kali2;

                    var berat = document.getElementById("berat" + x).value;
                    var berat2 = berat.replaceAll(".", "");

                    var free = document.getElementById("free" + x).value;
                    var free2 = free.replaceAll(".", "");

                    var hitung_qty_berat = (parseInt(qty) + parseInt(free2)) * berat2;
                    var hitung_qty_berat2 = hitung_qty_berat.toString().replaceAll(/(\d)(?=(\d\d\d)+(?!\d))/g, "$1.");
                    document.getElementById("sub_total_berat" + x).value = hitung_qty_berat2;

                    var on_hands = document.getElementById("on_hands" + x).value;
                    var on_hands2 = on_hands.replaceAll(".", "");


                    var hitung_on_hand = parseInt(on_hands2) + parseInt(qty) + parseInt(free2);
                    var hitung_on_hand2 = hitung_on_hand.toString().replaceAll(/(\d)(?=(\d\d\d)+(?!\d))/g, "$1.");
                    document.getElementById("on_hand" + x).value = hitung_on_hand2;

                    var stok_gudang = document.getElementById("stok_gudang" + x).value;
                    var stok_gudang2 = stok_gudang.replaceAll(".", "");

                    if (hitung_on_hand > stok_gudang2) {
                        alert('Maksimal qty adalah');
                        var stok_gudang3 = stok_gudang2.toString().replaceAll(/(\d)(?=(\d\d\d)+(?!\d))/g, "$1.");
                        document.getElementById("on_hand" + x).value = stok_gudang3;
                        var on_hands = document.getElementById("on_hands" + x).value;
                        var max_qty = parseInt(stok_gudang2) - parseInt(on_hands);
                        document.getElementById("qty" + x).value = max_qty;

                        var kali = max_qty * hj_retail2;
                        var kali2 = kali.toString().replaceAll(/(\d)(?=(\d\d\d)+(?!\d))/g, "$1.");
                        document.getElementById("sub_total" + x).value = kali2;

                        var hitung_qty_berat = max_qty * berat2;
                        var hitung_qty_berat2 = hitung_qty_berat.toString().replaceAll(/(\d)(?=(\d\d\d)+(?!\d))/g, "$1.");
                        document.getElementById("sub_total_berat" + x).value = hitung_qty_berat2;

                        document.getElementById("free" + x).value = '0';
                    }

                    var kurangin = parseInt(hitung_total) + parseInt(kali);
                    var kurangin2 = kurangin.toString().replaceAll(/(\d)(?=(\d\d\d)+(?!\d))/g, "$1.");
                    document.getElementById("total_biaya").value = kurangin2;

                    var tambahin = parseInt(hitung_total_berat) + parseInt(hitung_qty_berat);
                    var tambahin2 = tambahin.toString().replaceAll(/(\d)(?=(\d\d\d)+(?!\d))/g, "$1.");
                    document.getElementById("total_berat").value = tambahin2;

                    var biaya_kirim = document.getElementById("biaya_kirim").value;
                    var biaya_kirim2 = biaya_kirim.replaceAll(".", "");
                    var diskon = document.getElementById("diskon").value;
                    var diskon2 = diskon.replaceAll(".", "");

                    if (document.getElementById("jenis_diskon").value == 'persen') {
                        diskon2 = (parseInt(diskon2) / 100) * parseInt(total_biaya2);
                    }

                    // Sub Total
                    var main_sub_total = parseInt(kurangin) - parseInt(diskon2);
                    var main_sub_total2 = sub_total.toString().replaceAll(/(\d)(?=(\d\d\d)+(?!\d))/g, "$1.");
                    document.getElementById("sub_total").value = main_sub_total2;

                    var biaya_lain = document.getElementById("biaya_lain").value;
                    var biaya_lain2 = biaya_lain.replaceAll(".", "");

                    var deposit = document.getElementById("deposit").value;
                    var deposit2 = deposit.replaceAll(".", "");

                    // Net Total
                    var net_total = main_sub_total + parseInt(biaya_kirim2) + parseInt(biaya_lain2) - parseInt(deposit2);
                    var net_total2 = net_total.toString().replaceAll(/(\d)(?=(\d\d\d)+(?!\d))/g, "$1.");
                    document.getElementById("net_total").value = net_total2;

                    // var net_total = parseInt(kurangin)+parseInt(biaya_kirim2)-parseInt(diskon2);
                    // var net_total2 = net_total.toString().replaceAll(/(\d)(?=(\d\d\d)+(?!\d))/g, "$1.");
                    // document.getElementById("net_total").value=net_total2;

                    document.getElementById("sisa_bayar").value = net_total2;

                    var hj_retail_lama = document.getElementById("hj_retail_lama" + x).value;
                    var jumlah1 = parseInt(stok_gudang2) * parseInt(hj_retail_lama);
                    var jumlah2 = parseInt(stok_gudang2) + parseInt(qty);

                    var jumlah3 = parseInt(jumlah1) + parseInt(kali);

                    var jumlah4 = parseInt(jumlah3) / parseInt(jumlah2);

                    //document.getElementById("stok_gudang_baru"+x).value=jumlah2;
                    document.getElementById("hj_retail_baru" + x).value = jumlah4;
                }

                document.getElementById('gagal-error').innerHTML = "<span style='color: red;'>User ID atau Password Salah !</span>";
            } else {
                document.getElementById('gagal-error').innerHTML = '';
                modal.style.display = "none";
            }
        });

        //alert(test);
    }

    function biaya() {
        var total_biaya = document.getElementById("total_biaya").value;
        var total_biaya2 = total_biaya.replaceAll(".", "");
        var biaya_kirim = document.getElementById("biaya_kirim").value;
        var biaya_kirim2 = biaya_kirim.replaceAll(".", "");
        var biaya_kirim3 = biaya_kirim2.toString().replaceAll(/(\d)(?=(\d\d\d)+(?!\d))/g, "$1.");
        document.getElementById("biaya_kirim").value = biaya_kirim3;

        var diskon = document.getElementById("diskon").value;
        var diskon2 = diskon.replaceAll(".", "");

        if (document.getElementById("jenis_diskon").value == 'persen') {
            diskon2 = (parseInt(diskon2) / 100) * parseInt(total_biaya2);
        }

        // Sub Total
        var main_sub_total = parseInt(total_biaya2) - parseInt(diskon2);
        var main_sub_total2 = main_sub_total.toString().replaceAll(/(\d)(?=(\d\d\d)+(?!\d))/g, "$1.");
        document.getElementById("sub_total").value = main_sub_total2;

        var biaya_lain = document.getElementById("biaya_lain").value;
        var biaya_lain2 = biaya_lain.replaceAll(".", "");

        var deposit = document.getElementById("deposit").value;
        var deposit2 = deposit.replaceAll(".", "");

        // Net Total
        var net_total = main_sub_total + parseInt(biaya_kirim2) + parseInt(biaya_lain2) - parseInt(deposit2);
        var net_total2 = net_total.toString().replaceAll(/(\d)(?=(\d\d\d)+(?!\d))/g, "$1.");
        document.getElementById("net_total").value = net_total2;

        // var net_total = parseInt(total_biaya2)+parseInt(biaya_kirim2)-parseInt(diskon);
        // var net_total2 = net_total.toString().replaceAll(/(\d)(?=(\d\d\d)+(?!\d))/g, "$1.");
        // document.getElementById("net_total").value=net_total2;

        document.getElementById("sisa_bayar").value = net_total2;
    }

    function biayaLain() {
        var total_biaya = document.getElementById("total_biaya").value;
        var total_biaya2 = total_biaya.replaceAll(".", "");
        var biaya_kirim = document.getElementById("biaya_kirim").value;
        var biaya_kirim2 = biaya_kirim.replaceAll(".", "");


        var diskon = document.getElementById("diskon").value;
        var diskon2 = diskon.replaceAll(".", "");

        if (document.getElementById("jenis_diskon").value == 'persen') {
            diskon2 = (parseInt(diskon2) / 100) * parseInt(total_biaya2);
        }

        // Sub Total
        var main_sub_total = parseInt(total_biaya2) - parseInt(diskon2);
        var main_sub_total2 = main_sub_total.toString().replaceAll(/(\d)(?=(\d\d\d)+(?!\d))/g, "$1.");
        document.getElementById("sub_total").value = main_sub_total2;

        var biaya_lain = document.getElementById("biaya_lain").value;
        var biaya_lain2 = biaya_lain.replaceAll(".", "");
        var biaya_lain3 = biaya_lain2.toString().replaceAll(/(\d)(?=(\d\d\d)+(?!\d))/g, "$1.");
        document.getElementById("biaya_lain").value = biaya_lain3;

        var deposit = document.getElementById("deposit").value;
        var deposit2 = deposit.replaceAll(".", "");

        // Net Total
        var net_total = main_sub_total + parseInt(biaya_kirim2) + parseInt(biaya_lain2) - parseInt(deposit2);
        var net_total2 = net_total.toString().replaceAll(/(\d)(?=(\d\d\d)+(?!\d))/g, "$1.");
        document.getElementById("net_total").value = net_total2;

        // var net_total = parseInt(total_biaya2)+parseInt(biaya_kirim2)-parseInt(diskon);
        // var net_total2 = net_total.toString().replaceAll(/(\d)(?=(\d\d\d)+(?!\d))/g, "$1.");
        // document.getElementById("net_total").value=net_total2;

        document.getElementById("sisa_bayar").value = net_total2;
    }

    function onDepositChange() {
        var total_biaya = document.getElementById("total_biaya").value;
        var total_biaya2 = total_biaya.replaceAll(".", "");
        var biaya_kirim = document.getElementById("biaya_kirim").value;
        var biaya_kirim2 = biaya_kirim.replaceAll(".", "");


        var diskon = document.getElementById("diskon").value;
        var diskon2 = diskon.replaceAll(".", "");

        if (document.getElementById("jenis_diskon").value == 'persen') {
            diskon2 = (parseInt(diskon2) / 100) * parseInt(total_biaya2);
        }

        // Sub Total
        var main_sub_total = parseInt(total_biaya2) - parseInt(diskon2);
        var main_sub_total2 = main_sub_total.toString().replaceAll(/(\d)(?=(\d\d\d)+(?!\d))/g, "$1.");
        document.getElementById("sub_total").value = main_sub_total2;

        var biaya_lain = document.getElementById("biaya_lain").value;
        var biaya_lain2 = biaya_lain.replaceAll(".", "");


        var deposit = document.getElementById("deposit").value;
        var deposit2 = deposit.replaceAll(".", "");
        var deposit3 = deposit2.toString().replaceAll(/(\d)(?=(\d\d\d)+(?!\d))/g, "$1.");
        document.getElementById("deposit").value = deposit3;

        // Net Total
        var net_total = main_sub_total + parseInt(biaya_kirim2) + parseInt(biaya_lain2) - parseInt(deposit2);
        var net_total2 = net_total.toString().replaceAll(/(\d)(?=(\d\d\d)+(?!\d))/g, "$1.");
        document.getElementById("net_total").value = net_total2;

        // var net_total = parseInt(total_biaya2)+parseInt(biaya_kirim2)-parseInt(diskon);
        // var net_total2 = net_total.toString().replaceAll(/(\d)(?=(\d\d\d)+(?!\d))/g, "$1.");
        // document.getElementById("net_total").value=net_total2;

        document.getElementById("sisa_bayar").value = net_total2;
    }

    function datadiskon() {
        var total_biaya = document.getElementById("total_biaya").value;
        var total_biaya2 = total_biaya.replaceAll(".", "");
        var biaya_kirim = document.getElementById("biaya_kirim").value;
        var biaya_kirim2 = biaya_kirim.replaceAll(".", "");
        var diskon = document.getElementById("diskon").value;
        var diskon2 = diskon.replaceAll(".", "");
        var diskon3 = diskon2.toString().replaceAll(/(\d)(?=(\d\d\d)+(?!\d))/g, "$1.");

        if (document.getElementById("jenis_diskon").value == 'persen') {
            // diskon3 = diskon2;
            diskon2 = (parseInt(diskon2) / 100) * parseInt(total_biaya2);
        }

        document.getElementById("diskon").value = diskon3;

        var sub_total = parseInt(total_biaya2) - parseInt(diskon2);
        var sub_total2 = sub_total.toString().replaceAll(/(\d)(?=(\d\d\d)+(?!\d))/g, "$1.");
        document.getElementById("sub_total").value = sub_total2;

        var biaya_lain = document.getElementById("biaya_lain").value;
        var biaya_lain2 = biaya_lain.replaceAll(".", "");

        var deposit = document.getElementById("deposit").value;
        var deposit2 = deposit.replaceAll(".", "");

        var net_total = sub_total + parseInt(biaya_kirim2) + parseInt(biaya_lain2) - parseInt(deposit2);
        var net_total2 = net_total.toString().replaceAll(/(\d)(?=(\d\d\d)+(?!\d))/g, "$1.");
        document.getElementById("net_total").value = net_total2;
        // var net_total = parseInt(total_biaya2)+parseInt(biaya_kirim2)-parseInt(diskon2);
        // var net_total2 = net_total.toString().replaceAll(/(\d)(?=(\d\d\d)+(?!\d))/g, "$1.");
        // document.getElementById("net_total").value=net_total2;

        document.getElementById("sisa_bayar").value = net_total2;
    }

    function calculate() {
        var total_biaya = document.getElementById("total_biaya").value;
        var total_biaya2 = total_biaya.replaceAll(".", "");
        var biaya_kirim = document.getElementById("biaya_kirim").value;
        var biaya_kirim2 = biaya_kirim.replaceAll(".", "");
        var diskon = document.getElementById("diskon").value;
        var diskon2 = diskon.replaceAll(".", "");

        if (document.getElementById("jenis_diskon").value == 'persen') {
            diskon2 = (parseInt(diskon2) / 100) * parseInt(total_biaya2);
        }

        var sub_total = parseInt(total_biaya2) - parseInt(diskon2);
        var sub_total2 = sub_total.toString().replaceAll(/(\d)(?=(\d\d\d)+(?!\d))/g, "$1.");
        document.getElementById("sub_total").value = sub_total2;

        var biaya_lain = document.getElementById("biaya_lain").value;
        var biaya_lain2 = biaya_lain.replaceAll(".", "");

        var deposit = document.getElementById("deposit").value;
        var deposit2 = deposit.replaceAll(".", "");

        var net_total = sub_total + parseInt(biaya_kirim2) + parseInt(biaya_lain2) - parseInt(deposit2);
        var net_total2 = net_total.toString().replaceAll(/(\d)(?=(\d\d\d)+(?!\d))/g, "$1.");
        document.getElementById("net_total").value = net_total2;
        // var net_total = parseInt(total_biaya2)+parseInt(biaya_kirim2)-parseInt(diskon2);
        // var net_total2 = net_total.toString().replaceAll(/(\d)(?=(\d\d\d)+(?!\d))/g, "$1.");
        // document.getElementById("net_total").value=net_total2;

        document.getElementById("sisa_bayar").value = net_total2;
    }

    $('#jenis_diskon').on('change', function() {
        calculate();
        var diskon = document.getElementById("diskon").value;
        var diskon2 = diskon.replaceAll(".", "");
        var diskon3 = diskon2.toString().replaceAll(/(\d)(?=(\d\d\d)+(?!\d))/g, "$1.");

        if (document.getElementById("jenis_diskon").value == 'persen') {
            diskon3 = diskon2;
        }

        document.getElementById("diskon").value = diskon3;
    })

    function jumlahdp() {
        var net_total = document.getElementById("net_total").value;
        var net_total2 = net_total.replaceAll(".", "");
        var jml_penerimaan = document.getElementById("jml_penerimaan").value;
        var jml_penerimaana = jml_penerimaan.replaceAll(".", "");
        var jml_penerimaanb = jml_penerimaana.toString().replaceAll(/(\d)(?=(\d\d\d)+(?!\d))/g, "$1.");
        document.getElementById("jml_penerimaan").value = jml_penerimaanb;

        var jml_penerimaan2 = document.getElementById("jml_penerimaan2").value;
        var jml_penerimaan2a = jml_penerimaan2.replaceAll(".", "");
        var jml_penerimaan2b = jml_penerimaan2a.toString().replaceAll(/(\d)(?=(\d\d\d)+(?!\d))/g, "$1.");
        document.getElementById("jml_penerimaan2").value = jml_penerimaan2b;

        var jml_bayar = parseInt(jml_penerimaana) + parseInt(jml_penerimaan2a);
        var jml_bayar2 = jml_bayar.toString().replaceAll(/(\d)(?=(\d\d\d)+(?!\d))/g, "$1.");
        document.getElementById("jml_bayar").value = jml_bayar2;

        var sisa_bayar = parseInt(net_total2) - parseInt(jml_bayar);
        var sisa_bayar2 = sisa_bayar.toString().replaceAll(/(\d)(?=(\d\d\d)+(?!\d))/g, "$1.");
        document.getElementById("sisa_bayar").value = sisa_bayar2;
    }

    function coba(button) {
        var x = button;

        var hj_retail = document.getElementById("hj_retail" + x).value;
        var hj_retail2 = hj_retail.replaceAll(".", "");
        var hj_retail3 = hj_retail2.toString().replaceAll(/(\d)(?=(\d\d\d)+(?!\d))/g, "$1.");
        document.getElementById("hj_retail" + x).value = hj_retail3;
    }
</script>

<!--script>
		// Get the modal
		var modal = document.getElementById("myModal");

		// Get the button that opens the modal
		var btn = document.getElementById("myBtn");

		// Get the <span> element that closes the modal
		var span = document.getElementsByClassName("close")[0];

		// When the user clicks the button, open the modal 
		btn.onclick = function() {
		  modal.style.display = "block";
		}

		// When the user clicks on <span> (x), close the modal
		span.onclick = function() {
		  modal.style.display = "none";
		}

		// When the user clicks anywhere outside of the modal, close it
		window.onclick = function(event) {
		  if (event.target == modal) {
			modal.style.display = "none";
		  }
		}
	</script-->

<script>
    $(".product").select2();
</script>
<script>
    $(document).ready(function() {

        $('#tgl_invoice').datepicker({
            dateFormat: 'dd/mm/yy',
            changeMonth: true,
            changeYear: true
        });



    });
</script>


</body>

</html>