<?php require('partial/header.php');?>
<?php require('partial/menu.php');?>    
<script>
	$(document).ready(function () {
		$('#dataTables-emp').dataTable({
			"bPaginate": true,
			"bLengthChange": true,
			"bFilter": true,
			"bInfo": true,
			"bAutoWidth": true});
	});
	 
</script>
    <!-- **********************************************************************************************************************************************************
        MAIN CONTENT
        *********************************************************************************************************************************************************** -->
    <!--main content start-->
    <section id="main-content">
      <section class="wrapper" style="min-height:522px">
        <h3><i class="fa fa-angle-right"></i> Stock Opname</h3>
        <div class="row mb">
          <!-- page start-->
          <div class="content-panel">
            <div class="adv-table">
			<div id="listprogram" align="center"  class="col-xs-12">
				<br>
					<div id="page-content">
						<div class="form-group form-group-bottom" align="left">
							<button class="right btn btn-success  btn-xs" onClick="open_url_to_div('/sopretail/tambahdata')"><i class="fa fa-plus"></i>&nbsp;&nbsp;Buat Baru</button>		
						</div>
						<table style="font-size:12px;" class="table table-striped table-bordered table-hover" id="dataTables-emp">
							<thead>
							<tr bgcolor="#4ECDC4">
								<th width="5%" style="text-align:center;">No</th>
								<th width="40%" style="text-align:center;">Nomor Stock Opname</th>
								<th width="20%" style="text-align:center;">Tanggal Stock Opname</th>
								<th width="15%" style="text-align:center;">Kategori</th>
								<th width="10%" style="text-align:center;">Detail/Edit</th>
								<!--th width="10%" style="text-align:center;">Hapus</th-->
							</tr>
							</thead>
							<tbody>
							<?php
								 for($x=0; $x<count($this->data); $x++){

										$nomer			= $x+1;
										$no_sop 		= $this->data[$x]['no_sop'];
										$kategori	 	= $this->data[$x]['kategori'];
										$tgl_sop	 	= date_create($this->data[$x]['tgl_sop']);
										$tgl_sop		= date_format($tgl_sop,"d-m-Y");
									?>	
										<tr>
											<td align="center"><?php echo $nomer;?></td>	  
											<td align="center"><?php echo $no_sop;?></td>
											<td align="center"><?php echo $tgl_sop;?></td>
											<td align="center"><?php echo $kategori;?></td>
											<td width="7%">
                                                <a href="#" title="Edit" onclick="open_url_to_div('/sopretail/editdata?id=<?php echo $no_sop;?>')" class="btn-warning btn-sm mar-ed-button"><i class="fa fa-edit pad-ico-button"></i>Edit</a>
                                            </td>
                                            <!--td width="8%">
												<a href="#" title="Hapus" onclick="hapusdata('<?php echo $no_sop; ?>')" class="btn-danger btn-sm mar-ed-button"><i class="fa fa-trash-o pad-ico-button"></i>Hapus</a>
                                            </td-->	
										</tr>	
									<?php 
										}
									?>
								
							</tbody>
						</table>
					  </div>
				</div>
            </div>
          </div>
          <!-- page end-->
        </div>
        <!-- /row -->
      </section>
      <!-- /wrapper -->
    </section>
    <!--main content end-->
    <?php require('partial/main-footer.php');?> 
  </section>
   <!-- js placed at the end of the document so the pages load faster -->
  <script src="lib/jquery/jquery.min.js"></script>
  <script type="text/javascript" language="javascript" src="lib/advanced-datatable/js/jquery.js"></script>
  <script src="lib/bootstrap/js/bootstrap.min.js"></script>
  <script class="include" type="text/javascript" src="lib/jquery.dcjqaccordion.2.7.js"></script>
  <script src="lib/jquery.scrollTo.min.js"></script>
  <script src="lib/jquery.nicescroll.js" type="text/javascript"></script>
  <script type="text/javascript" language="javascript" src="lib/advanced-datatable/js/jquery.dataTables.js"></script>
  <script type="text/javascript" src="lib/advanced-datatable/js/DT_bootstrap.js"></script>
  <!--common script for all pages-->
  <script src="lib/common-scripts.js"></script>
  <!--script for this page-->
  <script type="text/javascript">
	function hapusdata(no_sop){
			var r = confirm("Anda yakin akan menghapus data ini ?");
			if (r == true) {
					var url = "<?php echo $this->basePath; ?>/sopretail/hapusdata";
					var opt = {no_sop:no_sop}
					
					jQuery.get(url,opt, function(data) {	
						location.reload(true)
						//jQuery("div#example1").html(data);
						//jQuery("#page-content").html(data);
					})
					//open_url_to_div('<?php echo $this->baseUrl(); ?>/pengaduan/index');
					//location.reload(true)
			} else {
				close();
			}
		}
  </script>
</body>

</html>
