<?php require('partial/header.php');?>
<?php require('partial/menu.php');?>   

<script>
	$(document).ready(function () {
		$('#dataTables-emp').dataTable({
			"bPaginate": true,
			"bLengthChange": true,
			"bFilter": true,
			"bInfo": true,
			"bAutoWidth": true});
	});
	 
</script>
    <!-- **********************************************************************************************************************************************************
        MAIN CONTENT
        *********************************************************************************************************************************************************** -->
    <!--main content start-->
    <section id="main-content">
      <section class="wrapper" style="min-height:522px">
        <h3><i class="fa fa-angle-right"></i> Finance</h3>
        <div class="row mb">
          <!-- page start-->
          <div class="content-panel">
            <div class="adv-table">
			<div id="listprogram" align="center"  class="col-xs-12">
				<br>
					<div id="page-content">
						<div class="form-group form-group-bottom" align="left" id="tambah">
							<button class="right btn btn-success  btn-xs" onClick="tambahdata()"><i class="fa fa-plus"></i>&nbsp;&nbsp;Tambah Data</button>		
						</div>
						
						
	<form id="frm_postdata" name="frm_postdata" enctype="multipart/form-data" method="POST">
	<input type="hidden" name="currentPage" id="currentPage" size="6" maxlength="6" value="<?php echo $this->numPage;?>" class="inputbox2 narrowkey1"></input>
		<?php 
			$seq = $this->seq;
			//var_dump($seq);
			$seq += 1;
			$seq2=str_pad($seq, 2, '0', STR_PAD_LEFT);
		?>
		<input type="hidden" id='seq' name='seq' value ='<?php echo $seq;?>'>
		<input type="hidden" id='action' name='action' value =''>
		<div class="panel">
            <fieldset class="panel-dt">	
				<h4 align="left"><u>Tambah Sumber Dana</u></h4>
				<br>
					<div class="col-sm-12">
						<table width="100%">
							<!-- baris judul -->
							<tr>
								<td width="10%"><font style="font-size:12px;font-weight:bold;">Sumber Dana</font></td>
								<td> &nbsp;</td>
								<td width="14%"><font style="font-size:12px;font-weight:bold;">Saldo Awal</font></td>
								<td> &nbsp;</td>
								<td width="14%"><font style="font-size:12px;font-weight:bold;">Nomor Rekening</font></td>
								<td> &nbsp;</td>
								<td width="18%"><font style="font-size:12px;font-weight:bold;">Kode Cabang</font></td>
								<td> &nbsp;</td>
								<td width="14%"><font style="font-size:12px;font-weight:bold;">Nama Cabang Pembuka</font></td>
								<td> &nbsp;</td>
								<td> &nbsp;</td>
								<td> &nbsp;</td>
								
							</tr> 
						<!-- 	Baris input -->

							<tr>

								<td width="14%"> 	
											<input name="nama_akun" id="nama_akun" type="text" maxlength="50" size="20" class="form-control" value=""> 
											<span class="input-group-btn add-on">
											
											</span>
										
								</td>

								<td >&nbsp;</td>
							
								<td width="16%"> 
									<input name="saldo_awal" id="saldo_awal" type="text" maxlength="30" size="30" class="form-control input-sm" placeholder="0"  onkeyup='masking("saldo_awal")'> 

								</td>

								<td> &nbsp;</td>
								<td width="20%">
									<input name="no_akun" id="no_akun" type="text" maxlength="30" size="30" class="form-control input-sm" value=""> 
								</td>

								<td> &nbsp;</td>
								<td width="16%">
									<input name="kode_cabang" id="kode_cabang" type="text" maxlength="30" size="30" class="form-control input-sm" value=""> 

								</td>

								<td> &nbsp;</td>
								<td width="16%">
									<input name="nama_cabang_pembuka" id="nama_cabang_pembuka" type="text" maxlength="30" size="30" class="form-control input-sm" value=""> 
									
								</td>
								<td> &nbsp;</td>
									<td width="16%">
									<label for="transfer">
									 	<input required=""  name="type" type="radio" id="transfer" name="transfer" value="Transfer">

										Transfer
									</label>
									
									<label for="Cash">
										<input required="" name="type"  type="radio" id="cash" name="cash" value="Cash">
										Cash
									</label>
									
								</td>
							</tr> 
								<!-- validasi error -->
							<tr>
								<td width="10%"> &nbsp; <label id="nama_akun-error" for="nama_akun" class="error"></font></td>
								<td>  &nbsp; </td>
								<td width="14%"> &nbsp; <label id="saldo_awal-error" for="saldo_awal" class="error"></font></td>
								<td> &nbsp; </td>
								<td width="14%"> &nbsp; <label id="no_akun-error" for="no_akun" class="error"></td>
								<td> &nbsp; </td>
								<td width="18%">&nbsp; <label id="kode_cabang-error" for="kode_cabang" class="error"></td>
								<td> &nbsp;</td>
								<td width="14%"> &nbsp; <label id="nama_cabang_pembuka-error" for="nama_cabang_pembuka" class="error"></td>
								<td> &nbsp;</td>
								
							</tr> 

							
						</table>
					</div>
				<div class="col-lg-12">
					<div class="form-group form-group-bottom" align="right">
						<input type="hidden" id="proses" name="proses" value="<?php echo $this->proses?>">	
						<br><br>
							
							<button onclick="back();" type="button" class="btn btn-theme02">
								<span class="fa fa-backward"></span> &nbsp;Kembali
							</button>
							<button type="button" class="btn btn-theme03" onCLick="PostData()">
								<span class="fa fa-save"></span> &nbsp;Simpan
							</button>
					</div>
				</div>
			</fieldset>
		</div>
	</form>			
						
						<table style="font-size:12px;" class="table table-striped table-bordered table-hover" id="dataTables-emp">
							<thead>
							<tr bgcolor="#4ECDC4">
								<th width="3%" style="text-align:center;">No</th>
								<th width="7%" style="text-align:center;">Sumber Dana</th>
								<th width="8%" style="text-align:center;">Nomor Rekening</th>
								<th width="8%" style="text-align:center;">Kode Cabang </th>
								<th width="8%" style="text-align:center;">Saldo Awal</th>
								<th width="10%" style="text-align:center;">Nama Cabang Pembuka</th>
								
								<th width="20%" style="text-align:center;">Action</th>
							</tr>
							</thead>
							<tbody>
							<?php
								 for($x=0; $x<count($this->data); $x++){

										$nomer		= $x+1;
										$id 	= $this->data[$x]['id'];
										$nama_akun 	= $this->data[$x]['nama_akun'];
										$no_akun 	= $this->data[$x]['no_akun'];
										$kode_cabang 	= $this->data[$x]['kode_cabang'];
										$saldo_awal 	= $this->data[$x]['saldo_awal'];
										$nama_cabang_pembuka 	= $this->data[$x]['nama_cabang_pembuka'];
										if ($no_akun==0){
											$no_akun="";
										}
										if ($kode_cabang==0){
											$kode_cabang="";
										}
									
									?>	
											<td align="center"><?php echo $nomer;?></td>	  
											<td align="center"><?php echo $nama_akun;?></td>
											<td align="center"><?php echo $no_akun;?></td>
											<td align="center"><?php echo $kode_cabang;?></td>
											<td align="center"><?php echo 'Rp. '.number_format($saldo_awal,0,",",".")?></td>
											<td align="center"><?php echo $nama_cabang_pembuka;?></td>
											
											<td width="15%">
                                                <a title="Edit" onclick="editdata('<?php echo$id ?>')"   class="btn-warning btn-sm mar-ed-button"><i class="fa fa-edit pad-ico-button"></i>Edit</a>
                                                <a href="#" title="Hapus" onclick="hapusdata('<?php echo $id; ?>')" class="btn-danger btn-sm mar-ed-button"><i class="fa fa-trash-o pad-ico-button"></i>Hapus</a>
                                            </td>
                                          	
										</tr>	
									<?php 
										}
									?>
								
							</tbody>
						</table>
					  </div>
				</div>
            </div>
          </div>
          <!-- page end-->
        </div>


      </section>



      <!-- /wrapper -->
    </section>
    <!--main content end-->
    <?php require('partial/main-footer.php');?> 
  </section>
   <!-- js placed at the end of the document so the pages load faster -->
  <script src="lib/jquery/jquery.min.js"></script>
  <script type="text/javascript" language="javascript" src="lib/advanced-datatable/js/jquery.js"></script>
  <script src="lib/bootstrap/js/bootstrap.min.js"></script>
  <script class="include" type="text/javascript" src="lib/jquery.dcjqaccordion.2.7.js"></script>
  <script src="lib/jquery.scrollTo.min.js"></script>
  <script src="lib/jquery.nicescroll.js" type="text/javascript"></script>
  <script type="text/javascript" language="javascript" src="lib/advanced-datatable/js/jquery.dataTables.js"></script>
  <script type="text/javascript" src="lib/advanced-datatable/js/DT_bootstrap.js"></script>
   <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
  <script src="<?php echo $this->baseUrl();?>/lib/jquery-ui-1.9.2.custom.min.js"></script>
  
		<script src="<?php echo $this->baseUrl();?>/lib/jquery.form.js"></script>
		<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl();?>/css/sweetalert.css">
		<script src="<?php echo $this->baseUrl();?>/lib/sweetalert.min.js"></script>
  
  <!--common script for all pages-->
  <script src="lib/common-scripts.js"></script>
  <!--script for this page-->
  <script type="text/javascript">

  $("#frm_postdata").hide();

  function back(){
  	  $("#frm_postdata").hide();
  	  $("#tambah").show();
  	  $("#nama_cabang_pembuka").val("");
  	  $("#kode_cabang").val("");
  	  $("#no_akun").val("");
  	  $("#saldo_awal").val("");
  	   $("#nama_akun").val("");


  }
  

  //function masking nominal
  function masking(id){
  	var biaya_kirim = document.getElementById(id).value;
    var biaya_kirim2 = biaya_kirim.replaceAll(".", "");
    var biaya_kirim3 = biaya_kirim2.toString().replaceAll(/(\d)(?=(\d\d\d)+(?!\d))/g, "$1.");
    document.getElementById(id).value=biaya_kirim3;
  }

  function tambahdata(){
	  $("#frm_postdata").show();
	  $("#tambah").hide();
	  document.getElementById('action').value="tambah";
  }
  
  function editdata(id){
		$("#frm_postdata").show();
		$("#tambah").hide();
		
		var url = "<?php echo $this->baseUrl; ?>/tambahsumberdana/editdata";
		var opt = {id:id};
		jQuery.get(url,opt, function(data) { 
			document.getElementById('frm_postdata').innerHTML = data;
			document.getElementById('action').value="edit";
		});
  }
	function hapusdata(id){
			var r = confirm("Anda yakin akan menghapus data ini ?");
			if (r == true) {
					var url = "<?php echo $this->basePath; ?>/tambahsumberdana/hapusdata";
					var opt = {id:id}
					
					jQuery.get(url,opt, function(data) {	
						location.reload(true)
						//jQuery("div#example1").html(data);
						//jQuery("#page-content").html(data);
					})
					//open_url_to_div('<?php echo $this->baseUrl(); ?>/pengaduan/index');
					//location.reload(true)
			} else {
				close();
			}
		}
	
	function PostData(){
		//alert('Testing2');
        $("#frm_postdata").ajaxSubmit(post_data);
    }
	
	var post_data = {
		target:'',
		beforeSubmit: function() {	
			var nama_akun = document.getElementById('nama_akun').value;
			var saldo_awal = document.getElementById('saldo_awal').value;
			var no_akun = document.getElementById('no_akun').value;
			var kode_cabang = document.getElementById('kode_cabang').value;
			var nama_cabang_pembuka = document.getElementById('nama_cabang_pembuka').value;
			
				if (!nama_akun) {
					document.getElementById('nama_akun-error').innerHTML ="<span style='color: red;'>Nama akun harus diisi.</span>";
					document.getElementById('nama_akun').focus();
					exit;
				
					
				}else if (!saldo_awal) {
					document.getElementById('saldo_awal-error').innerHTML ="<span style='color: red;'>Saldo awal harus diisi.</span>";
					document.getElementById('saldo_awal').focus();
					document.getElementById('nama_akun-error').innerHTML ='';
					exit;
				}else{
					document.getElementById('nama_cabang_pembuka').focus();
					document.getElementById('no_akun-error').innerHTML ='';
					document.getElementById('nama_akun-error').innerHTML ='';
					document.getElementById('saldo_awal-error').innerHTML ='';
					document.getElementById('kode_cabang-error').innerHTML ='';
					document.getElementById('nama_cabang_pembuka-error').innerHTML ='';

				} 
			}, 
		success:function(){	
			swal({
				    title: 'Tambah Akun Berhasil !',
				    text: 'Auto Close...',
				    icon: 'success',
				    timer: 4000,
				    showConfirmButton: false,
				})
			//location.href="#";		
			location.reload(true);
		},
		url: '<?php echo $this->baseUrl();?>/tambahsumberdana/kirimdata',
		type: 'post',
		resetForm: false
	};
  </script>

</body>

</html>
