
<?php require('partial/header.php');?>
<?php require('partial/menu.php');?>   

<script>
	$(document).ready(function () {
		$('#dataTables-emp').dataTable({
			"bPaginate": true,
			"bLengthChange": true,
			"bFilter": true,
			"bInfo": true,
			"bAutoWidth": true});

			$('#dataTables-detail').dataTable({
			"bPaginate": true,
			"bLengthChange": true,
			"bFilter": true,
			"bInfo": true,
			"bAutoWidth": true});
	});
	 
</script>
    <!-- **********************************************************************************************************************************************************
        MAIN CONTENT
        *********************************************************************************************************************************************************** -->
    <!--main content start-->
    <section id="main-content">
      <section class="wrapper" style="min-height:522px">
        <h3><i class="fa fa-angle-right"></i> Finance</h3>
        <div class="row mb">
          <!-- page start-->
          <div class="content-panel">
            <div class="adv-table">
			<div id="listprogram" align="center"  class="col-xs-12">
				<br>
					<div id="page-content">
					
						
						
	<form id="frm_postdata" name="frm_postdata" enctype="multipart/form-data" method="POST">
	<input type="hidden" name="currentPage" id="currentPage" size="6" maxlength="6" value="<?php echo $this->numPage;?>" class="inputbox2 narrowkey1"></input>
		<?php 
			$seq = $this->seq;
			//var_dump($seq);
			$seq += 1;
			$seq2=str_pad($seq, 2, '0', STR_PAD_LEFT);
		?>
		<input type="hidden" id='seq' name='seq' value ='<?php echo $seq;?>'>
		<input type="hidden" id='action' name='action' value =''>
		<div class="panel">
            <fieldset class="panel-dt">	
				<h4 align="left"><u>Cash In Cash Out</u></h4>
				<br>
					<div class="col-sm-12">
						<table width="100%">
							<!-- baris judul -->
							<tr>
								<td width="10%"><font style="font-size:12px;font-weight:bold;">Tanggal Transaksi</font></td>
								<td> &nbsp;</td>
								<td width="14%"><font style="font-size:12px;font-weight:bold;">Jenis Transaksi</font></td>
								<td> &nbsp;</td>
								<td width="14%"><font style="font-size:12px;font-weight:bold;">Nominal</font></td>
								<td> &nbsp;</td>
								<td width="18%"><font style="font-size:12px;font-weight:bold;">Catatan</font></td>
								<td> &nbsp;</td>
								<td width="14%"><font style="font-size:12px;font-weight:bold;">Sumber Dana</font></td>
								<td> &nbsp;</td>
								<td width="14%"></td>
							</tr> 
						<!-- 	Baris input -->

							<tr>
								<td width="14%"> 
								
											<input name="tgl_transaksi" id="tgl_transaksi" type="text" maxlength="50" size="20" class="form-control" value=""> 
											<span class="input-group-btn add-on">
											<button class="btn btn-theme" type="button"><i class="fa fa-calendar"></i></button>
											</span>
										
								</td>
								<td >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td>
								<td width="16%"> 
									<select class="jenis_expense" id="jenis_expense" name="jenis_expense" class="form-control select_group product" style="width: 100%">
                        			<option value="">--Jenis Expense--</option>
                        		<?php  
                          			for($x=0; $x<count($this->jenis_expense); $x++){ 
                          			$keterangan = $this->jenis_expense[$x]['keterangan'];
                          			$id = $this->jenis_expense[$x]['id'];
                          		
                        		?>
                        			<option value="<?php echo $id;?>"><?php echo $keterangan;?></option>
                       			 <?php } ?>
                       			</select>

								</td>
								<td> </td>

								<td width="16%"> 
									<input name="nominal" id="nominal" type="text" maxlength="30" size="30" class="form-control input-sm" placeholder="0"  onkeyup='masking("nominal")'> 

								</td>
								<td> &nbsp;</td>

								<td width="20%">
									<input name="catatan" id="catatan" type="text" maxlength="30" size="30" class="form-control input-sm" value=""> 
								</td>
								<td> &nbsp;</td>
								<td width="16%">
									<select id="nama_akun" name="nama_akun" class="form-control select_group product" style="width: 100%">
                        			<option value="">--Sumber Dana--</option>
                        			<?php  
                          			for($x=0; $x<count($this->akun); $x++){ 
                          			$nama_akun = $this->akun[$x]['nama_akun'];
                          			$no_akun = $this->akun[$x]['no_akun'];
                          			$id = $this->akun[$x]['id'];
                          		
                        		?>
                        			<option value="<?php echo $id ?>"><?php echo $nama_akun.' | '.$no_akun;?></option>
                       			 <?php } ?>
                       			</select>


								</td>
								<td> &nbsp;</td>
								<td width="16%">
									<label for="cashin">
									 	<input required=""  name="type" type="radio" id="cashin" name="cashin" value="Cash In">

										Cash in
									</label>
									
									<label for="Cash In">
										<input required="" name="type"  type="radio" id="cashout" name="cashout" value="Cash Out">
										Cash out
									</label>
									
								</td>
							</tr> 

								<tr>
								<td width="10%">&nbsp; <label id="tgl_transaksi-error" for="nama_akun" class="error"></font></td>
								<td> &nbsp;</td>
								<td width="14%">&nbsp; <label id="jenis_expense-error" for="jenis_expense" class="error"></font></td>
								<td> &nbsp;</td>
								<td width="14%">&nbsp; <label id="nominal-error" for="nominal" class="error"></td>
								<td> &nbsp;</td>
								<td width="18%">&nbsp; <label id="catatan-error" for="catatan" class="error"></td>
								<td> &nbsp;</td>
								<td width="14%">&nbsp; <label id="nama_akun-error" for="nama_akun" class="error"></td>
								<td> &nbsp;</td>
								<td width="14%">&nbsp; <label id="type-error" for="nama_akun" class="error"></td>
								<td> &nbsp;</td>

								
							</tr> 


							
						</table>
					</div>
				<div class="col-lg-12">
					<div class="form-group form-group-bottom" align="right">
						<input type="hidden" id="proses" name="proses" value="<?php echo $this->proses?>">	
						<br><br>
							<a href="cashincashout">
							<button type="button" class="btn btn-theme02">
								<span class="fa fa-backward"></span> &nbsp;Kembali
							</button></a>
							<button type="button" class="btn btn-theme03" onCLick="PostData()">
								<span class="fa fa-save"></span> &nbsp;Simpan
							</button>
					</div>
				</div>
			</fieldset>
		</div>
	</form>			
						
						<table style="font-size:12px;" class="table table-striped table-bordered table-hover" id="dataTables-emp">
							<thead>
							<tr bgcolor="#4ECDC4">
								<th width="3%" style="text-align:center;">No</th>
								<th width="7%" style="text-align:center;">Tanggal</th>
								<th width="10%" style="text-align:center;">Nama Akun</th>
								<th width="10%" style="text-align:center;">Type</th>
								<th width="10%" style="text-align:center;">Deskripsi</th>
								<th width="10%" style="text-align:center;">Nominal</th>
								<th width="10%" style="text-align:center;">Catatan</th>
								<th width="10%" style="text-align:center;">Action</th>
							</tr>
							</thead>
							<tbody>
							<?php
								 for($x=0; $x<count($this->data); $x++){

										$nomer		= $x+1;
										$tgl_transaksi 	= $this->data[$x]['tgl_transaksi'];
									
										$nominal 	= $this->data[$x]['nominal'];
										$catatan 	= $this->data[$x]['catatan'];
										$nama_akun 	= $this->data[$x]['nama_akun'];
										$no_akun 	= $this->data[$x]['no_akun'];
										$type 	= $this->data[$x]['type'];
										$id 	= $this->data[$x]['id_akun'];
										$deskripsi= $this->data[$x]['deskripsi'];
										if ($this->data[$x]['type_transaksi']=="Cash In"){
											$type="Income";

										}else{
											 if ($deskripsi!=''){
											 	$type="Cost";

											 }else{
											 	$type="Expense";

											 }
											

										}
									
									?>	
											<td align="center"><?php echo $nomer;?></td>	  
											<td align="center"><?php echo $tgl_transaksi;?></td>
											<td align="center"><?php echo $nama_akun;?></td>
											<td align="center"><?php echo $type?>
											<td ><?php echo $deskripsi ?></td>
											<td ><?php echo 'Rp. '.number_format($nominal,0,",",".")?></td>
											<td ><?php echo $catatan;?></td>
											<td width="15%" align="center">
                                                <a href="#" title="Detail" onClick="editdata('<?php echo $id;?>')" class="btn-warning btn-sm mar-ed-button">Detail</a>
                                           
                                            </td>
                                          	
										</tr>	
									<?php 
										}
									?>
								
							</tbody>
						</table>
					  </div>
				</div>
            </div>
          </div>
          <!-- page end-->
        </div>
        <!-- /row -->
      </section>
      <!-- /wrapper -->
    </section>
    <!--main content end-->
    <?php require('partial/main-footer.php');?> 
  </section>
   <!-- js placed at the end of the document so the pages load faster -->
  <script src="lib/jquery/jquery.min.js"></script>
  <script type="text/javascript" language="javascript" src="lib/advanced-datatable/js/jquery.js"></script>
  <script src="lib/bootstrap/js/bootstrap.min.js"></script>
  <script class="include" type="text/javascript" src="lib/jquery.dcjqaccordion.2.7.js"></script>
  <script src="lib/jquery.scrollTo.min.js"></script>
  <script src="lib/jquery.nicescroll.js" type="text/javascript"></script>
  <script type="text/javascript" language="javascript" src="lib/advanced-datatable/js/jquery.dataTables.js"></script>
  <script type="text/javascript" src="lib/advanced-datatable/js/DT_bootstrap.js"></script>
   <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
  <script src="<?php echo $this->baseUrl();?>/lib/jquery-ui-1.9.2.custom.min.js"></script>
   <link href="<?php echo $this->baseUrl();?>/css/select2.min.css" rel="stylesheet">


    <script src="<?php echo $this->baseUrl();?>/lib/select2.full.min.js"></script>
  
		<script src="<?php echo $this->baseUrl();?>/lib/jquery.form.js"></script>
		<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl();?>/css/sweetalert.css">
		<script src="<?php echo $this->baseUrl();?>/lib/sweetalert.min.js"></script>
  
  <!--common script for all pages-->
  <script src="lib/common-scripts.js"></script>
  <!--script for this page-->
  <script type="text/javascript">

  $("#frm_postdata").hide();
  

  //function masking nominal
  function masking(id){
  	var biaya_kirim = document.getElementById(id).value;
    var biaya_kirim2 = biaya_kirim.replaceAll(".", "");
    var biaya_kirim3 = biaya_kirim2.toString().replaceAll(/(\d)(?=(\d\d\d)+(?!\d))/g, "$1.");
    document.getElementById(id).value=biaya_kirim3;
  }




  function tambahdata(){
	  $("#frm_postdata").show();
	  $("#tambah").hide();
	  document.getElementById('action').value="tambah";
  }
  
  function editdata(id){
		$("#frm_postdata").show();
		$("#tambah").hide();
				$(document).ready(function () {
		setTimeout(() => {
			$('#dataTables-detail').dataTable({
			"bPaginate": true,
			"bLengthChange": true,
			"bFilter": true,
			"bInfo": true,
			"bAutoWidth": true});
		}, 200)
	});


		
		var url = "<?php echo $this->baseUrl; ?>/transaksi/detaildata";
		var opt = {id:id};
		jQuery.get(url,opt, function(data) { 
			document.getElementById('frm_postdata').innerHTML = data;
			document.getElementById('action').value="edit";
		});
  $("#jenis_expense").select2();
    $("#nama_akun").select2();
  }
	function hapusdata(id){
			var r = confirm("Anda yakin akan menghapus data ini ?");
			if (r == true) {
					var url = "<?php echo $this->basePath; ?>/transaksi/hapusdata";
					var opt = {id:id}
					
					jQuery.get(url,opt, function(data) {	
						location.reload(true)
						//jQuery("div#example1").html(data);
						//jQuery("#page-content").html(data);
					})
					//open_url_to_div('<?php echo $this->baseUrl(); ?>/pengaduan/index');
					//location.reload(true)
			} else {
				close();
			}
		}
	
	function PostData(){
		//alert('Testing2');
        $("#frm_postdata").ajaxSubmit(post_data);
    }
	
	var post_data = {
		target:'',
		beforeSubmit: function() {	
			var tgl_transaksi = document.getElementById('tgl_transaksi').value;
			var jenis_expense = document.getElementById('jenis_expense').value;
			var nominal = document.getElementById('nominal').value;
			var catatan = document.getElementById('catatan').value;
			var nama_akun = document.getElementById('nama_akun').value;
			var type=$('[name="type"]').val();
			
				if (!tgl_transaksi) {
					document.getElementById('tgl_transaksi-error').innerHTML ="<span style='color: red;'>Tanggal transaksi belum diisi.</span>";
					document.getElementById('tgl_transaksi').focus();
					exit;
				}if (!jenis_expense) {
					document.getElementById('jenis_expense-error').innerHTML ="<span style='color: red;'>Jenis Expense belum dipilih.</span>";
					document.getElementById('jenis_expense').focus();
					exit;
				}
				else document.getElementById('jenis_expense-error').innerHTML ='';
				if (!nominal) {
					document.getElementById('nominal-error').innerHTML ="<span style='color: red;'>Status Harus Dipilih.</span>";
					document.getElementById('nominal').focus();
					exit;
				}else document.getElementById('nominal-error').innerHTML ='';
				if (!catatan) {
					document.getElementById('catatan-error').innerHTML ="<span style='color: red;'>Status Harus Dipilih.</span>";
					document.getElementById('catatan').focus();
					exit;
				}else document.getElementById('catatan-error').innerHTML ='';

				if (!type) {
					document.getElementById('type-error').innerHTML ="<span style='color: red;'>status keuangan  Harus Dipilih.</span>";
					
					exit;
				}else document.getElementById('type-error').innerHTML ='';
				

			}, 
		success:function(){	
			swal({
				    title: 'Tambah Liquid Berhasil !',
				    text: 'Auto Close...',
				    icon: 'success',
				    timer: 4000,
				    showConfirmButton: false,
				})
			//location.href="#";		
			location.reload(true);
		},
		url: '<?php echo $this->baseUrl();?>/transaksi/kirimdata',
		type: 'post',
		resetForm: false
	};
  </script>
  <script type="text/javascript">
  			$(document).ready(function(){
    $(function() {
      $('#tgl_transaksi').datepicker({
        dateFormat: 'yy-mm-dd',
        changeMonth: true,
        changeYear: true
      });
    });
  });
		
  </script>
</body>
  <script>
   $("#jenis_expense").select2();
    $("#nama_akun").select2();
  </script>

</html>
