<?php require('partial/header.php');?>
<?php require('partial/menu.php');?>    
<script>
	$(document).ready(function () {
		$('#dataTables-emp').dataTable({
			"bPaginate": true,
			"bLengthChange": true,
			"bFilter": true,
			"bInfo": true,
			"bAutoWidth": true});
	});
	 
</script>
    <!-- **********************************************************************************************************************************************************
        MAIN CONTENT
        *********************************************************************************************************************************************************** -->
    <!--main content start-->
    <section id="main-content">
      <section class="wrapper" style="min-height:522px">
        <h3><i class="fa fa-angle-right"></i> Data User</h3>
        <div class="row mb">
          <!-- page start-->
          <div class="content-panel">
            <div class="adv-table">
			<div id="listprogram" align="center"  class="col-xs-12">
				<br>
					<div id="page-content">
						<div class="form-group form-group-bottom" align="left" id="tambah">
							<button class="right btn btn-success  btn-xs" onClick="tambahdata()"><i class="fa fa-plus"></i>&nbsp;&nbsp;Tambah Data</button>		
						</div>
						
						
	<form id="frm_postdata" name="frm_postdata" enctype="multipart/form-data" method="POST">
		<input type="hidden" name="i_entry" id="i_entry" value="<?php echo $this->user_id;?>">
		<input type="hidden" id='action' name='action' value =''>
		<div class="panel">
            <fieldset class="panel-dt">	
				<h4 align="left"><u>Tambah Data</u></h4>
				<br>
					<div class="col-sm-12">
						<table width="100%">
							<tr>
								<td width="10%"><font style="font-size:12px;font-weight:bold;">Nama</font></td>
								<td width="1%">:</td>
								<td>
									<table>
										<td> <input name="nama" id="nama" type="text" maxlength="50" size="50" class="form-control input-sm" value=""> </td>
										<td> &nbsp; <label id="nama-error" for="nama" class="error"></td>
									</table>
								</td>
							</tr>
							<tr><td>&nbsp;</td></tr>
							<tr>
								<td width="10%"><font style="font-size:12px;font-weight:bold;">User ID</font></td>
								<td width="1%">:</td>
								<td>
									<table>
										<td> <input name="user_id" id="user_id" type="text" maxlength="20" size="30" class="form-control input-sm" onchange="checkData(this)" > </td>
										<td> &nbsp; <label id="user_id-error" for="user_id" class="error"></td>
									</table>
								</td>
							</tr> 
							<tr><td>&nbsp;</td></tr>
							<tr>
								<td width="10%"><font style="font-size:12px;font-weight:bold;">Email</font></td>
								<td width="1%">:</td>
								<td>
									<table>
										<td> <input name="email" id="email" type="email" maxlength="50" size="50" class="form-control input-sm" value=""> </td>
										<td> &nbsp; <label id="email-error" for="email" class="error"></td>
									</table>
								</td>
							</tr>
							<tr><td>&nbsp;</td></tr>
							<tr>
								<td width="10%"><font style="font-size:12px;font-weight:bold;">Groups</font></td>
								<td width="1%">:</td>
								<td>
									<table>
										<td> 
											<select id="group" name="group" class = "form-control input-sm" width="15%">
												<option value="0">--Pilih Group--</option>
												<?php  
													for($x=0; $x<count($this->group); $x++){ 
													$id = $this->group[$x]['id'];
													$group_name = $this->group[$x]['group_name'];
												?>
												<option value="<?php echo $id;?>"><?php echo $group_name;?></option>
												<?php } ?>
											</select>
										</td>
										<td> &nbsp; <label id="group-error" for="group" class="error"></td>
									</table>
								</td>
							</tr>
							<tr><td>&nbsp;</td></tr>
							<tr>
								<td width="10%"><font style="font-size:12px;font-weight:bold;">Password</font></td>
								<td width="1%">:</td>
								<td>
									<table>
										<td> <input name="password" id="password" type="password" maxlength="50" size="30" class="form-control input-sm" value=""> </td>
										<td> &nbsp; <label id="password-error" for="password" class="error"></td>
									</table>
								</td>
							</tr>
							<tr><td>&nbsp;</td></tr>
							<tr>
								<td width="10%"><font style="font-size:12px;font-weight:bold;">Ulangi Password</font></td>
								<td width="1%">:</td>
								<td>
									<table>
										<td> <input name="password2" id="password2" type="password" maxlength="50" size="30" class="form-control input-sm" value=""> </td>
										<td> &nbsp; <label id="password2-error" for="password2" class="error"></td>
									</table>
								</td>
							</tr>
							<tr><td>&nbsp;</td></tr>
						</table>
					</div>
				<div class="col-lg-12">
					<div class="form-group form-group-bottom" align="right">
						<input type="hidden" id="proses" name="proses" value="<?php echo $this->proses?>">	
						<br><br>
							<a href="user">
							<button type="button" class="btn btn-theme02">
								<span class="fa fa-backward"></span> &nbsp;Kembali
							</button></a>
							<button type="button" class="btn btn-theme03" onCLick="PostData()">
								<span class="fa fa-save"></span> &nbsp;Simpan
							</button>
					</div>
				</div>
			</fieldset>
		</div>
	</form>			
						
						<table style="font-size:12px;" class="table table-striped table-bordered table-hover" id="dataTables-emp">
							<thead>
							<tr bgcolor="#4ECDC4">
								<th width="3%" style="text-align:center;">No</th>
								<th width="7%" style="text-align:center;">Nama</th>
								<th width="10%" style="text-align:center;">User ID</th>
								<th width="10%" style="text-align:center;">Email</th>
								<th width="10%" style="text-align:center;">Group</th>
								<th width="10%" style="text-align:center;">Admin</th>
								<th width="10%" style="text-align:center;">Tgl Entry</th>
								<th width="10%" style="text-align:center;">Edit</th>
								<th width="10%" style="text-align:center;">Hapus</th>
							</tr>
							</thead>
							<tbody>
							<?php
								 for($x=0; $x<count($this->data); $x++){

										$nomer		= $x+1;
										$user_id 	= $this->data[$x]['user_id'];
										$nama 	= $this->data[$x]['nama'];
										$email 	= $this->data[$x]['email'];
										$group 	= $this->data[$x]['group'];
										$i_entry 	= $this->data[$x]['i_entry'];
										$d_entry 	= $this->data[$x]['d_entry'];
										
										$nama_group = $this->User_Service->getdatagroup($group);
									?>	
											<td align="center"><?php echo $nomer;?></td>	  
											<td align="center"><?php echo $nama;?></td>
											<td align="center"><?php echo $user_id;?></td>
											<td align="center"><?php echo $email;?></td>
											<td align="center"><?php echo $nama_group;?></td>
											<td align="center"><?php echo $i_entry;?></td>
											<td align="center"><?php echo $d_entry;?></td>
											<td width="7%">
                                                <a href="#" title="Edit" onClick="editdata('<?php echo $user_id;?>')" class="btn-warning btn-sm mar-ed-button"><i class="fa fa-edit pad-ico-button"></i>Edit</a>
                                            </td>
                                            <td width="8%">
												<a href="#" title="Hapus" onclick="hapusdata('<?php echo $user_id; ?>')" class="btn-danger btn-sm mar-ed-button"><i class="fa fa-trash-o pad-ico-button"></i>Hapus</a>
                                            </td>	
										</tr>	
									<?php 
										}
									?>
								
							</tbody>
						</table>
					  </div>
				</div>
            </div>
          </div>
          <!-- page end-->
        </div>
        <!-- /row -->
      </section>
      <!-- /wrapper -->
    </section>
    <!--main content end-->
    <?php require('partial/main-footer.php');?> 
  </section>
   <!-- js placed at the end of the document so the pages load faster -->
  <script src="lib/jquery/jquery.min.js"></script>
  <script type="text/javascript" language="javascript" src="lib/advanced-datatable/js/jquery.js"></script>
  <script src="lib/bootstrap/js/bootstrap.min.js"></script>
  <script class="include" type="text/javascript" src="lib/jquery.dcjqaccordion.2.7.js"></script>
  <script src="lib/jquery.scrollTo.min.js"></script>
  <script src="lib/jquery.nicescroll.js" type="text/javascript"></script>
  <script type="text/javascript" language="javascript" src="lib/advanced-datatable/js/jquery.dataTables.js"></script>
  <script type="text/javascript" src="lib/advanced-datatable/js/DT_bootstrap.js"></script>
  
		<script src="<?php echo $this->baseUrl();?>/lib/jquery.form.js"></script>
		<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl();?>/css/sweetalert.css">
		<script src="<?php echo $this->baseUrl();?>/lib/sweetalert.min.js"></script>
  
  <!--common script for all pages-->
  <script src="lib/common-scripts.js"></script>
  <!--script for this page-->
  <script type="text/javascript">
  $("#frm_postdata").hide();
  
  function tambahdata(){
	  $("#frm_postdata").show();
	  $("#tambah").hide();
	  document.getElementById('action').value="tambah";
  }
  
  function editdata(user_id){
		$("#frm_postdata").show();
		$("#tambah").hide();
		
		var url = "<?php echo $this->baseUrl; ?>/user/editdata";
		var opt = {user_id:user_id};
		jQuery.get(url,opt, function(data) { 
			document.getElementById('frm_postdata').innerHTML = data;
			document.getElementById('action').value="edit";
		});
  }
	function hapusdata(user_id){
			var r = confirm("Anda yakin akan menghapus data ini ?");
			if (r == true) {
					var url = "<?php echo $this->basePath; ?>/user/hapusdata";
					var opt = {user_id:user_id}
					
					jQuery.get(url,opt, function(data) {	
						location.reload(true)
						//jQuery("div#example1").html(data);
						//jQuery("#page-content").html(data);
					})
					//open_url_to_div('<?php echo $this->baseUrl(); ?>/pengaduan/index');
					//location.reload(true)
			} else {
				close();
			}
		}
	
	function validateEmail(email) {
		  var re = /^(([^<>()[\]\\.,;:\s@\"]+(\.[^<>()[\]\\.,;:\s@\"]+)*)|(\".+\"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/;
		  return re.test(email);
	}
	
	function PostData(){
		//alert('Testing2');
        $("#frm_postdata").ajaxSubmit(post_data);
    }
	
	var post_data = {
		target:'',
		beforeSubmit: function() {	
			var nama = document.getElementById('nama').value;
			var user_id = document.getElementById('user_id').value;
			var email = document.getElementById('email').value;
			var group = document.getElementById('group').value;
			var password = document.getElementById('password').value;
			var password2 = document.getElementById('password2').value;
				if (!nama) {
					document.getElementById('nama-error').innerHTML ="<span style='color: red;'>Nama Harus Diisi.</span>";
					document.getElementById('nama').focus();
					exit;
				}else document.getElementById('nama-error').innerHTML ='';
				if (!user_id) {
					document.getElementById('user_id-error').innerHTML ="<span style='color: red;'>User ID Harus Diisi.</span>";
					document.getElementById('user_id').focus();
					exit;
				}else document.getElementById('user_id-error').innerHTML ='';
				if (!email) {
					document.getElementById('email-error').innerHTML ="<span style='color: red;'>email Harus Diisi.</span>";
					document.getElementById('email').focus();
					exit;
				}else document.getElementById('email-error').innerHTML ='';
				if (validateEmail(email)) {
					document.getElementById('email-error').innerHTML ='';
				}else { 
					document.getElementById('email-error').innerHTML ="<span style='color: red;'>Email Salah.</span>";
					document.getElementById('email').focus();
					exit;
				}
				if (group == '0') {
					document.getElementById('group-error').innerHTML ="<span style='color: red;'>Group Harus Dipilih.</span>";
					document.getElementById('group').focus();
					exit;
				}else document.getElementById('group-error').innerHTML ='';
				
				if (!password) {
					document.getElementById('password-error').innerHTML ="<span style='color: red;'>Password Harus Diisi.</span>";
					document.getElementById('password').focus();
					exit;
				}else document.getElementById('password-error').innerHTML ='';
				if (!password2) {
					document.getElementById('password2-error').innerHTML ="<span style='color: red;'>Ulang Password.</span>";
					document.getElementById('password2').focus();
					exit;
				}else document.getElementById('password2-error').innerHTML ='';
				if (password == password2) {
					document.getElementById('password2-error').innerHTML ='';
				} else {
					document.getElementById('password2-error').innerHTML ="<span style='color: red;'>Password Tidak Cocok.</span>";
					document.getElementById('password2').focus();
					exit;
				}
			}, 
		success:function(){	
			swal({
				    title: 'Tambah Liquid Berhasil !',
				    text: 'Auto Close...',
				    icon: 'success',
				    timer: 4000,
				    showConfirmButton: false,
				})
			//location.href="#";		
			location.reload(true);
		},
		url: '<?php echo $this->baseUrl();?>/user/kirimdata',
		type: 'post',
		resetForm: false
	};
	
	function checkData(input){
			var user_id = input.value;
					
			var url = "<?php echo $this->baseUrl; ?>/user/cekdatauser";
			var opt = {user_id:user_id};
		
			jQuery.get(url,opt, function(data) {	
			//alert(data);
				if(data != '0'){
					document.getElementById('user_id-error').innerHTML ="<span style='color: red;'>User ID sudah terdaftar.</span>";
					document.getElementById('user_id').focus();
					document.getElementById('user_id').value = '';
				}else document.getElementById('user_id-error').innerHTML ='';
			});
			
			//alert(test);
	}
	
	function PostDataEdit(){
		//alert('Testing2');
        $("#frm_postdata").ajaxSubmit(post_dataedit);
    }
	
	var post_dataedit = {
		target:'',
		beforeSubmit: function() {	
			var nama = document.getElementById('nama').value;
			var user_id = document.getElementById('user_id').value;
			var email = document.getElementById('email').value;
			var group = document.getElementById('group').value;
				if (!nama) {
					document.getElementById('nama-error').innerHTML ="<span style='color: red;'>Nama Harus Diisi.</span>";
					document.getElementById('nama').focus();
					exit;
				}else document.getElementById('nama-error').innerHTML ='';
				if (!user_id) {
					document.getElementById('user_id-error').innerHTML ="<span style='color: red;'>User ID Harus Diisi.</span>";
					document.getElementById('user_id').focus();
					exit;
				}else document.getElementById('user_id-error').innerHTML ='';
				if (!email) {
					document.getElementById('email-error').innerHTML ="<span style='color: red;'>email Harus Diisi.</span>";
					document.getElementById('email').focus();
					exit;
				}else document.getElementById('email-error').innerHTML ='';
				if (validateEmail(email)) {
					document.getElementById('email-error').innerHTML ='';
				}else { 
					document.getElementById('email-error').innerHTML ="<span style='color: red;'>Email Salah.</span>";
					document.getElementById('email').focus();
					exit;
				}
				if (group == '0') {
					document.getElementById('group-error').innerHTML ="<span style='color: red;'>Group Harus Dipilih.</span>";
					document.getElementById('group').focus();
					exit;
				}else document.getElementById('group-error').innerHTML ='';
			}, 
		success:function(){	
			swal({
				    title: 'Tambah Liquid Berhasil !',
				    text: 'Auto Close...',
				    icon: 'success',
				    timer: 4000,
				    showConfirmButton: false,
				})
			//location.href="#";		
			location.reload(true);
		},
		url: '<?php echo $this->baseUrl();?>/user/kirimdata',
		type: 'post',
		resetForm: false
	};
  </script>
</body>

</html>
