<form id="frm_postdata" name="frm_postdata" enctype="multipart/form-data" method="POST">
		<input type="hidden" name="i_entry" id="i_entry" value="<?php echo $this->user_id;?>">
		<input type="hidden" id='action' name='action' value =''>
		<div class="panel">
            <fieldset class="panel-dt">	
				<h4 align="left"><u>Edit User</u></h4>
				<br>
					<div class="col-sm-12">
						<table width="100%">
							<tr>
								<td width="10%"><font style="font-size:12px;font-weight:bold;">Nama</font></td>
								<td width="1%">:</td>
								<td>
									<table>
										<td> <input name="nama" id="nama" type="text" maxlength="50" size="50" class="form-control input-sm" value="<?php echo $this->data[0]['nama'];?>"> </td>
										<td> &nbsp; <label id="nama-error" for="nama" class="error"></td>
									</table>
								</td>
							</tr>
							<tr><td>&nbsp;</td></tr>
							<tr>
								<td width="10%"><font style="font-size:12px;font-weight:bold;">User ID</font></td>
								<td width="1%">:</td>
								<td>
									<table>
										<td> <input name="user_id" id="user_id" type="text" maxlength="20" size="30" class="form-control input-sm" value="<?php echo $this->data[0]['user_id'];?>" readonly> </td>
										<td> &nbsp; <label id="user_id-error" for="user_id" class="error"></td>
									</table>
								</td>
							</tr> 
							<tr><td>&nbsp;</td></tr>
							<tr>
								<td width="10%"><font style="font-size:12px;font-weight:bold;">Email</font></td>
								<td width="1%">:</td>
								<td>
									<table>
										<td> <input name="email" id="email" type="email" maxlength="50" size="50" class="form-control input-sm" value="<?php echo $this->data[0]['email'];?>"> </td>
										<td> &nbsp; <label id="email-error" for="email" class="error"></td>
									</table>
								</td>
							</tr>
							<tr><td>&nbsp;</td></tr>
							<tr>
								<td width="10%"><font style="font-size:12px;font-weight:bold;">Groups</font></td>
								<td width="1%">:</td>
								<td>
									<table>
										<?php 
											$group = $this->data[0]['group'];
											$selected = 'selected';
										?>
										<td> 
											<select id="group" name="group" class = "form-control input-sm" width="15%">
												<option value="0">--Pilih Group--</option>
												<?php  
													for($x=0; $x<count($this->group); $x++){ 
													$id = $this->group[$x]['id'];
													$group_name = $this->group[$x]['group_name'];
												?>
												<option value="<?php echo $id;?>" <?php if($group == $id){ echo $selected; } ?>><?php echo $group_name;?></option>
												<?php } ?>
											</select>
										</td>
										<td> &nbsp; <label id="group-error" for="group" class="error"></td>
									</table>
								</td>
							</tr>
							<tr><td>&nbsp;</td></tr>
						</table>
					</div>
				<div class="col-lg-12">
					<div class="form-group form-group-bottom" align="right">
						<input type="hidden" id="proses" name="proses" value="<?php echo $this->proses?>">	
						<br><br>
							<a href="user">
							<button type="button" class="btn btn-theme02">
								<span class="fa fa-backward"></span> &nbsp;Kembali
							</button></a>
							<button type="button" class="btn btn-theme03" onCLick="PostDataEdit()">
								<span class="fa fa-save"></span> &nbsp;Simpan
							</button>
					</div>
				</div>
			</fieldset>
		</div>
	</form>