<script>
	$(document).ready(function () {
		$('#dataTables-emp').dataTable({
			"bPaginate": true,
			"bLengthChange": true,
			"bFilter": true,
			"bInfo": true,
			"bAutoWidth": true});
	});
	 
</script>
			<div id="listprogram" align="center"  class="col-xs-12">
				<br>
					<div id="page-content">
						<div class="form-group form-group-bottom" align="left">
							<b><u>HYSTORY PENYELESAIAN RETUR PENJUALAN</u></b>	
						</div>
						<table style="font-size:12px;" class="table table-striped table-bordered table-hover" id="dataTables-emp">
							<thead>
							<tr bgcolor="#4ECDC4">
								<th width="3%" style="text-align:center;">No</th>
								<th width="7%" style="text-align:center;">Nomor Retur</th>
								<th width="10%" style="text-align:center;">Tanggal Retur</th>
								<th width="7%" style="text-align:center;">Nomor Invoice</th>
								<th width="10%" style="text-align:center;">Tanggal Invoice</th>
								<th width="20%" style="text-align:center;">Nama Supplier</th>
								<th width="10%" style="text-align:center;">Selisih Pembayaran</th>
								<th width="10%" style="text-align:center;">Action</th>
							</tr>
							</thead>
							<tbody>
							<?php
								 for($x=0; $x<count($this->data); $x++){

										$nomer			= $x+1;
										$no_invoice 		= $this->data[$x]['no_invoice'];
										$tgl_invoice	 	= date_create($this->data[$x]['tgl_invoice']);
										$tgl_invoice		= date_format($tgl_invoice,"d-m-Y");
										$sisa_bayar	 	= number_format($this->data[$x]['sisa_bayar'],0,",",".");
										$kode_customer 	= $this->data[$x]['kode_customer'];
										$no_retur 		= $this->data[$x]['no_retur'];
										$tgl_retur	 	= date_create($this->data[$x]['tgl_retur']);
										$tgl_retur		= date_format($tgl_retur,"d-m-Y");
										
										$customer = $this->Penyelesaianpenjualan_Service->getdatasupplierid($kode_customer);
										$nama_customer  = $customer[0]['nama_customer'];
									?>	
										<tr>
											<td align="center"><?php echo $nomer;?></td>	
											<td align="center"><?php echo $no_retur;?></td>
											<td align="center"><?php echo $tgl_retur;?></td>	
											<td align="center"><?php echo $no_invoice;?></td>
											<td align="center"><?php echo $tgl_invoice;?></td>
											<td align="center"><?php echo $nama_customer;?></td>
											<td align="center"><?php echo $sisa_bayar;?></td>
											<td width="7%" align="center">
												<a href="#" title="Detail" onclick="open_url_to_div('/penyelesaianpenjualan/detail?id=<?php echo $no_retur;?>')" class="btn-warning btn-sm mar-ed-button">Detail</a>
                                            </td>
										</tr>	
									<?php 
										}
									?>
								
							</tbody>
						</table>
					  </div>
				</div>
            
   <!-- js placed at the end of the document so the pages load faster -->
  <script src="<?php echo $this->baseUrl();?>/lib/jquery.form.js"></script>
  <link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl();?>/css/sweetalert.css">
  <script src="<?php echo $this->baseUrl();?>/lib/sweetalert.min.js"></script>   
  <script src="<?php echo $this->baseUrl();?>/lib/jquery.scrollTo.min.js"></script>
  <script src="<?php echo $this->baseUrl();?>/lib/jquery.nicescroll.js" type="text/javascript"></script>
  <!--script for this page-->
  <script type="text/javascript">
	function hapusdata(no_invoice){
			var r = confirm("Anda yakin akan menghapus data ini ?");
			if (r == true) {
					var url = "<?php echo $this->basePath; ?>/penyelesaianpenjualan/hapusdata";
					var opt = {no_invoice:no_invoice}
					
					jQuery.get(url,opt, function(data) {	
						location.reload(true)
						//jQuery("div#example1").html(data);
						//jQuery("#page-content").html(data);
					})
					//open_url_to_div('<?php echo $this->baseUrl(); ?>/pengaduan/index');
					//location.reload(true)
			} else {
				close();
			}
		}
  </script>
</body>

</html>
