<form id="frm_postdata" name="frm_postdata" enctype="multipart/form-data" method="POST">
	<input type="hidden" name="currentPage" id="currentPage" size="6" maxlength="6" value="<?php echo $this->numPage;?>" class="inputbox2 narrowkey1"></input>
		<?php 
			$seq = substr($this->seq,6,5);
			//var_dump($seq);
			$seq += 1;
			$seq=str_pad($seq, 2, '0', STR_PAD_LEFT);
		?>
		<input type="hidden" id='seq' value ='<?php echo $seq;?>'>
		<div class="panel">
            <fieldset class="panel-dt">							
				<h4><i class="fa fa-angle-right"></i> Tambah Data Isi Ulang 3 (Liquid)</h4>
						<br>
					<div class="col-sm-12">
						<table width="100%">
							<tr>
								<td width="10%"><font style="font-size:12px;font-weight:bold;">ID Volume</font></td>
								<td width="1%">:</td>
								<td>
									<table>
										<td> <input name="id_volume" id="id_volume" type="text" maxlength="4" size="10" class="form-control input-sm" value="VL<?php echo $seq;?>" readonly> </td>
										<td> &nbsp; <label id="id_volume-error" for="id_volume" class="error"></td>
									</table>
								</td>
							</tr> 
							<tr><td>&nbsp;</td></tr>
							<tr>
								<td width="10%"><font style="font-size:12px;font-weight:bold;">Volume</font></td>
								<td width="1%">:</td>
								<td>
									<table>
										<td> <input name="volume" id="volume" type="text" maxlength="5" size="10" class="form-control input-sm" value=""> </td>
										<td> &nbsp; <label id="volume-error" for="volume" class="error"></td>
									</table>
								</td>
							</tr>
							<tr><td>&nbsp;</td></tr>
						</table>
					</div>				
			</fieldset>
		</div>
		<div class="col-lg-12">
			<div class="form-group form-group-bottom" align="right">
						<input type="hidden" id="proses" name="proses" value="<?php echo $this->proses?>">	
						<br><br>
							
							<a href="liquid">
							<button type="button" class="btn btn-theme02">
								<span class="fa fa-backward"></span> &nbsp;Kembali
							</button></a>
							<button type="button" class="btn btn-theme03" onCLick="PostData()">
								<span class="fa fa-save"></span> &nbsp;Simpan
							</button>
							
			</div>
		</div>
</form>
  <script src="<?php echo $this->baseUrl();?>/lib/jquery/jquery.min.js"></script>
  <script src="<?php echo $this->baseUrl();?>/lib/bootstrap/js/bootstrap.min.js"></script>
  <script src="<?php echo $this->baseUrl();?>/lib/jquery.form.js"></script>
  <link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl();?>/css/sweetalert.css">
  <script src="<?php echo $this->baseUrl();?>/lib/sweetalert.min.js"></script>
<script>
	function getSelectValue(){
		var selectedValue = document.getElementById("kode_supplier").value;
		var res = selectedValue.split(",");
		var kode_supplier = res[0];
		var alamat = res[1];
		var tipe = res[2];
		var res2 = tipe.substring(0,1);
		var volume = document.getElementById("volume").value;
		var seq = document.getElementById("seq").value;
		
		var id_kode_barang = res2+'-L'+volume;
		var url = "<?php echo $this->baseUrl; ?>/liquid/cekseq";
			var opt = {id_kode_barang:id_kode_barang};
		
			jQuery.get(url,opt, function(data) {	
			//alert(data);
				if(data == ''){
					data2='0';
				} else {
					data2=data;
				}
				var hasilseq = parseInt(data2) + parseInt(1);
				var str = "" + hasilseq
				var pad = "00000"
				var ans = pad.substring(0, pad.length - str.length) + str
				
				var kode = id_kode_barang+'-'+ans;
				document.getElementById("kode_barang").value = kode;
				
				document.getElementById("id_kode_barang").value = id_kode_barang;
				document.getElementById("seq_kode_barang").value = hasilseq;
			});
		
		document.getElementById("kode_supplier2").value = kode_supplier;
		document.getElementById("alamat_supplier").value = alamat;
		document.getElementById("tipe").value = tipe;
	}
	
	function getKode(){
		var tipe = document.getElementById("tipe").value;
		var res = tipe.substring(0,1);
		var volume = document.getElementById("volume").value;
		var seq = document.getElementById("seq").value;
		
		var id_kode_barang = res+'-L'+volume;
		var url = "<?php echo $this->baseUrl; ?>/liquid/cekseq";
			var opt = {id_kode_barang:id_kode_barang};
		
			jQuery.get(url,opt, function(data) {	
			//alert(data);
				if(data == ''){
					data2='0';
				} else {
					data2=data;
				}
				var hasilseq = parseInt(data2) + parseInt(1);
				var str = "" + hasilseq
				var pad = "00000"
				var ans = pad.substring(0, pad.length - str.length) + str
				
				var kode = id_kode_barang+'-'+ans;
				document.getElementById("kode_barang").value = kode;
				
				document.getElementById("id_kode_barang").value = id_kode_barang;
				document.getElementById("seq_kode_barang").value = hasilseq;
			});
	}
                                                                                                                                     
	
	function PostData(){
		//alert('Testing2');
        $("#frm_postdata").ajaxSubmit(post_data);
    }
	
	var post_data = {
		target:'',
		beforeSubmit: function() {	
			var kode_supplier2 	  = document.getElementById("kode_supplier2").value;
			var volume		      = document.getElementById('volume').value;
			var kode_barang 	  = document.getElementById('kode_barang').value;
			var merk_barang 	  = document.getElementById('merk_barang').value;
			var nama_barang 	  = document.getElementById('nama_barang').value;
			var kode_rasa	 	  = document.getElementById('kode_rasa').value;
			var nic			 	  = document.getElementById('nic').value;
			var berat 	  		  = document.getElementById('berat').value;
			var stok_pusat 	  	  = document.getElementById('stok_pusat').value;
			var stok_retail 	  = document.getElementById('stok_retail').value;
			var stok_studio 	  = document.getElementById('stok_studio').value;
			var bad_stock    	  = document.getElementById('bad_stock').value;
			var harga_beli 	  	  = document.getElementById('harga_beli').value;
			var hj_agen 	  	  = document.getElementById('hj_agen').value;
			var hj_retail 	  	  = document.getElementById('hj_retail').value;
			var hj_whs 	  		  = document.getElementById('hj_whs').value;
			var status 			  = document.getElementById('status').value;
			
				if (!kode_supplier2) {
					document.getElementById('kode_supplier-error').innerHTML ="<span style='color: red;'>Supplier Harus Dipilih.</span>";
					document.getElementById('kode_supplier').focus();
					exit;
				}else document.getElementById('kode_supplier-error').innerHTML ='';
				
				if (volume=='0') {
					document.getElementById('volume-error').innerHTML ="<span style='color: red;'>Volume Harus Dipilih.</span>";
					document.getElementById('volume').focus();
					exit;
				}else document.getElementById('volume-error').innerHTML ='';
				
				if (!merk_barang) {
					document.getElementById('merk_barang-error').innerHTML ="<span style='color: red;'>Merk Liquid Harus Diisi.</span>";
					document.getElementById('merk_barang').focus();
					exit;
				}else document.getElementById('merk_barang-error').innerHTML ='';
				
				if (!nama_barang) {
					document.getElementById('nama_barang-error').innerHTML ="<span style='color: red;'>Nama Liquid Harus Diisi.</span>";
					document.getElementById('nama_barang').focus();
					exit;
				}else document.getElementById('nama_barang-error').innerHTML ='';
				
				if (kode_rasa=='0') {
					document.getElementById('kode_rasa-error').innerHTML ="<span style='color: red;'>Rasa Harus Dipilih.</span>";
					document.getElementById('kode_rasa').focus();
					exit;
				}else document.getElementById('kode_rasa-error').innerHTML ='';
				
				if (!nic) {
					document.getElementById('nic-error').innerHTML ="<span style='color: red;'>Nicotin Harus Diisi.</span>";
					document.getElementById('nic').focus();
					exit;
				}else document.getElementById('nic-error').innerHTML ='';
				
				if (!berat) {
					document.getElementById('berat-error').innerHTML ="<span style='color: red;'>Berat Harus Diisi.</span>";
					document.getElementById('berat').focus();
					exit;
				}else document.getElementById('berat-error').innerHTML ='';
				
				if (!stok_pusat) {
					document.getElementById('stok_pusat-error').innerHTML ="<span style='color: red;'>Stok Gudang Pusat Harus Diisi.</span>";
					document.getElementById('stok_pusat').focus();
					exit;
				}else document.getElementById('stok_pusat-error').innerHTML ='';
				
				if (!stok_retail) {
					document.getElementById('stok_retail-error').innerHTML ="<span style='color: red;'>Stok Gudang Retail Harus Diisi.</span>";
					document.getElementById('stok_retail').focus();
					exit;
				}else document.getElementById('stok_retail-error').innerHTML ='';
				
				if (!stok_studio) {
					document.getElementById('stok_studio-error').innerHTML ="<span style='color: red;'>Stok Gudang Studio Harus Diisi.</span>";
					document.getElementById('stok_studio').focus();
					exit;
				}else document.getElementById('stok_studio-error').innerHTML ='';
				
				if (!bad_stock) {
					document.getElementById('bad_stock-error').innerHTML ="<span style='color: red;'>Bad Stock Harus Diisi.</span>";
					document.getElementById('bad_stock').focus();
					exit;
				}else document.getElementById('bad_stock-error').innerHTML ='';
				
				if (!harga_beli) {
					document.getElementById('harga_beli-error').innerHTML ="<span style='color: red;'>Harga Beli Harus Diisi.</span>";
					document.getElementById('harga_beli').focus();
					exit;
				}else document.getElementById('harga_beli-error').innerHTML ='';
				
				if (!hj_agen) {
					document.getElementById('hj_agen-error').innerHTML ="<span style='color: red;'>Harga Jual Agn Harus Diisi.</span>";
					document.getElementById('hj_agen').focus();
					exit;
				}else document.getElementById('hj_agen-error').innerHTML ='';
				
				if (!hj_retail) {
					document.getElementById('hj_retail-error').innerHTML ="<span style='color: red;'>Harga Jual Ret Harus Diisi.</span>";
					document.getElementById('hj_retail').focus();
					exit;
				}else document.getElementById('hj_retail-error').innerHTML ='';
				
				if (!hj_whs) {
					document.getElementById('hj_whs-error').innerHTML ="<span style='color: red;'>Harga Jual WS Harus Diisi.</span>";
					document.getElementById('hj_whs').focus();
					exit;
				}else document.getElementById('hj_whs-error').innerHTML ='';
				
				if (status=='') {
					document.getElementById('status-error').innerHTML ="<span style='color: red;'>Status Harus Dipilih.</span>";
					document.getElementById('status').focus();
					exit;
				}else document.getElementById('status-error').innerHTML ='';
			}, 
		success:function(){	
			swal({
				    title: 'Tambah Liquid Berhasil !',
				    text: 'Auto Close...',
				    icon: 'success',
				    timer: 4000,
				    showConfirmButton: false,
				})
			location.href="#";		
			location.reload(true)
		},
		url: '<?php echo $this->baseUrl();?>/liquid/kirimdata',
		type: 'post',
		resetForm: false
	};
	
	function isNumber(evt) {
        var iKeyCode = (evt.which) ? evt.which : evt.keyCode
        if (iKeyCode != 46 && iKeyCode > 31 && (iKeyCode < 48 || iKeyCode > 57))
            return false;

        return true;
    } 
	
	function currency(){
		var harga_beli = document.getElementById("harga_beli").value;
		var harga_beli2 = harga_beli.replaceAll(".", "");
		var harga_beli3 = harga_beli2.toString().replaceAll(/(\d)(?=(\d\d\d)+(?!\d))/g, "$1.");
		document.getElementById("harga_beli").value=harga_beli3;
		
		var hj_agen = document.getElementById("hj_agen").value;
		var hj_agen2 = hj_agen.replaceAll(".", "");
		var hj_agen3 = hj_agen2.toString().replaceAll(/(\d)(?=(\d\d\d)+(?!\d))/g, "$1.");
		document.getElementById("hj_agen").value=hj_agen3;
		
		var hj_retail = document.getElementById("hj_retail").value;
		var hj_retail2 = hj_retail.replaceAll(".", "");
		var hj_retail3 = hj_retail2.toString().replaceAll(/(\d)(?=(\d\d\d)+(?!\d))/g, "$1.");
		document.getElementById("hj_retail").value=hj_retail3;
		
		var hj_whs = document.getElementById("hj_whs").value;
		var hj_whs2 = hj_whs.replaceAll(".", "");
		var hj_whs3 = hj_whs2.toString().replaceAll(/(\d)(?=(\d\d\d)+(?!\d))/g, "$1.");
		document.getElementById("hj_whs").value=hj_whs3;
	}
</script>