<head>
  <link href="<?php echo $this->baseUrl();?>/css/select2.min.css" rel="stylesheet">
  <link href="<?php echo $this->baseUrl();?>/css/fileinput/fileinput.min.css" rel="stylesheet">
  <script src="<?php echo $this->baseUrl();?>/lib/select2.full.min.js"></script>
  <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
  <script src="<?php echo $this->baseUrl();?>/lib/jquery-ui-1.9.2.custom.min.js"></script>
</head>
<form id="frm_postdata" name="frm_postdata" enctype="multipart/form-data" method="POST">
	<input type="hidden" name="currentPage" id="currentPage" size="6" maxlength="6" value="<?php echo $this->numPage;?>" class="inputbox2 narrowkey1"></input>
		<?php 
			$seq = substr($this->seq,6,5);
			//var_dump($seq);
			$seq += 1;
			$seq=str_pad($seq, 5, '0', STR_PAD_LEFT);
		?>
		<input type="hidden" id='seq' value ='<?php echo $seq;?>'>
		<div class="panel">
            <fieldset class="panel-dt">							
				<h4><i class="fa fa-angle-right"></i> Edit Data Isi Ulang (Liquid)</h4>
						<br>
					<div class="col-sm-12">
						<table width="100%">
							<tr>
								<td width="10%"><font style="font-size:12px;font-weight:bold;">Nama Supplier</font></td>
								<td width="1%">:</td>
								<td><?php
										$kode_supplier = $this->data[0]['kode_supplier'];
										$supplier = $this->Liquid_Service->getNamaSupplier($kode_supplier);
									?>
									<table>
										<td> <input name="nama_supplier" id="nama_supplier" type="text" maxlength="50" size="20" class="form-control input-sm" value="<?php echo $supplier;?>" readonly> </td>
										<td> 
											<input name="kode_supplier2" id="kode_supplier2" type="hidden" value="<?php echo $this->data[0]['kode_supplier'];?>">
											&nbsp; <label id="kode_supplier2-error" for="kode_supplier2" class="error">
										</td>
									</table>
								</td>
							</tr> 
							<tr><td>&nbsp;</td></tr>
							<tr>
								<td width="10%"><font style="font-size:12px;font-weight:bold;">Alamat Supplier</font></td>
								<td width="1%">:</td>
								<td>
									<table>
										<td> <input name="alamat_supplier" id="alamat_supplier" type="text" maxlength="100" size="100" class="form-control input-sm" value="<?php echo $this->data2[0]['alamat_supplier']?>" readonly> </td>
										<td> </td>
									</table>
								</td>
							</tr> 
							<tr><td>&nbsp;</td></tr>
							<tr>
								<td width="10%"><font style="font-size:12px;font-weight:bold;">Status Supplier</font></td>
								<td width="1%">:</td>
								<td>
									<table>
										<td> <input name="tipe" id="tipe" type="text" maxlength="10" size="10" class="form-control input-sm" value="<?php echo $this->data2[0]['tipe']?>" readonly> </td>
										<td> </td>
									</table>
								</td>
							</tr> 
							<tr><td>&nbsp;</td></tr>
							<tr>
								<td width="10%"><font style="font-size:12px;font-weight:bold;">Volume</font></td>
								<td width="1%">:</td>
								<td>
									<table>
										<td> <input name="volume" id="volume" type="text" maxlength="50" size="20" class="form-control input-sm" value="<?php echo $this->data[0]['volume'];?>" readonly> </td>
										<td> &nbsp; <label id="volume-error" for="volume" class="error"></td>
									</table>
								</td>
							</tr> 
							<!--tr>
								<td width="10%"><font style="font-size:12px;font-weight:bold;">Volume</font></td>
								<td width="1%">:</td>
								<td>
									<table>
										<td> <?php
											 $volume_data =  $this->data[0]['volume'];
											 $selected2 = 'selected';
											 ?>
											<select id="volume" name="volume" class = "form-control input-sm" width="15%" onchange="getKode();">
												<option value="0">--Pilih Volume--</option>
												<option value="15" <?php if($volume_data == '15'){echo $selected2;}?>>15</option>
												<option value="30" <?php if($volume_data == '30'){echo $selected2;}?>>30</option>
												<option value="60" <?php if($volume_data == '60'){echo $selected2;}?>>60</option>
												<option value="100" <?php if($volume_data == '100'){echo $selected2;}?>>100</option>
											</select>
										</td>
										<td> &nbsp; <label id="volume-error" for="volume" class="error"></td>
									</table>
								</td>
							</tr--> 
							<tr><td>&nbsp;</td></tr>
							<tr>
								<td width="10%"><font style="font-size:12px;font-weight:bold;">Kode Liquid</font></td>
								<td width="1%">:</td>
								<td>
									<table>
										<td> <input name="kode_barang" id="kode_barang" type="text" maxlength="50" size="20" class="form-control input-sm" value="<?php echo $this->data[0]['kode_barang']?>" readonly> </td>
										<td> &nbsp; <label id="kode_barang-error" for="kode_barang" class="error"></td>
									</table>
								</td>
							</tr> 
							<tr><td>&nbsp;</td></tr>
							<tr>
								<td width="10%"><font style="font-size:12px;font-weight:bold;">Merk Liquid</font></td>
								<td width="1%">:</td>
								<td>
									<table>
										<td> <input name="merk_barang" id="merk_barang" type="text" maxlength="50" size="20" class="form-control input-sm" value="<?php echo $this->data[0]['merk_barang']?>"> </td>
										<td> &nbsp; <label id="merk_barang-error" for="merk_barang" class="error"></td>
									</table>
								</td>
							</tr>
							<tr><td>&nbsp;</td></tr>
							<tr>
								<td width="10%"><font style="font-size:12px;font-weight:bold;">Nama Liquid</font></td>
								<td width="1%">:</td>
								<td>
									<table>
										<td> <input name="nama_barang" id="nama_barang" type="text" maxlength="50" size="50" class="form-control input-sm" value="<?php echo $this->data[0]['nama_barang']?>"> </td>
										<td> &nbsp; <label id="nama_barang-error" for="nama_barang" class="error"></td>
									</table>
								</td>
							</tr>
							<tr><td>&nbsp;</td></tr>
							<tr>
								<td width="10%"><font style="font-size:12px;font-weight:bold;">Rasa</font></td>
								<td width="1%">:</td>
								<td>
									<table>
										<td> 
											<select id="kode_rasa" name="kode_rasa" class="form-control select_group product" width="15%">
												<option value="0">--Pilih Rasa--</option>
												<?php  
													$kode_rasa_data =  $this->data[0]['kode_rasa'];
													$selected3 = 'selected';
													for($x=0; $x<count($this->rasa); $x++){ 
												?>
												<option value="<?php echo $this->rasa[$x]['kode_rasa'];?>" <?php if($kode_rasa_data == $this->rasa[$x]['kode_rasa']){echo $selected3;}?>><?php echo $this->rasa[$x]['rasa'];?></option>
												<?php } ?>
											</select>
										</td>
										<td> &nbsp; <label id="kode_rasa-error" for="kode_rasa" class="error"></td>
									</table>
								</td>
							</tr>
							<tr><td>&nbsp;</td></tr>
							<tr>
								<td width="10%"><font style="font-size:12px;font-weight:bold;">Nicotin</font></td>
								<td width="1%">:</td>
								<td>
									<table>
										<td> <input name="nic" id="nic" type="text" maxlength="10" size="5" class="form-control input-sm" value="<?php echo $this->data[0]['nic']?>"> </td>
										<td> &nbsp; Miligram (Mgr)</td>
										<td> &nbsp; <label id="nic-error" for="nic" class="error"></td>
									</table>
								</td>
							</tr>
							<tr><td>&nbsp;</td></tr>
							<tr>
								<td width="10%"><font style="font-size:12px;font-weight:bold;">Berat</font></td>
								<td width="1%">:</td>
								<td>
									<table>
										<td> <input name="berat" id="berat" type="text" maxlength="10" size="5" class="form-control input-sm" value="<?php echo $this->data[0]['berat']?>"> </td>
										<td> &nbsp; Gram (Gr)</td>
										<td> &nbsp; <label id="berat-error" for="berat" class="error"></td>
									</table>
								</td>
							</tr>
							<tr><td>&nbsp;</td></tr>
							<tr>
								<td width="10%"><font style="font-size:12px;font-weight:bold;">Stok Gudang Pusat</font></td>
								<td width="1%">:</td>
								<td>
									<table>
										<td> <input name="stok_pusat" id="stok_pusat" type="text" maxlength="50" size="15" class="form-control input-sm" value="<?php echo $this->data[0]['stok_pusat']?>" onkeypress="javascript:return isNumber(event)"> </td>
										<td> &nbsp; pcs.</td>
										<td> &nbsp; <label id="stok_pusat-error" for="stok_pusat" class="error"></td>
									</table>
								</td>
							</tr>
							<tr><td>&nbsp;</td></tr>
							<tr>
								<td width="10%"><font style="font-size:12px;font-weight:bold;">Stok Gudang Retail</font></td>
								<td width="1%">:</td>
								<td>
									<table>
										<td> <input name="stok_retail" id="stok_retail" type="text" maxlength="50" size="15" class="form-control input-sm" value="<?php echo $this->data[0]['stok_retail']?>" onkeypress="javascript:return isNumber(event)"> </td>
										<td> &nbsp; pcs.</td>
										<td> &nbsp; <label id="stok_retail-error" for="stok_retail" class="error"></td>
									</table>
								</td>
							</tr>
							<tr><td>&nbsp;</td></tr>
							<tr>
								<td width="10%"><font style="font-size:12px;font-weight:bold;">Stok Gudang Studio</font></td>
								<td width="1%">:</td>
								<td>
									<table>
										<td> <input name="stok_studio" id="stok_studio" type="text" maxlength="50" size="15" class="form-control input-sm" value="<?php echo $this->data[0]['stok_studio']?>" onkeypress="javascript:return isNumber(event)"> </td>
										<td> &nbsp; pcs.</td>
										<td> &nbsp; <label id="stok_studio-error" for="stok_studio" class="error"></td>
									</table>
								</td>
							</tr>
							<tr><td>&nbsp;</td></tr>
							<tr>
								<td width="10%"><font style="font-size:12px;font-weight:bold;">Bad Stock (BS)</font></td>
								<td width="1%">:</td>
								<td>
									<table>
										<td> <input name="bad_stock" id="bad_stock" type="text" maxlength="50" size="15" class="form-control input-sm" value="<?php echo $this->data[0]['bad_stock']?>" onkeypress="javascript:return isNumber(event)"> </td>
										<td> &nbsp; pcs.</td>
										<td> &nbsp; <label id="bad_stock-error" for="bad_stock" class="error"></td>
									</table>
								</td>
							</tr>
							<tr><td>&nbsp;</td></tr>
							<tr>
								<td width="10%"><font style="font-size:12px;font-weight:bold;">Harga Beli Rp.</font></td>
								<td width="1%">:</td>
								<td>
									<table>
										<td> <input name="harga_beli" id="harga_beli" type="text" maxlength="50" size="20" class="form-control input-sm" value="<?php echo number_format($this->data[0]['harga_beli'],0,",",".")?>" onkeypress="javascript:return isNumber(event)" onkeyup="currency()"> </td>
										<td> &nbsp; <label id="harga_beli-error" for="harga_beli" class="error"></td>
									</table>
								</td>
							</tr>
							<tr><td>&nbsp;</td></tr>
							<tr>
								<td width="10%"><font style="font-size:12px;font-weight:bold;">Harga Jual Agn Rp.</font></td>
								<td width="1%">:</td>
								<td>
									<table>
										<td> <input name="hj_agen" id="hj_agen" type="text" maxlength="50" size="20" class="form-control input-sm" value="<?php echo number_format($this->data[0]['hj_agen'],0,",",".")?>" onkeypress="javascript:return isNumber(event)" onkeyup="currency()"> </td>
										<td> &nbsp; <label id="hj_agen-error" for="hj_agen" class="error"></td>
									</table>
								</td>
							</tr>
							<tr><td>&nbsp;</td></tr>
							<tr>
								<td width="10%"><font style="font-size:12px;font-weight:bold;">Harga Jual Ret Rp.</font></td>
								<td width="1%">:</td>
								<td>
									<table>
										<td> <input name="hj_retail" id="hj_retail" type="text" maxlength="50" size="20" class="form-control input-sm" value="<?php echo number_format($this->data[0]['hj_retail'],0,",",".")?>" onkeypress="javascript:return isNumber(event)" onkeyup="currency()"> </td>
										<td> &nbsp; <label id="hj_retail-error" for="hj_retail" class="error"></td>
									</table>
								</td>
							</tr>
							<tr><td>&nbsp;</td></tr>
							<tr>
								<td width="10%"><font style="font-size:12px;font-weight:bold;">Harga Jual WS Rp.</font></td>
								<td width="1%">:</td>
								<td>
									<table>
										<td> <input name="hj_whs" id="hj_whs" type="text" maxlength="50" size="20" class="form-control input-sm" value="<?php echo number_format($this->data[0]['hj_whs'],0,",",".")?>" onkeypress="javascript:return isNumber(event)" onkeyup="currency()"> </td>
										<td> &nbsp; <label id="hj_whs-error" for="hj_whs" class="error"></td>
									</table>
								</td>
							</tr>
							<tr><td>&nbsp;</td></tr>
							<tr>
								<td width="10%"><font style="font-size:12px;font-weight:bold;">Status</font></td>
								<td width="1%">:</td>
								<td>
									<table>
										<td> 
										<?php 
											$status = $this->data[0]['status'];
											$selected = 'selected';
										?>
											<select id="status" name="status" class="form-control select_group product" width="15%">
												<option value="">--Pilih Status--</option>
												<option value="1" <?php if($status == '1'){ echo $selected; } ?>>Active</option>
												<option value="0" <?php if($status == '0'){ echo $selected; } ?>>Inactive</option>
											</select>
										</td>
										<td> &nbsp; <label id="status-error" for="status" class="error"></td>
									</table>
								</td>
							</tr>
							<tr><td>&nbsp;</td></tr>
						</table>
					</div>				
			</fieldset>
		</div>
		
	</div>
</div>
<div class="col-lg-12">
<div class="form-group form-group-bottom" align="right">
						<input type="hidden" id="proses" name="proses" value="<?php echo $this->proses?>">	
						<br><br>
							
							<a href="liquid">
							<button type="button" class="btn btn-theme02">
								<span class="fa fa-backward"></span> &nbsp;Kembali
							</button></a>
							<button type="button" class="btn btn-theme03" onCLick="PostData()">
								<span class="fa fa-save"></span> &nbsp;Simpan
							</button>
							
			</div>
</div>
</form>
  <script src="<?php echo $this->baseUrl();?>/lib/jquery.form.js"></script>
  <link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl();?>/css/sweetalert.css">
  <script src="<?php echo $this->baseUrl();?>/lib/sweetalert.min.js"></script>   
  <script src="<?php echo $this->baseUrl();?>/lib/jquery.scrollTo.min.js"></script>
  <script src="<?php echo $this->baseUrl();?>/lib/jquery.nicescroll.js" type="text/javascript"></script>
<script>
	function getSelectValue(){
		var selectedValue = document.getElementById("kode_supplier").value;
		var res = selectedValue.split(",");
		var kode_supplier = res[0];
		var alamat = res[1];
		var tipe = res[2];
		var res2 = tipe.substring(0,1);
		var volume = document.getElementById("volume").value;
		var seq = document.getElementById("seq").value;
		
		var kode = res2+'-L'+volume+'-'+seq;
		document.getElementById("kode_barang").value = kode;
		//document.getElementById("test").innerHTML = kode;
		
		document.getElementById("kode_supplier2").value = kode_supplier;
		document.getElementById("alamat_supplier").value = alamat;
		document.getElementById("tipe").value = tipe;
	}
	
	function getKode(){
		var tipe = document.getElementById("tipe").value;
		var res = tipe.substring(0,1);
		var volume = document.getElementById("volume").value;
		var seq = document.getElementById("seq").value;
		
		var kode = res+'-L'+volume+'-'+seq;
		document.getElementById("kode_barang").value = kode;
		//document.getElementById("test").innerHTML = kode;
	}
                                                                                                                                     
	
	function PostData(){
		//alert('Testing2');
        $("#frm_postdata").ajaxSubmit(post_data);
    }
	
	var post_data = {
		target:'',
		beforeSubmit: function() {	
			/* var kode_supplier2 	  = document.getElementById("kode_supplier2").value;
			var volume		      = document.getElementById('volume').value;
			var kode_barang 	  = document.getElementById('kode_barang').value; */
			var merk_barang 	  = document.getElementById('merk_barang').value;
			var nama_barang 	  = document.getElementById('nama_barang').value;
			var kode_rasa	 	  = document.getElementById('kode_rasa').value;
			var nic			 	  = document.getElementById('nic').value;
			var berat 	  		  = document.getElementById('berat').value;
			var stok_pusat 	  	  = document.getElementById('stok_pusat').value;
			var stok_retail 	  = document.getElementById('stok_retail').value;
			var stok_studio 	  = document.getElementById('stok_studio').value;
			var bad_stock    	  = document.getElementById('bad_stock').value;
			var harga_beli 	  	  = document.getElementById('harga_beli').value;
			var hj_agen 	  	  = document.getElementById('hj_agen').value;
			var hj_retail 	  	  = document.getElementById('hj_retail').value;
			var hj_whs 	  		  = document.getElementById('hj_whs').value;
			var status 			  = document.getElementById('status').value;
			
				/* if (!kode_supplier2) {
					document.getElementById('kode_supplier-error').innerHTML ="<span style='color: red;'>Supplier Harus Dipilih.</span>";
					document.getElementById('kode_supplier').focus();
					exit;
				}else document.getElementById('kode_supplier-error').innerHTML ='';
				
				if (volume=='0') {
					document.getElementById('volume-error').innerHTML ="<span style='color: red;'>Volume Harus Dipilih.</span>";
					document.getElementById('volume').focus();
					exit;
				}else document.getElementById('volume-error').innerHTML =''; */
				
				if (!merk_barang) {
					document.getElementById('merk_barang-error').innerHTML ="<span style='color: red;'>Merk Liquid Harus Diisi.</span>";
					document.getElementById('merk_barang').focus();
					exit;
				}else document.getElementById('merk_barang-error').innerHTML ='';
				
				if (!nama_barang) {
					document.getElementById('nama_barang-error').innerHTML ="<span style='color: red;'>Nama Liquid Harus Diisi.</span>";
					document.getElementById('nama_barang').focus();
					exit;
				}else document.getElementById('nama_barang-error').innerHTML ='';
				
				if (kode_rasa=='0') {
					document.getElementById('kode_rasa-error').innerHTML ="<span style='color: red;'>Rasa Harus Dipilih.</span>";
					document.getElementById('kode_rasa').focus();
					exit;
				}else document.getElementById('kode_rasa-error').innerHTML ='';
				
				if (!nic) {
					document.getElementById('nic-error').innerHTML ="<span style='color: red;'>Nicotin Harus Diisi.</span>";
					document.getElementById('nic').focus();
					exit;
				}else document.getElementById('nic-error').innerHTML ='';
				
				if (!berat) {
					document.getElementById('berat-error').innerHTML ="<span style='color: red;'>Berat Harus Diisi.</span>";
					document.getElementById('berat').focus();
					exit;
				}else document.getElementById('berat-error').innerHTML ='';
				
				if (!stok_pusat) {
					document.getElementById('stok_pusat-error').innerHTML ="<span style='color: red;'>Stok Gudang Pusat Harus Diisi.</span>";
					document.getElementById('stok_pusat').focus();
					exit;
				}else document.getElementById('stok_pusat-error').innerHTML ='';
				
				if (!stok_retail) {
					document.getElementById('stok_retail-error').innerHTML ="<span style='color: red;'>Stok Gudang Retail Harus Diisi.</span>";
					document.getElementById('stok_retail').focus();
					exit;
				}else document.getElementById('stok_retail-error').innerHTML ='';
				
				if (!stok_studio) {
					document.getElementById('stok_studio-error').innerHTML ="<span style='color: red;'>Stok Gudang Studio Harus Diisi.</span>";
					document.getElementById('stok_studio').focus();
					exit;
				}else document.getElementById('stok_studio-error').innerHTML ='';
				
				if (!bad_stock) {
					document.getElementById('bad_stock-error').innerHTML ="<span style='color: red;'>Bad Stock Harus Diisi.</span>";
					document.getElementById('bad_stock').focus();
					exit;
				}else document.getElementById('bad_stock-error').innerHTML ='';
				
				if (!harga_beli) {
					document.getElementById('harga_beli-error').innerHTML ="<span style='color: red;'>Harga Beli Harus Diisi.</span>";
					document.getElementById('harga_beli').focus();
					exit;
				}else document.getElementById('harga_beli-error').innerHTML ='';
				
				if (!hj_agen) {
					document.getElementById('hj_agen-error').innerHTML ="<span style='color: red;'>Harga Jual Agn Harus Diisi.</span>";
					document.getElementById('hj_agen').focus();
					exit;
				}else document.getElementById('hj_agen-error').innerHTML ='';
				
				if (!hj_retail) {
					document.getElementById('hj_retail-error').innerHTML ="<span style='color: red;'>Harga Jual Ret Harus Diisi.</span>";
					document.getElementById('hj_retail').focus();
					exit;
				}else document.getElementById('hj_retail-error').innerHTML ='';
				
				if (!hj_whs) {
					document.getElementById('hj_whs-error').innerHTML ="<span style='color: red;'>Harga Jual WS Harus Diisi.</span>";
					document.getElementById('hj_whs').focus();
					exit;
				}else document.getElementById('hj_whs-error').innerHTML ='';
				
				if (status=='') {
					document.getElementById('status-error').innerHTML ="<span style='color: red;'>Status Harus Dipilih.</span>";
					document.getElementById('status').focus();
					exit;
				}else document.getElementById('status-error').innerHTML ='';
			}, 
		success:function(){	
			swal({
				    title: 'Tambah Liquid Berhasil !',
				    text: 'Auto Close...',
				    icon: 'success',
				    timer: 4000,
				    showConfirmButton: false,
				})
			location.href="#";		
			location.reload(true)
		},
		url: '<?php echo $this->baseUrl();?>/liquid/kirimdataedit',
		type: 'post',
		resetForm: false
	};
	
	function isNumber(evt) {
        var iKeyCode = (evt.which) ? evt.which : evt.keyCode
        if (iKeyCode != 46 && iKeyCode > 31 && (iKeyCode < 48 || iKeyCode > 57))
            return false;

        return true;
    } 
	
	function currency(){
		var harga_beli = document.getElementById("harga_beli").value;
		var harga_beli2 = harga_beli.replaceAll(".", "");
		var harga_beli3 = harga_beli2.toString().replaceAll(/(\d)(?=(\d\d\d)+(?!\d))/g, "$1.");
		document.getElementById("harga_beli").value=harga_beli3;
		
		var hj_agen = document.getElementById("hj_agen").value;
		var hj_agen2 = hj_agen.replaceAll(".", "");
		var hj_agen3 = hj_agen2.toString().replaceAll(/(\d)(?=(\d\d\d)+(?!\d))/g, "$1.");
		document.getElementById("hj_agen").value=hj_agen3;
		
		var hj_retail = document.getElementById("hj_retail").value;
		var hj_retail2 = hj_retail.replaceAll(".", "");
		var hj_retail3 = hj_retail2.toString().replaceAll(/(\d)(?=(\d\d\d)+(?!\d))/g, "$1.");
		document.getElementById("hj_retail").value=hj_retail3;
		
		var hj_whs = document.getElementById("hj_whs").value;
		var hj_whs2 = hj_whs.replaceAll(".", "");
		var hj_whs3 = hj_whs2.toString().replaceAll(/(\d)(?=(\d\d\d)+(?!\d))/g, "$1.");
		document.getElementById("hj_whs").value=hj_whs3;
	}
</script>
  <script>
   $(".product").select2();
  </script>