<head>
  <link href="<?php echo $this->baseUrl();?>/css/select2.min.css" rel="stylesheet">
  <link href="<?php echo $this->baseUrl();?>/css/fileinput/fileinput.min.css" rel="stylesheet">
  <script src="<?php echo $this->baseUrl();?>/lib/select2.full.min.js"></script>
  <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
  <script src="<?php echo $this->baseUrl();?>/lib/jquery-ui-1.9.2.custom.min.js"></script>
</head>
<form id="frm_postdata" name="frm_postdata" enctype="multipart/form-data" method="POST" autocomplete="off">
	<input type="hidden" name="currentPage" id="currentPage" size="6" maxlength="6" value="<?php echo $this->numPage;?>" class="inputbox2 narrowkey1"></input>
		<?php 
			$seq = substr($this->seq,9,5);
			//var_dump($seq);
			$seq += 1;
			$seq=str_pad($seq, 5, '0', STR_PAD_LEFT);
		?>
		<input type="hidden" id='seq' value ='<?php echo $seq;?>'>
		<div class="panel">
            <fieldset class="panel-dt">							
				<h4><i class="fa fa-angle-right"></i> Tambah Data Atomizer</h4>
						<br>
					<div class="col-sm-12">
						<table width="100%">
							<tr>
								<td width="10%"><font style="font-size:12px;font-weight:bold;">Nama Supplier</font></td>
								<td width="1%">:</td>
								<td>
									<table>
										<td>
											<select id="kode_supplier" name="kode_supplier" class="form-control select_group product" width="15%" onchange="getSelectValue();">
												<option value="0">--Pilih Supplier--</option>
												<?php  
													for($x=0; $x<count($this->supplier); $x++){ 
													$kode_supplier = $this->supplier[$x]['kode_supplier'];
													$nama_supplier = $this->supplier[$x]['nama_supplier'];
													$alamat_supplier = $this->supplier[$x]['alamat_supplier'];
													$tipe = $this->supplier[$x]['tipe'];
												?>
												<option value="<?php echo $kode_supplier;?>,<?php echo $alamat_supplier;?>,<?php echo $tipe;?>"><?php echo $nama_supplier;?></option>
												<?php } ?>
											</select>
										</td>
										<td> &nbsp; <label id="kode_supplier-error" for="kode_supplier" class="error"></td>
										<td> <input type='hidden' id='kode_supplier2' name='kode_supplier2' value=''></td>
									</table>
								</td>
							</tr>
							<tr><td>&nbsp;</td></tr>
							<tr>
								<td width="10%"><font style="font-size:12px;font-weight:bold;">Alamat Supplier</font></td>
								<td width="1%">:</td>
								<td>
									<table>
										<td> <input name="alamat_supplier" id="alamat_supplier" type="text" maxlength="100" size="100" class="form-control input-sm" value="" readonly> </td>
										<td> </td>
									</table>
								</td>
							</tr> 
							<tr><td>&nbsp;</td></tr>
							<tr>
								<td width="10%"><font style="font-size:12px;font-weight:bold;">Status Supplier</font></td>
								<td width="1%">:</td>
								<td>
									<table>
										<td> <input name="tipe" id="tipe" type="text" maxlength="10" size="10" class="form-control input-sm" value="" readonly> </td>
										<td> </td>
									</table>
								</td>
							</tr> 
							<tr><td>&nbsp;</td></tr>
							<tr>
								<td width="10%"><font style="font-size:12px;font-weight:bold;">Jenis Atomizer</font></td>
								<td width="1%">:</td>
								<td>
									<table>
										<td> 
											<select id="jenis_atomizer" name="jenis_atomizer" class="form-control select_group product" width="15%" onchange="getKode();">
												<option value="0">--Pilih Jenis Atomizer--</option>
												<?php  
													for($x=0; $x<count($this->jenis); $x++){ 
													$kode_ket = $this->jenis[$x]['kode_ket'];
													$keterangan = $this->jenis[$x]['keterangan'];
												?>
												<option value="<?php echo $kode_ket;?>"><?php echo $keterangan;?></option>
												<?php } ?>
											</select>
										</td>
										<td> &nbsp; <label id="jenis_atomizer-error" for="jenis_atomizer" class="error"></td>
									</table>
								</td>
							</tr> 
							<tr><td>&nbsp;</td></tr>
							<tr>
								<td width="10%"><font style="font-size:12px;font-weight:bold;">Kode Atomizer</font></td>
								<td width="1%">:</td>
								<td>
									<table>
										<td> 
											<input name="kode_atomizer" id="kode_atomizer" type="text" maxlength="50" size="20" class="form-control input-sm" value="" readonly> 
											<input type="hidden" name="id_kode_barang" id="id_kode_barang" value="">
											<input type="hidden" name="seq_kode_barang" id="seq_kode_barang" value="">
										</td>
										<td> &nbsp; <label id="kode_atomizer-error" for="kode_atomizer" class="error"></td>
									</table>
								</td>
							</tr> 
							<tr><td>&nbsp;</td></tr>
							<tr>
								<td width="10%"><font style="font-size:12px;font-weight:bold;">Merk Atomizer</font></td>
								<td width="1%">:</td>
								<td>
									<table>
										<td> <input name="merk_atomizer" id="merk_atomizer" type="text" maxlength="50" size="20" class="form-control input-sm" value=""> </td>
										<td> &nbsp; <label id="merk_atomizer-error" for="merk_atomizer" class="error"></td>
									</table>
								</td>
							</tr>
							<tr><td>&nbsp;</td></tr>
							<tr>
								<td width="10%"><font style="font-size:12px;font-weight:bold;">Nama Atomizer</font></td>
								<td width="1%">:</td>
								<td>
									<table>
										<td> <input name="nama_atomizer" id="nama_atomizer" type="text" maxlength="50" size="50" class="form-control input-sm" value=""> </td>
										<td> &nbsp; <label id="nama_atomizer-error" for="nama_atomizer" class="error"></td>
									</table>
								</td>
							</tr>
							<tr><td>&nbsp;</td></tr>
							<tr>
								<td width="10%"><font style="font-size:12px;font-weight:bold;">Warna</font></td>
								<td width="1%">:</td>
								<td>
									<table>
										<td> 
											<select id="kode_warna" name="kode_warna" class="form-control select_group product" width="15%">
												<option value="0">--Pilih Warna--</option>
												<?php  
													for($x=0; $x<count($this->warna); $x++){ 
												?>
												<option value="<?php echo $this->warna[$x]['kode_warna'];?>"><?php echo $this->warna[$x]['nama_warna'];?></option>
												<?php } ?>
											</select>
										</td>
										<td> &nbsp; <label id="kode_warna-error" for="kode_warna" class="error"></td>
									</table>
								</td>
							</tr>
							<tr><td>&nbsp;</td></tr>
							<tr>
								<td width="10%"><font style="font-size:12px;font-weight:bold;">Berat</font></td>
								<td width="1%">:</td>
								<td>
									<table>
										<td> <input name="berat" id="berat" type="text" maxlength="10" size="5" class="form-control input-sm" value=""> </td>
										<td> &nbsp; Gram (Gr)</td>
										<td> &nbsp; <label id="berat-error" for="berat" class="error"></td>
									</table>
								</td>
							</tr>
							<tr><td>&nbsp;</td></tr>
							<tr>
								<td width="10%"><font style="font-size:12px;font-weight:bold;">Stok Gudang Pusat</font></td>
								<td width="1%">:</td>
								<td>
									<table>
										<td> <input name="stok_pusat" id="stok_pusat" type="text" maxlength="50" size="15" class="form-control input-sm" value="" onkeypress="javascript:return isNumber(event)"> </td>
										<td> &nbsp; pcs.</td>
										<td> &nbsp; <label id="stok_pusat-error" for="stok_pusat" class="error"></td>
									</table>
								</td>
							</tr>
							<tr><td>&nbsp;</td></tr>
							<tr>
								<td width="10%"><font style="font-size:12px;font-weight:bold;">Stok Gudang Retail</font></td>
								<td width="1%">:</td>
								<td>
									<table>
										<td> <input name="stok_retail" id="stok_retail" type="text" maxlength="50" size="15" class="form-control input-sm" value="" onkeypress="javascript:return isNumber(event)"> </td>
										<td> &nbsp; pcs.</td>
										<td> &nbsp; <label id="stok_retail-error" for="stok_retail" class="error"></td>
									</table>
								</td>
							</tr>
							<tr><td>&nbsp;</td></tr>
							<tr>
								<td width="10%"><font style="font-size:12px;font-weight:bold;">Stok Gudang Studio</font></td>
								<td width="1%">:</td>
								<td>
									<table>
										<td> <input name="stok_studio" id="stok_studio" type="text" maxlength="50" size="15" class="form-control input-sm" value="" onkeypress="javascript:return isNumber(event)"> </td>
										<td> &nbsp; pcs.</td>
										<td> &nbsp; <label id="stok_studio-error" for="stok_studio" class="error"></td>
									</table>
								</td>
							</tr>
							<tr><td>&nbsp;</td></tr>
							<tr>
								<td width="10%"><font style="font-size:12px;font-weight:bold;">Bad Stock (BS)</font></td>
								<td width="1%">:</td>
								<td>
									<table>
										<td> <input name="bad_stock" id="bad_stock" type="text" maxlength="50" size="15" class="form-control input-sm" value="" onkeypress="javascript:return isNumber(event)"> </td>
										<td> &nbsp; pcs.</td>
										<td> &nbsp; <label id="bad_stock-error" for="bad_stock" class="error"></td>
									</table>
								</td>
							</tr>
							<tr><td>&nbsp;</td></tr>
							<tr>
								<td width="10%"><font style="font-size:12px;font-weight:bold;">Harga Beli Rp.</font></td>
								<td width="1%">:</td>
								<td>
									<table>
										<td> <input name="harga_beli" id="harga_beli" type="text" maxlength="50" size="20" class="form-control input-sm" value="" onkeypress="javascript:return isNumber(event)" onkeyup="currency()"> </td>
										<td> &nbsp; <label id="harga_beli-error" for="harga_beli" class="error"></td>
									</table>
								</td>
							</tr>
							<tr><td>&nbsp;</td></tr>
							<tr>
								<td width="10%"><font style="font-size:12px;font-weight:bold;">Harga Jual Agn Rp.</font></td>
								<td width="1%">:</td>
								<td>
									<table>
										<td> <input name="hj_agen" id="hj_agen" type="text" maxlength="50" size="20" class="form-control input-sm" value="" onkeypress="javascript:return isNumber(event)" onkeyup="currency()"> </td>
										<td> &nbsp; <label id="hj_agen-error" for="hj_agen" class="error"></td>
									</table>
								</td>
							</tr>
							<tr><td>&nbsp;</td></tr>
							<tr>
								<td width="10%"><font style="font-size:12px;font-weight:bold;">Harga Jual WS Rp.</font></td>
								<td width="1%">:</td>
								<td>
									<table>
										<td> <input name="hj_whs" id="hj_whs" type="text" maxlength="50" size="20" class="form-control input-sm" value="" onkeypress="javascript:return isNumber(event)" onkeyup="currency()"> </td>
										<td> &nbsp; <label id="hj_whs-error" for="hj_whs" class="error"></td>
									</table>
								</td>
							</tr>
							<tr><td>&nbsp;</td></tr>
							<tr>
								<td width="10%"><font style="font-size:12px;font-weight:bold;">Harga Jual Ret Rp.</font></td>
								<td width="1%">:</td>
								<td>
									<table>
										<td> <input name="hj_retail" id="hj_retail" type="text" maxlength="50" size="20" class="form-control input-sm" value="" onkeypress="javascript:return isNumber(event)" onkeyup="currency()"> </td>
										<td> &nbsp; <label id="hj_retail-error" for="hj_retail" class="error"></td>
									</table>
								</td>
							</tr>
							<tr><td>&nbsp;</td></tr>
							
							<tr>
								<td width="10%"><font style="font-size:12px;font-weight:bold;">Status</font></td>
								<td width="1%">:</td>
								<td>
									<table>
										<td> 
											<select id="status" name="status" class="form-control select_group product" width="15%">
												<option value="">--Pilih Status--</option>
												<option value="1" selected>Active</option>
												<option value="0">Inactive</option>
											</select>
										</td>
										<td> &nbsp; <label id="status-error" for="status" class="error"></td>
									</table>
								</td>
							</tr>
							<tr><td>&nbsp;</td></tr>
							<tr>
								<td width="10%"><font style="font-size:12px;font-weight:bold;">Izinkan Perubahan Harga</font></td>
								<td width="1%">:</td>
								<td>
									<table>
										<td> 
											<select id="otorisasi_harga" name="otorisasi_harga" class="form-control select_group product" width="15%">
												<option value="1">Tidak</option>
												<option value="0">Ya</option>
											</select>
											
										</td>
									
										<td> &nbsp; <label id="status-error" for="status" class="error"></td>
										
									</table>
									
								</td>
							</tr>
							<tr class="ket_otorisasi_harga">
								<td width="10%"></td>
								<td width="1%"></td>
								<td>
								<small>*Pengguna harus melakukan otorisasi (username, password) ketika melakukan<br>perubahan harga ke lebih rendah untuk item ini</small>
								</td>
							</tr>
							<tr><td>&nbsp;</td></tr>
						</table>
					</div>				
			</fieldset>
		</div>
		
	</div>
</div>
<div class="col-lg-12">
<div class="form-group form-group-bottom" align="right">
						<input type="hidden" id="proses" name="proses" value="<?php echo $this->proses?>">	
						<br><br>
							
							<a href="atomizer">
							<button type="button" class="btn btn-theme02">
								<span class="fa fa-backward"></span> &nbsp;Kembali
							</button></a>
							<button type="button" class="btn btn-theme03" onCLick="PostData()">
								<span class="fa fa-save"></span> &nbsp;Simpan
							</button>
							
			</div>
</div>
</form>
  <script src="<?php echo $this->baseUrl();?>/lib/jquery.form.js"></script>
  <link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl();?>/css/sweetalert.css">
  <script src="<?php echo $this->baseUrl();?>/lib/sweetalert.min.js"></script>   
  <script src="<?php echo $this->baseUrl();?>/lib/jquery.scrollTo.min.js"></script>
  <script src="<?php echo $this->baseUrl();?>/lib/jquery.nicescroll.js" type="text/javascript"></script>
<script>

$('#otorisasi_harga').on('change', function() {
		let otorisasi_harga = $(this).val();
		if(otorisasi_harga == '1') {
			$('.ket_otorisasi_harga').show();
		} else {
			$('.ket_otorisasi_harga').hide();
		}
	})
	function getSelectValue(){
		var selectedValue = document.getElementById("kode_supplier").value;
		var res = selectedValue.split(",");
		var kode_supplier = res[0];
		var alamat = res[1];
		var tipe = res[2];
		var res2 = tipe.substring(0,1);
		var jenis_atomizer = document.getElementById("jenis_atomizer").value;
		var seq = document.getElementById("seq").value;
		
		//var kode = res2+'-AT/'+jenis_atomizer+'-'+seq;
		//document.getElementById("kode_atomizer").value = kode;
		//document.getElementById("test").innerHTML = kode;
		
		var id_kode_barang = res2+'-AT/'+jenis_atomizer;
		var url = "<?php echo $this->baseUrl; ?>/atomizer/cekseq";
			var opt = {id_kode_barang:id_kode_barang};
		
			jQuery.get(url,opt, function(data) {	
			//alert(data);
				if(data == ''){
					data2='0';
				} else {
					data2=data;
				}
				var hasilseq = parseInt(data2) + parseInt(1);
				var str = "" + hasilseq
				var pad = "00000"
				var ans = pad.substring(0, pad.length - str.length) + str
				
				var kode = id_kode_barang+'-'+ans;
				document.getElementById("kode_atomizer").value = kode;
				
				document.getElementById("id_kode_barang").value = id_kode_barang;
				document.getElementById("seq_kode_barang").value = hasilseq;
			});
		
		document.getElementById("kode_supplier2").value = kode_supplier;
		document.getElementById("alamat_supplier").value = alamat;
		document.getElementById("tipe").value = tipe;
	}
	
	function getKode(){
		var tipe = document.getElementById("tipe").value;
		var res = tipe.substring(0,1);
		var jenis_atomizer = document.getElementById("jenis_atomizer").value;
		var seq = document.getElementById("seq").value;
		
		//var kode = res+'-AT/'+jenis_atomizer+'-'+seq;
		//document.getElementById("kode_atomizer").value = kode;
		//document.getElementById("test").innerHTML = kode;
		
		var id_kode_barang = res+'-AT/'+jenis_atomizer;
		var url = "<?php echo $this->baseUrl; ?>/atomizer/cekseq";
			var opt = {id_kode_barang:id_kode_barang};
		
			jQuery.get(url,opt, function(data) {	
			//alert(data);
				if(data == ''){
					data2='0';
				} else {
					data2=data;
				}
				var hasilseq = parseInt(data2) + parseInt(1);
				var str = "" + hasilseq
				var pad = "00000"
				var ans = pad.substring(0, pad.length - str.length) + str
				
				var kode = id_kode_barang+'-'+ans;
				document.getElementById("kode_atomizer").value = kode;
				
				document.getElementById("id_kode_barang").value = id_kode_barang;
				document.getElementById("seq_kode_barang").value = hasilseq;
			});
	}
                                                                                                                                     
	
	function PostData(){
		//alert('Testing2');
        $("#frm_postdata").ajaxSubmit(post_data);
    }
	
	var post_data = {
		target:'',
		beforeSubmit: function() {	
			var kode_supplier2 	  = document.getElementById("kode_supplier2").value;
			var kode_atomizer 	  = document.getElementById('kode_atomizer').value;
			var merk_atomizer 	  = document.getElementById('merk_atomizer').value;
			var nama_atomizer 	  = document.getElementById('nama_atomizer').value;
			var jenis_atomizer	  = document.getElementById('jenis_atomizer').value;
			var kode_warna	 	  = document.getElementById('kode_warna').value;
			var berat 	  		  = document.getElementById('berat').value;
			var stok_pusat 	  	  = document.getElementById('stok_pusat').value;
			var stok_retail 	  = document.getElementById('stok_retail').value;
			var stok_studio 	  = document.getElementById('stok_studio').value;
			var bad_stock    	  = document.getElementById('bad_stock').value;
			var harga_beli 	  	  = document.getElementById('harga_beli').value;
			var hj_agen 	  	  = document.getElementById('hj_agen').value;
			var hj_retail 	  	  = document.getElementById('hj_retail').value;
			var hj_whs 	  		  = document.getElementById('hj_whs').value;
			var status 			  = document.getElementById('status').value;
			
				if (!kode_supplier2) {
					document.getElementById('kode_supplier-error').innerHTML ="<span style='color: red;'>Supplier Harus Dipilih.</span>";
					document.getElementById('kode_supplier').focus();
					exit;
				}else document.getElementById('kode_supplier-error').innerHTML ='';
				
				if (jenis_atomizer=='0') {
					document.getElementById('jenis_atomizer-error').innerHTML ="<span style='color: red;'>Jenis Atomizer Harus Dipilih.</span>";
					document.getElementById('jenis_atomizer').focus();
					exit;
				}else document.getElementById('jenis_atomizer-error').innerHTML ='';
				
				if (!merk_atomizer) {
					document.getElementById('merk_atomizer-error').innerHTML ="<span style='color: red;'>Merk Atomizer Harus Diisi.</span>";
					document.getElementById('merk_atomizer').focus();
					exit;
				}else document.getElementById('merk_atomizer-error').innerHTML ='';
				
				if (!nama_atomizer) {
					document.getElementById('nama_atomizer-error').innerHTML ="<span style='color: red;'>Nama Atomizer Harus Diisi.</span>";
					document.getElementById('nama_atomizer').focus();
					exit;
				}else document.getElementById('nama_atomizer-error').innerHTML ='';
				
				if (kode_warna=='0') {
					document.getElementById('kode_warna-error').innerHTML ="<span style='color: red;'>Warna Harus Dipilih.</span>";
					document.getElementById('kode_warna').focus();
					exit;
				}else document.getElementById('kode_warna-error').innerHTML ='';
				
				if (!berat) {
					document.getElementById('berat-error').innerHTML ="<span style='color: red;'>Berat Harus Diisi.</span>";
					document.getElementById('berat').focus();
					exit;
				}else document.getElementById('berat-error').innerHTML ='';
				
				if (!stok_pusat) {
					document.getElementById('stok_pusat-error').innerHTML ="<span style='color: red;'>Stok Gudang Pusat Harus Diisi.</span>";
					document.getElementById('stok_pusat').focus();
					exit;
				}else document.getElementById('stok_pusat-error').innerHTML ='';
				
				if (!stok_retail) {
					document.getElementById('stok_retail-error').innerHTML ="<span style='color: red;'>Stok Gudang Retail Harus Diisi.</span>";
					document.getElementById('stok_retail').focus();
					exit;
				}else document.getElementById('stok_retail-error').innerHTML ='';
				
				if (!stok_studio) {
					document.getElementById('stok_studio-error').innerHTML ="<span style='color: red;'>Stok Gudang Studio Harus Diisi.</span>";
					document.getElementById('stok_studio').focus();
					exit;
				}else document.getElementById('stok_studio-error').innerHTML ='';
				
				if (!bad_stock) {
					document.getElementById('bad_stock-error').innerHTML ="<span style='color: red;'>Bad Stock Harus Diisi.</span>";
					document.getElementById('bad_stock').focus();
					exit;
				}else document.getElementById('bad_stock-error').innerHTML ='';
				
				if (!harga_beli) {
					document.getElementById('harga_beli-error').innerHTML ="<span style='color: red;'>Harga Beli Harus Diisi.</span>";
					document.getElementById('harga_beli').focus();
					exit;
				}else document.getElementById('harga_beli-error').innerHTML ='';
				
				if (!hj_agen) {
					document.getElementById('hj_agen-error').innerHTML ="<span style='color: red;'>Harga Jual Agn Harus Diisi.</span>";
					document.getElementById('hj_agen').focus();
					exit;
				}else document.getElementById('hj_agen-error').innerHTML ='';
				
				if (!hj_retail) {
					document.getElementById('hj_retail-error').innerHTML ="<span style='color: red;'>Harga Jual Ret Harus Diisi.</span>";
					document.getElementById('hj_retail').focus();
					exit;
				}else document.getElementById('hj_retail-error').innerHTML ='';
				
				if (!hj_whs) {
					document.getElementById('hj_whs-error').innerHTML ="<span style='color: red;'>Harga Jual WS Harus Diisi.</span>";
					document.getElementById('hj_whs').focus();
					exit;
				}else document.getElementById('hj_whs-error').innerHTML ='';
				
				if (status=='') {
					document.getElementById('status-error').innerHTML ="<span style='color: red;'>Status Harus Dipilih.</span>";
					document.getElementById('status').focus();
					exit;
				}else document.getElementById('status-error').innerHTML ='';
			}, 
		success:function(){	
			swal({
				    title: 'Tambah Atomizer Berhasil !',
				    text: 'Auto Close...',
				    icon: 'success',
				    timer: 4000,
				    showConfirmButton: false,
				})
			location.href="#";		
			location.reload(true)
		},
		url: '<?php echo $this->baseUrl();?>/atomizer/kirimdata',
		type: 'post',
		resetForm: false
	};
	
	function isNumber(evt) {
        var iKeyCode = (evt.which) ? evt.which : evt.keyCode
        if (iKeyCode != 46 && iKeyCode > 31 && (iKeyCode < 48 || iKeyCode > 57))
            return false;

        return true;
    } 
	
	function currency(){
		var harga_beli = document.getElementById("harga_beli").value;
		var harga_beli2 = harga_beli.replaceAll(".", "");
		var harga_beli3 = harga_beli2.toString().replaceAll(/(\d)(?=(\d\d\d)+(?!\d))/g, "$1.");
		document.getElementById("harga_beli").value=harga_beli3;
		
		var hj_agen = document.getElementById("hj_agen").value;
		var hj_agen2 = hj_agen.replaceAll(".", "");
		var hj_agen3 = hj_agen2.toString().replaceAll(/(\d)(?=(\d\d\d)+(?!\d))/g, "$1.");
		document.getElementById("hj_agen").value=hj_agen3;
		
		var hj_retail = document.getElementById("hj_retail").value;
		var hj_retail2 = hj_retail.replaceAll(".", "");
		var hj_retail3 = hj_retail2.toString().replaceAll(/(\d)(?=(\d\d\d)+(?!\d))/g, "$1.");
		document.getElementById("hj_retail").value=hj_retail3;
		
		var hj_whs = document.getElementById("hj_whs").value;
		var hj_whs2 = hj_whs.replaceAll(".", "");
		var hj_whs3 = hj_whs2.toString().replaceAll(/(\d)(?=(\d\d\d)+(?!\d))/g, "$1.");
		document.getElementById("hj_whs").value=hj_whs3;
	}
</script>
<script>
	$(".product").select2();
</script>