<head>
  <link href="<?php echo $this->baseUrl();?>/css/select2.min.css" rel="stylesheet">
  <link href="<?php echo $this->baseUrl();?>/css/fileinput/fileinput.min.css" rel="stylesheet">
  <script src="<?php echo $this->baseUrl();?>/lib/select2.full.min.js"></script>
  <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
  <script src="<?php echo $this->baseUrl();?>/lib/jquery-ui-1.9.2.custom.min.js"></script>
</head>
<style>
#backgroundPopup{  

display:none;  
position:fixed;  
_position:absolute; /* hack for internet explorer 6*/  
height:100%;  
width:100%;  
top:0;  
left:0; 
/*background: rgba(0, 0, 0, 0) url("../img/popup-bg.png");*/
background:rgba(0,0,0,0.85);  
border:1px solid #cecece;  
z-index:1040;  


}  
 
 
.box-popup1{
	position:fixed;
	top:30px;
	left:30px;
	width:40px;
	height:30px;
}
 

#popupContact{  

display:none;  
position:fixed;  
_position:absolute; /* hack for internet explorer 6*/  
height:100%; 
width:90%;  
background:#acacac;  
z-index:999999;  
font-size:13px;  
overflow:auto;
top:2px;
bottom:10px;
padding:15px;
margin: 1%;
}  




#popupContact h1{  
text-align:left;  
color:#6FA5FD;  
font-size:22px;  
font-weight:bold;  
border-bottom:1px dotted #D3D3D3;  
padding-bottom:2px;  
margin-bottom:20px;  
}  
#popupContact textarea{width:90%;height:100px;}
#popupContactClose{  
font-size:14px;  
line-height:14px;  
right:6px;  
top:4px;  
position:absolute;  
color:#6fa5fd;  
font-weight:bold;  
width:16px;
cursor:pointer;
display:block;  
background:url(../images/cross.png)
} 
</style>
<form id="frm_postdata" name="frm_postdata" enctype="multipart/form-data" method="POST">
	<input type="hidden" name="currentPage" id="currentPage" size="6" maxlength="6" value="<?php echo $this->numPage;?>" class="inputbox2 narrowkey1"></input>
		<?php 
			$seq = $this->seq;
			//var_dump($seq);
			$seq += 1;
			$seq=str_pad($seq, 5, '0', STR_PAD_LEFT);
		?>
		<input type="hidden" id='seq' name='seq' value ='<?php echo $seq;?>'>
		<div id="popupview"></div>
		<div class="panel">
            <fieldset class="panel-dt">							
				<!--h4><i class="fa fa-angle-right"></i> Tambah Stock Opname</h4-->
						<br>
					<div class="col-sm-12">
						<table width="100%">
							<tr>
								<td width="10%"><font style="font-size:12px;font-weight:bold;">Nomor Proses</font></td>
								<td width="1%">:</td>
								<td>
									<table>
										<td> <input name="no_proses" id="no_proses" type="text" maxlength="50" size="20" class="form-control input-sm" value="BS/VH/<?php echo date("Y");?>-<?php echo date("m");?>/<?php echo $seq;?>" readonly> </td>
										<td> &nbsp; <label id="no_proses-error" for="no_proses" class="error"></td>
									</table>
								</td>
							</tr> 
							<tr><td>&nbsp;</td></tr>
							<tr>
								<td width="10%"><font style="font-size:12px;font-weight:bold;">Tanggal Proses</font></td>
								<td width="1%">:</td>
								<td>
									<table>
										<td> 
											<input name="tgl_proses" id="tgl_proses" class="form-control form-control-inline input-medium" size="16" type="text" value="">
											<span class="input-group-btn add-on">
												<button class="btn btn-theme" type="button"><i class="fa fa-calendar"></i></button>
											</span>
										</td>
										<td> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <label id="tgl_proses-error" for="tgl_proses" class="error"></td>
									</table>
								</td>
							</tr> 
							<tr><td>&nbsp;</td></tr>
							<tr>
								<td width="10%"><font style="font-size:12px;font-weight:bold;">Uppload Gambar</font></td>
								<td width="1%">:</td>
								<td>
									<table>
									<td> 
										<div class="fileupload fileupload-new" data-provides="fileupload">
										  <div class="fileupload-new thumbnail" style="width: 200px; height: 150px;">
											<img src="http://www.placehold.it/200x150/EFEFEF/AAAAAA&text=no+image" alt="" />
										  </div>
										  <div class="fileupload-preview fileupload-exists thumbnail" style="max-width: 200px; max-height: 150px; line-height: 20px;"></div>
										  <div>
											<span class="btn btn-theme02 btn-file">
											  <span class="fileupload-new"><i class="fa fa-paperclip"></i> Select image</span>
											<span class="fileupload-exists"><i class="fa fa-undo"></i> Change</span>
											<input type="file" class="default" name="nama_file" id="nama_file">
											</span>
											<span><label id="nama_file-error" for="nama_file" class="error"></span>
										  </div>
										</div>
										<span class="label label-info">NOTE!</span>
										<span>Attached image thumbnail is supported in Latest Firefox, Chrome, Opera, Safari and Internet Explorer 10 only</span><br>
									<td></td>
									</table>
								</td>
							</tr> 
							<tr><td>&nbsp;</td></tr>
						</table>
						
						<div align='left'>
							<input type="button" class="right btn btn-success  btn-xs" style="font-weight:bold;" value="Tambah Barang" onclick="dataliquid()">
							<input type='hidden' name='counterx' id='counterx' value="0">
						</div>
						<br>
						<table width="100%" id="myTable" style="font-size:12px;" class="table-bordered">
							<tr bgcolor="#4ECDC4">
								<td width="25%" style="text-align:center;"> <font style="font-size:12px;font-weight:bold;">Kode Barang</font></td>
								<td width="25%" style="text-align:center;"> <font style="font-size:12px;font-weight:bold;">Nama Barang</font></td>
								<td width="9%" style="text-align:center;"> <font style="font-size:12px;font-weight:bold;">Keterangan</font></td>
								<td width="9%" style="text-align:center;"> <font style="font-size:12px;font-weight:bold;">Stock Pusat</font></td>
								<td width="9%" style="text-align:center;"> <font style="font-size:12px;font-weight:bold;">Bad Stock</font></td>
								<td width="9%" style="text-align:center;"> <font style="font-size:12px;font-weight:bold;">Qty</font></td>
								<td width="9%" style="text-align:center;"> <font style="font-size:12px;font-weight:bold;">Sisa</font></td>
								<td width="5%" style="text-align:center;"> <font style="font-size:12px;font-weight:bold;"></font></td>
							</tr>
						</table>
						<br>
					</div>				
			</fieldset>
		</div>
		
	</div>
</div>
<div class="col-lg-12">
<div class="form-group form-group-bottom" align="right">
						<input type="hidden" id="proses" name="proses" value="<?php echo $this->proses?>">	
						<br><br>
							
							<a href="badstockgudang">
							<button type="button" class="btn btn-theme02">
								<span class="fa fa-backward"></span> &nbsp;Kembali
							</button></a>
							<button type="button" class="btn btn-theme03" onCLick="PostData()">
								<span class="fa fa-save"></span> &nbsp;Simpan
							</button>
							
			</div>
</div>
</form>
  <script src="<?php echo $this->baseUrl();?>/lib/jquery.form.js"></script>
  <link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl();?>/css/sweetalert.css">
  <script src="<?php echo $this->baseUrl();?>/lib/sweetalert.min.js"></script>   
  <script src="<?php echo $this->baseUrl();?>/lib/jquery.scrollTo.min.js"></script>
  <script src="<?php echo $this->baseUrl();?>/lib/jquery.nicescroll.js" type="text/javascript"></script>
  <script type="text/javascript" src="lib/bootstrap-fileupload/bootstrap-fileupload.js"></script>
<script>
	function PostData(){
		//alert('Testing2');
        $("#frm_postdata").ajaxSubmit(post_data);
    }
	
	var post_data = {
		target:'',
		beforeSubmit: function() {	
			var tgl_proses 	 	  = document.getElementById('tgl_proses').value;
			var seq		 	 	  = document.getElementById('seq').value;
			var nama_file		  = document.getElementById('nama_file').value;
			//alert(nama_file);
				
				if (!tgl_proses) {
					document.getElementById('tgl_proses-error').innerHTML ="<span style='color: red;'>Tanggal Stock Opname Harus Diisi.</span>";
					document.getElementById('tgl_proses').focus();
					exit;
				}else document.getElementById('tgl_proses-error').innerHTML ='';
				if (!nama_file) {
					document.getElementById('nama_file-error').innerHTML ="<span style='color: red;'>File Image Harus Diisi.</span>";
					document.getElementById('nama_file').focus();
					exit;
				}else document.getElementById('nama_file-error').innerHTML ='';
			}, 
		success:function(){	
			swal({
				    title: 'Order Sukses !',
				    text: 'Auto Close...',
				    icon: 'success',
				    timer: 4000,
				    showConfirmButton: false,
				})
			location.href="#";		
			location.reload(true)
		},
		url: '<?php echo $this->baseUrl();?>/badstockgudang/kirimdata',
		type: 'post',
		resetForm: false
	};
	
	function isNumber(evt) {
        var iKeyCode = (evt.which) ? evt.which : evt.keyCode
        if (iKeyCode != 46 && iKeyCode > 31 && (iKeyCode < 48 || iKeyCode > 57))
            return false;

        return true;
    } 
	
	function closeDetil(){
	document.getElementById('popupContact').style.display = "none";
	disablePopup();
	}
	
	function deleterow(button,rows){
		var x = button.parentNode.parentNode.rowIndex;
		document.getElementById("myTable").deleteRow(x);
	}

	function pilih_barang(x){
		var nilai = x.value;
		if(nilai == 'Liquid'){
			dataliquid();
		} else if(nilai == 'Device'){
			datadevice();
		} else if(nilai == 'Aksesoris'){
			dataaksesoris();
		} else if(nilai == 'Atomizer'){
			dataatomizer();
		} 
	}
	
	function loadPopup() {
		var popupStatus = 0;
		if (popupStatus == 0) {
			jQuery("#backgroundPopup").css({"opacity": "1"});
			jQuery("#backgroundPopup").fadeIn("fast");
			jQuery("#popupContact").fadeIn("fast");
			popupStatus = 1
		}
	}

	function centerPopup() {
		var windowWidth = document.documentElement.clientWidth;
		var windowHeight = "1000%";
		var popupHeight = jQuery("#popupContact").height();
		var popupWidth = jQuery("#popupContact").width();
	}

	function closePopup() {
		document.getElementById('popupContact').style.display = "none";
		document.getElementById('backgroundPopup').style.display = "none";
	}

	function disablePopup() {
		document.getElementById('popupContact').style.display = "none";
		document.getElementById('backgroundPopup').style.display = "none";
	}
		
	function dataliquid(){
		var seq = document.getElementById('seq').value;
		
		//alert('maintain'); 
		
		var url = '<?php echo $this->basePath; ?>/badstockgudang/dataliquid';
		var opt = {seq:seq};
		
		jQuery.get(url,opt, function(data) {			
			jQuery("#popupview").html(data);
			centerPopup(); 
			loadPopup();		
		})
	}
	
	function datadevice(){
		var seq = document.getElementById('seq').value;
		
		//alert('maintain'); 
		
		var url = '<?php echo $this->basePath; ?>/badstockgudang/datadevice';
		var opt = {seq:seq};
		
		jQuery.get(url,opt, function(data) {			
			jQuery("#popupview").html(data);
			centerPopup(); 
			loadPopup();		
		})
	}
	
	function dataaksesoris(){
		var seq = document.getElementById('seq').value;
		
		//alert('maintain'); 
		
		var url = '<?php echo $this->basePath; ?>/badstockgudang/dataaksesoris';
		var opt = {seq:seq};
		
		jQuery.get(url,opt, function(data) {			
			jQuery("#popupview").html(data);
			centerPopup(); 
			loadPopup();		
		})
	}
	
	function dataatomizer(){
		var seq = document.getElementById('seq').value;
		
		//alert('maintain'); 
		
		var url = '<?php echo $this->basePath; ?>/badstockgudang/dataatomizer';
		var opt = {seq:seq};
		
		jQuery.get(url,opt, function(data) {			
			jQuery("#popupview").html(data);
			centerPopup(); 
			loadPopup();		
		})
	}
	
	function hitung(button){
		var x = button;
		
		var bad_stock = document.getElementById("bad_stock"+x).value;
		var bad_stock2 = bad_stock.replaceAll(".", "");
		
		var bad_stock_awal = document.getElementById("bad_stock_awal"+x).value;
		var bad_stock_awal2 = bad_stock_awal.replaceAll(".", "");
		
		var qty = document.getElementById("qty"+x).value;
		var qty2 = qty.replaceAll(".", "");
		
		var hitung_sisa = parseInt(bad_stock_awal2) - parseInt(qty2);
		var hitung_sisa2 = hitung_sisa.toString().replaceAll(/(\d)(?=(\d\d\d)+(?!\d))/g, "$1.");
		document.getElementById("sisa"+x).value=hitung_sisa2;
	}
	
</script>
  <script>
   $(".product").select2();
  </script>
  <script>
   $(document).ready(function(){
    $(function() {
      $('#tgl_proses').datepicker({
        dateFormat: 'dd/mm/yy',
        changeMonth: true,
        changeYear: true
      });
    });
  });
  </script>